Sensorclient: Core/Inc/crc.h File Reference
crc.h File Reference
This file contains all the function prototypes for the crc.c file.
#include "main.h"
Functions
void MX_CRC_Init (void)
Variables
CRC_HandleTypeDef hcrc
Detailed Description
This file contains all the function prototypes for the crc.c file.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file crc.h.
Function Documentation
MX_CRC_Init()
void MX_CRC_Init (void)
Definition at line 30 of file crc.c.
References CRC, CRC_INPUTDATA_FORMAT_BYTES, CRC_INPUTDATA_INVERSION_NONE, CRC_OUTPUTDATA_INVERSION_DISABLE, DEFAULT_INIT_VALUE_ENABLE, DEFAULT_POLYNOMIAL_ENABLE, CRC_InitTypeDef::DefaultInitValueUse, CRC_InitTypeDef::DefaultPolynomialUse, Error_Handler(), HAL_CRC_Init(), HAL_OK, hcrc, CRC_HandleTypeDef::Init, CRC_HandleTypeDef::InputDataFormat, CRC_InitTypeDef::InputDataInversionMode, CRC_HandleTypeDef::Instance, and CRC_InitTypeDef::OutputDataInversionMode.
Referenced by main().
Variable Documentation
hcrc
CRC_HandleTypeDef hcrc
Definition at line 27 of file crc.c.
Referenced by MX_CRC_Init().