Sensorclient: Core/Src/dma2d.c File Reference
dma2d.c File Reference
This file provides code for the configuration of the DMA2D instances.
#include "dma2d.h"
Functions
void MX_DMA2D_Init (void)
void HAL_DMA2D_MspInit (DMA2D_HandleTypeDef *dma2dHandle)
void HAL_DMA2D_MspDeInit (DMA2D_HandleTypeDef *dma2dHandle)
Variables
DMA2D_HandleTypeDef hdma2d
Detailed Description
This file provides code for the configuration of the DMA2D instances.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file dma2d.c.
Function Documentation
HAL_DMA2D_MspDeInit()
void HAL_DMA2D_MspDeInit (DMA2D_HandleTypeDef * dma2dHandle)
Definition at line 82 of file dma2d.c.
References DMA2D, DMA2D_IRQn, and HAL_NVIC_DisableIRQ().
HAL_DMA2D_MspInit()
void HAL_DMA2D_MspInit (DMA2D_HandleTypeDef * dma2dHandle)
Definition at line 62 of file dma2d.c.
References DMA2D, DMA2D_IRQn, HAL_NVIC_EnableIRQ(), and HAL_NVIC_SetPriority().
MX_DMA2D_Init()
void MX_DMA2D_Init (void)
Definition at line 30 of file dma2d.c.
References DMA2D, Error_Handler(), HAL_OK, and hdma2d.
Referenced by main().
Variable Documentation
hdma2d
DMA2D_HandleTypeDef hdma2d
Definition at line 27 of file dma2d.c.
Referenced by DMA2D_IRQHandler(), and MX_DMA2D_Init().