Sensorclient: LWIP/Target/ethernetif.c File Reference
ethernetif.c File Reference
#include "main.h"
#include "lwip/opt.h"
#include "lwip/mem.h"
#include "lwip/memp.h"
#include "lwip/timeouts.h"
#include "netif/ethernet.h"
#include "netif/etharp.h"
#include "lwip/ethip6.h"
#include "ethernetif.h"
#include "lan8742.h"
#include <string.h>
Classes
struct RxBuff_t
Macros
#define IFNAME0 's'
#define IFNAME1 't'
#define ETH_DMA_TRANSMIT_TIMEOUT (20U)
#define ETH_TX_BUFFER_MAX ((ETH_TX_DESC_CNT) * 2U)
#define ETH_RX_BUFFER_CNT 12U
Enumerations
enum RxAllocStatusTypeDef { RX_ALLOC_OK = 0x00, RX_ALLOC_ERROR = 0x01 }
Functions
LWIP_MEMPOOL_DECLARE (RX_POOL, ETH_RX_BUFFER_CNT, sizeof(RxBuff_t), "Zero-copy RX PBUF pool")
int32_t ETH_PHY_IO_Init (void)
Initializes the MDIO interface GPIO and clocks.
int32_t ETH_PHY_IO_DeInit (void)
De-Initializes the MDIO interface .
int32_t ETH_PHY_IO_ReadReg (uint32_t DevAddr, uint32_t RegAddr, uint32_t *pRegVal)
Read a PHY register through the MDIO interface.
int32_t ETH_PHY_IO_WriteReg (uint32_t DevAddr, uint32_t RegAddr, uint32_t RegVal)
Write a value to a PHY register through the MDIO interface.
int32_t ETH_PHY_IO_GetTick (void)
Get the time in millisecons used for internal PHY driver process.
void pbuf_free_custom (struct pbuf *p)
Custom Rx pbuf free callback.
static void low_level_init (struct netif *netif)
In this function, the hardware should be initialized. Called from ethernetif_init().
static err_t low_level_output (struct netif *netif, struct pbuf *p)
This function should do the actual transmission of the packet. The packet is contained in the pbuf that is passed to the function. This pbuf might be chained.
static struct pbuf * low_level_input (struct netif *netif)
Should allocate a pbuf and transfer the bytes of the incoming packet from the interface into the pbuf.
void ethernetif_input (struct netif *netif)
This function should be called when a packet is ready to be read from the interface. It uses the function low_level_input() that should handle the actual reception of bytes from the network interface. Then the type of the received packet is determined and the appropriate input function is called.
static err_t low_level_output_arp_off (struct netif *netif, struct pbuf *q, const ip4_addr_t *ipaddr)
err_t ethernetif_init (struct netif *netif)
Should be called at the beginning of the program to set up the network interface. It calls the function low_level_init() to do the actual setup of the hardware.
u32_t sys_now (void)
Returns the current time in milliseconds when LWIP_TIMERS == 1 and NO_SYS == 1.
void HAL_ETH_MspInit (ETH_HandleTypeDef *ethHandle)
Initializes the ETH MSP.
void HAL_ETH_MspDeInit (ETH_HandleTypeDef *ethHandle)
void ethernet_link_check_state (struct netif *netif)
Check the ETH link state then update ETH driver and netif link accordingly.
void HAL_ETH_RxAllocateCallback (uint8_t **buff)
void HAL_ETH_RxLinkCallback (void **pStart, void **pEnd, uint8_t *buff, uint16_t Length)
void HAL_ETH_TxFreeCallback (uint32_t *buff)
Variables
static uint8_t RxAllocStatus
ETH_HandleTypeDef heth
ETH_TxPacketConfig TxConfig
lan8742_Object_t LAN8742
lan8742_IOCtx_t LAN8742_IOCtx
Macro Definition Documentation
ETH_DMA_TRANSMIT_TIMEOUT
#define ETH_DMA_TRANSMIT_TIMEOUT (20U)
Definition at line 46 of file ethernetif.c.
ETH_RX_BUFFER_CNT
#define ETH_RX_BUFFER_CNT 12U
Definition at line 90 of file ethernetif.c.
ETH_TX_BUFFER_MAX
#define ETH_TX_BUFFER_MAX ((ETH_TX_DESC_CNT) * 2U)
Definition at line 47 of file ethernetif.c.
IFNAME0
#define IFNAME0 's'
File Name : ethernetif.c Description : This file provides code for the configuration of the ethernetif.c MiddleWare.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition at line 42 of file ethernetif.c.
IFNAME1
#define IFNAME1 't'
Definition at line 43 of file ethernetif.c.
Enumeration Type Documentation
RxAllocStatusTypeDef
enum RxAllocStatusTypeDef
Enumerator
RX_ALLOC_OK
RX_ALLOC_ERROR
Definition at line 77 of file ethernetif.c.
Function Documentation
ETH_PHY_IO_DeInit()
int32_t ETH_PHY_IO_DeInit (void)
De-Initializes the MDIO interface .
Parameters
None
Return values
0 if OK, -1 if ERROR
Definition at line 570 of file ethernetif.c.
ETH_PHY_IO_GetTick()
int32_t ETH_PHY_IO_GetTick (void)
Get the time in millisecons used for internal PHY driver process.
Return values
Time value
Definition at line 613 of file ethernetif.c.
ETH_PHY_IO_Init()
int32_t ETH_PHY_IO_Init (void)
Initializes the MDIO interface GPIO and clocks.
Parameters
None
Return values
0 if OK, -1 if ERROR
Definition at line 553 of file ethernetif.c.
ETH_PHY_IO_ReadReg()
int32_t ETH_PHY_IO_ReadReg (uint32_t DevAddr, uint32_t RegAddr, uint32_t * pRegVal)
Read a PHY register through the MDIO interface.
Parameters
DevAddr PHY port address
RegAddr PHY register address
pRegVal pointer to hold the register value
Return values
0 if OK -1 if Error
Definition at line 582 of file ethernetif.c.
ETH_PHY_IO_WriteReg()
int32_t ETH_PHY_IO_WriteReg (uint32_t DevAddr, uint32_t RegAddr, uint32_t RegVal)
Write a value to a PHY register through the MDIO interface.
Parameters
DevAddr PHY port address
RegAddr PHY register address
RegVal Value to be written
Return values
0 if OK -1 if Error
Definition at line 599 of file ethernetif.c.
ethernet_link_check_state()
void ethernet_link_check_state (struct netif * netif)
Check the ETH link state then update ETH driver and netif link accordingly.
Return values
None
Definition at line 622 of file ethernetif.c.
Referenced by Ethernet_Link_Periodic_Handle().
ethernetif_init()
err_t ethernetif_init (struct netif * netif)
Should be called at the beginning of the program to set up the network interface. It calls the function low_level_init() to do the actual setup of the hardware.
This function should be passed as a parameter to netif_add().
Parameters
netif the lwip network interface structure for this ethernetif
Returns
ERR_OK if the loopif is initialized ERR_MEM if private data couldn't be allocated any other err_t on error
Definition at line 375 of file ethernetif.c.
Referenced by MX_LWIP_Init().
ethernetif_input()
void ethernetif_input (struct netif * netif)
This function should be called when a packet is ready to be read from the interface. It uses the function low_level_input() that should handle the actual reception of bytes from the network interface. Then the type of the received packet is determined and the appropriate input function is called.
Parameters
netif the lwip network interface structure for this ethernetif
Definition at line 325 of file ethernetif.c.
Referenced by MX_LWIP_Process().
HAL_ETH_MspDeInit()
void HAL_ETH_MspDeInit (ETH_HandleTypeDef * ethHandle)
ETH GPIO Configuration PG14 ---—> ETH_TXD1 PG13 ---—> ETH_TXD0 PG11 ---—> ETH_TX_EN PC1 ---—> ETH_MDC PA1 ---—> ETH_REF_CLK PC4 ---—> ETH_RXD0 PA2 ---—> ETH_MDIO PC5 ---—> ETH_RXD1 PA7 ---—> ETH_CRS_DV
Definition at line 513 of file ethernetif.c.
References ETH, GPIOA, GPIOC, GPIOG, HAL_GPIO_DeInit(), RMII_CRS_DV_Pin, RMII_MDC_Pin, RMII_MDIO_Pin, RMII_REF_CLK_Pin, RMII_RXD0_Pin, RMII_RXD1_Pin, RMII_TX_EN_Pin, RMII_TXD0_Pin, and RMII_TXD1_Pin.
HAL_ETH_MspInit()
void HAL_ETH_MspInit (ETH_HandleTypeDef * ethHandle)
Initializes the ETH MSP.
Parameters
ethHandle ETH handle
Return values
None
ETH GPIO Configuration PG14 ---—> ETH_TXD1 PG13 ---—> ETH_TXD0 PG11 ---—> ETH_TX_EN PC1 ---—> ETH_MDC PA1 ---—> ETH_REF_CLK PC4 ---—> ETH_RXD0 PA2 ---—> ETH_MDIO PC5 ---—> ETH_RXD1 PA7 ---—> ETH_CRS_DV
Definition at line 461 of file ethernetif.c.
HAL_ETH_RxAllocateCallback()
void HAL_ETH_RxAllocateCallback (uint8_t ** buff)
Definition at line 679 of file ethernetif.c.
HAL_ETH_RxLinkCallback()
void HAL_ETH_RxLinkCallback (void ** pStart, void ** pEnd, uint8_t * buff, uint16_t Length)
Definition at line 701 of file ethernetif.c.
HAL_ETH_TxFreeCallback()
void HAL_ETH_TxFreeCallback (uint32_t * buff)
Definition at line 741 of file ethernetif.c.
low_level_init()
static void low_level_init (struct netif * netif) static
In this function, the hardware should be initialized. Called from ethernetif_init().
Parameters
netif the already initialized lwip network interface structure for this ethernetif
Definition at line 157 of file ethernetif.c.
low_level_input()
static struct pbuf* low_level_input (struct netif * netif) static
Should allocate a pbuf and transfer the bytes of the incoming packet from the interface into the pbuf.
Parameters
netif the lwip network interface structure for this ethernetif
Returns
a pbuf filled with the received packet (including MAC header) NULL on memory error
Definition at line 304 of file ethernetif.c.
low_level_output()
static err_t low_level_output (struct netif * netif, struct pbuf * p) static
This function should do the actual transmission of the packet. The packet is contained in the pbuf that is passed to the function. This pbuf might be chained.
Parameters
netif the lwip network interface structure for this ethernetif
p the MAC packet to send (e.g. IP packet including MAC addresses and type)
Returns
ERR_OK if the packet could be sent an err_t value if the packet couldn't be sent
Note
Returning ERR_MEM here if a DMA queue of your MAC is full can lead to strange results. You might consider waiting for space in the DMA queue to become available since the stack doesn't retry to send a packet dropped because of memory failure (except for the TCP timers).
Definition at line 257 of file ethernetif.c.
low_level_output_arp_off()
static err_t low_level_output_arp_off (struct netif * netif, struct pbuf * q, const ip4_addr_t * ipaddr) static
This function has to be completed by user in case of ARP OFF.
Parameters
netif the lwip network interface structure for this ethernetif
Returns
ERR_OK if ...
Definition at line 349 of file ethernetif.c.
LWIP_MEMPOOL_DECLARE()
LWIP_MEMPOOL_DECLARE (RX_POOL , ETH_RX_BUFFER_CNT , sizeof(RxBuff_t) , "Zero-copy RX PBUF pool")
pbuf_free_custom()
void pbuf_free_custom (struct pbuf * p)
Custom Rx pbuf free callback.
Parameters
pbuf pbuf to be freed
Return values
None
Definition at line 426 of file ethernetif.c.
Variable Documentation
heth
ETH_HandleTypeDef heth
File Name : LWIP.h Description : This file provides code for the configuration of the LWIP.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition at line 120 of file ethernetif.c.
LAN8742
lan8742_Object_t LAN8742
Definition at line 130 of file ethernetif.c.
LAN8742_IOCtx
lan8742_IOCtx_t LAN8742_IOCtx
Initial value:
= {ETH_PHY_IO_Init,
                                  ETH_PHY_IO_DeInit,
                                  ETH_PHY_IO_WriteReg,
                                  ETH_PHY_IO_ReadReg,
                                  ETH_PHY_IO_GetTick}
Definition at line 131 of file ethernetif.c.
RxAllocStatus
uint8_t RxAllocStatus static
IAR Compiler
Definition at line 94 of file ethernetif.c.
TxConfig
ETH_TxPacketConfig TxConfig
Definition at line 121 of file ethernetif.c.