Sensorclient: LWIP/Target/ethernetif.h File Reference
ethernetif.h File Reference
#include "lwip/err.h"
#include "lwip/netif.h"
Functions
err_t ethernetif_init (struct netif *netif)
Should be called at the beginning of the program to set up the network interface. It calls the function low_level_init() to do the actual setup of the hardware.
void ethernetif_input (struct netif *netif)
This function should be called when a packet is ready to be read from the interface. It uses the function low_level_input() that should handle the actual reception of bytes from the network interface. Then the type of the received packet is determined and the appropriate input function is called.
void ethernet_link_check_state (struct netif *netif)
Check the ETH link state then update ETH driver and netif link accordingly.
void Error_Handler (void)
This function is executed in case of error occurrence.
u32_t sys_jiffies (void)
u32_t sys_now (void)
Returns the current time in milliseconds when LWIP_TIMERS == 1 and NO_SYS == 1.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 254 of file main.c.
References __disable_irq().
Referenced by PeriphCommonClock_Config(), and SystemClock_Config().
ethernet_link_check_state()
void ethernet_link_check_state (struct netif * netif)
Check the ETH link state then update ETH driver and netif link accordingly.
Return values
None
Definition at line 622 of file ethernetif.c.
Referenced by Ethernet_Link_Periodic_Handle().
ethernetif_init()
err_t ethernetif_init (struct netif * netif)
Should be called at the beginning of the program to set up the network interface. It calls the function low_level_init() to do the actual setup of the hardware.
File Name : ethernetif.h Description : This file provides initialization code for LWIP middleWare.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
This function should be passed as a parameter to netif_add().
Parameters
netif the lwip network interface structure for this ethernetif
Returns
ERR_OK if the loopif is initialized ERR_MEM if private data couldn't be allocated any other err_t on error
Definition at line 375 of file ethernetif.c.
Referenced by MX_LWIP_Init().
ethernetif_input()
void ethernetif_input (struct netif * netif)
This function should be called when a packet is ready to be read from the interface. It uses the function low_level_input() that should handle the actual reception of bytes from the network interface. Then the type of the received packet is determined and the appropriate input function is called.
Parameters
netif the lwip network interface structure for this ethernetif
Definition at line 325 of file ethernetif.c.
Referenced by MX_LWIP_Process().
sys_jiffies()
u32_t sys_jiffies (void)
sys_now()
u32_t sys_now (void)
Returns the current time in milliseconds when LWIP_TIMERS == 1 and NO_SYS == 1.
Parameters
None
Return values
Current Time value
Definition at line 448 of file ethernetif.c.