Sensorclient: Core/Inc/fmc.h File Reference
fmc.h File Reference
#include "main.h"
Functions
void MX_FMC_Init (void)
void HAL_SDRAM_MspInit (SDRAM_HandleTypeDef *hsdram)
void HAL_SDRAM_MspDeInit (SDRAM_HandleTypeDef *hsdram)
Variables
SDRAM_HandleTypeDef hsdram1
Function Documentation
HAL_SDRAM_MspDeInit()
void HAL_SDRAM_MspDeInit (SDRAM_HandleTypeDef * hsdram)
Definition at line 342 of file fmc.c.
HAL_SDRAM_MspInit()
void HAL_SDRAM_MspInit (SDRAM_HandleTypeDef * hsdram)
Definition at line 229 of file fmc.c.
MX_FMC_Init()
void MX_FMC_Init (void)
Perform the SDRAM1 memory initialization sequence
Definition at line 31 of file fmc.c.
References FMC_SDRAM_InitTypeDef::CASLatency, FMC_SDRAM_InitTypeDef::ColumnBitsNumber, Error_Handler(), FMC_SDRAM_TimingTypeDef::ExitSelfRefreshDelay, FMC_SDRAM_BANK2, FMC_SDRAM_CAS_LATENCY_3, FMC_SDRAM_CLOCK_PERIOD_2, FMC_SDRAM_COLUMN_BITS_NUM_8, FMC_SDRAM_DEVICE, FMC_SDRAM_INTERN_BANKS_NUM_4, FMC_SDRAM_MEM_BUS_WIDTH_32, FMC_SDRAM_RBURST_DISABLE, FMC_SDRAM_ROW_BITS_NUM_12, FMC_SDRAM_RPIPE_DELAY_0, FMC_SDRAM_WRITE_PROTECTION_DISABLE, HAL_OK, HAL_SDRAM_Init(), hsdram1, SDRAM_HandleTypeDef::Init, SDRAM_HandleTypeDef::Instance, FMC_SDRAM_InitTypeDef::InternalBankNumber, FMC_SDRAM_TimingTypeDef::LoadToActiveDelay, FMC_SDRAM_InitTypeDef::MemoryDataWidth, FMC_SDRAM_TimingTypeDef::RCDDelay, FMC_SDRAM_InitTypeDef::ReadBurst, FMC_SDRAM_InitTypeDef::ReadPipeDelay, FMC_SDRAM_InitTypeDef::RowBitsNumber, FMC_SDRAM_TimingTypeDef::RowCycleDelay, FMC_SDRAM_TimingTypeDef::RPDelay, FMC_SDRAM_InitTypeDef::SDBank, FMC_SDRAM_InitTypeDef::SDClockPeriod, FMC_SDRAM_TimingTypeDef::SelfRefreshTime, FMC_SDRAM_InitTypeDef::WriteProtection, and FMC_SDRAM_TimingTypeDef::WriteRecoveryTime.
Referenced by main().
Variable Documentation
hsdram1
SDRAM_HandleTypeDef hsdram1
File Name : FMC.h Description : This file provides code for the configuration of the FMC peripheral.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
File Name : FMC.c Description : This file provides code for the configuration of the FMC peripheral.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition at line 28 of file fmc.c.
Referenced by MX_FMC_Init().