Sensorclient: Core/Src/fmc.c File Reference
fmc.c File Reference
#include "fmc.h"
Functions
void MX_FMC_Init (void)
static void HAL_FMC_MspInit (void)
void HAL_SDRAM_MspInit (SDRAM_HandleTypeDef *sdramHandle)
static void HAL_FMC_MspDeInit (void)
void HAL_SDRAM_MspDeInit (SDRAM_HandleTypeDef *sdramHandle)
Variables
SDRAM_HandleTypeDef hsdram1
static uint32_t FMC_Initialized = 0
static uint32_t FMC_DeInitialized = 0
Function Documentation
HAL_FMC_MspDeInit()
static void HAL_FMC_MspDeInit (void) static
FMC GPIO Configuration PE1 ---—> FMC_NBL1 PE0 ---—> FMC_NBL0 PG15 ---—> FMC_SDNCAS PD0 ---—> FMC_D2 PI4 ---—> FMC_NBL2 PD1 ---—> FMC_D3 PI3 ---—> FMC_D27 PI2 ---—> FMC_D26 PF0 ---—> FMC_A0 PI5 ---—> FMC_NBL3 PI7 ---—> FMC_D29 PI10 ---—> FMC_D31 PI6 ---—> FMC_D28 PH15 ---—> FMC_D23 PI1 ---—> FMC_D25 PF1 ---—> FMC_A1 PI9 ---—> FMC_D30 PH13 ---—> FMC_D21 PH14 ---—> FMC_D22 PI0 ---—> FMC_D24 PF2 ---—> FMC_A2 PF3 ---—> FMC_A3 PG8 ---—> FMC_SDCLK PF4 ---—> FMC_A4 PH5 ---—> FMC_SDNWE PH3 ---—> FMC_SDNE0 PF5 ---—> FMC_A5 PD15 ---—> FMC_D1 PD10 ---—> FMC_D15 PC3 ---—> FMC_SDCKE0 PD14 ---—> FMC_D0 PD9 ---—> FMC_D14 PD8 ---—> FMC_D13 PF12 ---—> FMC_A6 PG1 ---—> FMC_A11 PF15 ---—> FMC_A9 PH12 ---—> FMC_D20 PF13 ---—> FMC_A7 PG0 ---—> FMC_A10 PE8 ---—> FMC_D5 PG5 ---—> FMC_BA1 PG4 ---—> FMC_BA0 PH7 ---—> FMC_SDCKE1 PH9 ---—> FMC_D17 PH11 ---—> FMC_D19 PF14 ---—> FMC_A8 PF11 ---—> FMC_SDNRAS PE9 ---—> FMC_D6 PE11 ---—> FMC_D8 PE14 ---—> FMC_D11 PH6 ---—> FMC_SDNE1 PH8 ---—> FMC_D16 PH10 ---—> FMC_D18 PE7 ---—> FMC_D4 PE10 ---—> FMC_D7 PE12 ---—> FMC_D9 PE15 ---—> FMC_D12 PE13 ---—> FMC_D10
Definition at line 241 of file fmc.c.
References __HAL_RCC_FMC_CLK_DISABLE, FMC_DeInitialized, FMC_SDCKE0_GPIO_Port, FMC_SDCKE0_Pin, FMC_SDNE0_Pin, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_8, GPIO_PIN_9, GPIOD, GPIOE, GPIOF, GPIOG, GPIOH, GPIOI, and HAL_GPIO_DeInit().
Referenced by HAL_SDRAM_MspDeInit().
HAL_FMC_MspInit()
static void HAL_FMC_MspInit (void) static
FMC GPIO Configuration PE1 ---—> FMC_NBL1 PE0 ---—> FMC_NBL0 PG15 ---—> FMC_SDNCAS PD0 ---—> FMC_D2 PI4 ---—> FMC_NBL2 PD1 ---—> FMC_D3 PI3 ---—> FMC_D27 PI2 ---—> FMC_D26 PF0 ---—> FMC_A0 PI5 ---—> FMC_NBL3 PI7 ---—> FMC_D29 PI10 ---—> FMC_D31 PI6 ---—> FMC_D28 PH15 ---—> FMC_D23 PI1 ---—> FMC_D25 PF1 ---—> FMC_A1 PI9 ---—> FMC_D30 PH13 ---—> FMC_D21 PH14 ---—> FMC_D22 PI0 ---—> FMC_D24 PF2 ---—> FMC_A2 PF3 ---—> FMC_A3 PG8 ---—> FMC_SDCLK PF4 ---—> FMC_A4 PH5 ---—> FMC_SDNWE PH3 ---—> FMC_SDNE0 PF5 ---—> FMC_A5 PD15 ---—> FMC_D1 PD10 ---—> FMC_D15 PC3 ---—> FMC_SDCKE0 PD14 ---—> FMC_D0 PD9 ---—> FMC_D14 PD8 ---—> FMC_D13 PF12 ---—> FMC_A6 PG1 ---—> FMC_A11 PF15 ---—> FMC_A9 PH12 ---—> FMC_D20 PF13 ---—> FMC_A7 PG0 ---—> FMC_A10 PE8 ---—> FMC_D5 PG5 ---—> FMC_BA1 PG4 ---—> FMC_BA0 PH7 ---—> FMC_SDCKE1 PH9 ---—> FMC_D17 PH11 ---—> FMC_D19 PF14 ---—> FMC_A8 PF11 ---—> FMC_SDNRAS PE9 ---—> FMC_D6 PE11 ---—> FMC_D8 PE14 ---—> FMC_D11 PH6 ---—> FMC_SDNE1 PH8 ---—> FMC_D16 PH10 ---—> FMC_D18 PE7 ---—> FMC_D4 PE10 ---—> FMC_D7 PE12 ---—> FMC_D9 PE15 ---—> FMC_D12 PE13 ---—> FMC_D10
Definition at line 78 of file fmc.c.
References __HAL_RCC_FMC_CLK_ENABLE, GPIO_InitTypeDef::Alternate, FMC_Initialized, FMC_SDCKE0_GPIO_Port, FMC_SDCKE0_Pin, FMC_SDNE0_Pin, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_8, GPIO_PIN_9, GPIO_SPEED_FREQ_VERY_HIGH, GPIOD, GPIOE, GPIOF, GPIOG, GPIOH, GPIOI, HAL_GPIO_Init(), GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, and GPIO_InitTypeDef::Speed.
Referenced by HAL_SDRAM_MspInit().
MX_FMC_Init()
void MX_FMC_Init (void)
Perform the SDRAM1 memory initialization sequence
Definition at line 31 of file fmc.c.
References FMC_SDRAM_InitTypeDef::CASLatency, FMC_SDRAM_InitTypeDef::ColumnBitsNumber, Error_Handler(), FMC_SDRAM_TimingTypeDef::ExitSelfRefreshDelay, FMC_SDRAM_BANK2, FMC_SDRAM_CAS_LATENCY_3, FMC_SDRAM_CLOCK_PERIOD_2, FMC_SDRAM_COLUMN_BITS_NUM_8, FMC_SDRAM_DEVICE, FMC_SDRAM_INTERN_BANKS_NUM_4, FMC_SDRAM_MEM_BUS_WIDTH_32, FMC_SDRAM_RBURST_DISABLE, FMC_SDRAM_ROW_BITS_NUM_12, FMC_SDRAM_RPIPE_DELAY_0, FMC_SDRAM_WRITE_PROTECTION_DISABLE, HAL_OK, HAL_SDRAM_Init(), hsdram1, SDRAM_HandleTypeDef::Init, SDRAM_HandleTypeDef::Instance, FMC_SDRAM_InitTypeDef::InternalBankNumber, FMC_SDRAM_TimingTypeDef::LoadToActiveDelay, FMC_SDRAM_InitTypeDef::MemoryDataWidth, FMC_SDRAM_TimingTypeDef::RCDDelay, FMC_SDRAM_InitTypeDef::ReadBurst, FMC_SDRAM_InitTypeDef::ReadPipeDelay, FMC_SDRAM_InitTypeDef::RowBitsNumber, FMC_SDRAM_TimingTypeDef::RowCycleDelay, FMC_SDRAM_TimingTypeDef::RPDelay, FMC_SDRAM_InitTypeDef::SDBank, FMC_SDRAM_InitTypeDef::SDClockPeriod, FMC_SDRAM_TimingTypeDef::SelfRefreshTime, FMC_SDRAM_InitTypeDef::WriteProtection, and FMC_SDRAM_TimingTypeDef::WriteRecoveryTime.
Referenced by main().
Variable Documentation
FMC_DeInitialized
uint32_t FMC_DeInitialized = 0 static
Definition at line 239 of file fmc.c.
Referenced by HAL_FMC_MspDeInit().
FMC_Initialized
uint32_t FMC_Initialized = 0 static
Definition at line 76 of file fmc.c.
Referenced by HAL_FMC_MspInit().
hsdram1
SDRAM_HandleTypeDef hsdram1
File Name : FMC.c Description : This file provides code for the configuration of the FMC peripheral.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition at line 28 of file fmc.c.
Referenced by MX_FMC_Init().