Sensorclient: Core/Src/gpio.c File Reference
gpio.c File Reference
This file provides code for the configuration of all used GPIO pins.
#include "gpio.h"
Functions
void MX_GPIO_Init (void)
Detailed Description
This file provides code for the configuration of all used GPIO pins.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file gpio.c.
Function Documentation
MX_GPIO_Init()
void MX_GPIO_Init (void)
Configure pins PE2 ---—> QUADSPI_BK1_IO2 PB5 ---—> USB_OTG_HS_ULPI_D7 PB6 ---—> QUADSPI_BK1_NCS PH4 ---—> USB_OTG_HS_ULPI_NXT PB13 ---—> USB_OTG_HS_ULPI_D6 PB12 ---—> USB_OTG_HS_ULPI_D5 PC0 ---—> USB_OTG_HS_ULPI_STP PC2 ---—> USB_OTG_HS_ULPI_DIR PB2 ---—> QUADSPI_CLK PD12 ---—> QUADSPI_BK1_IO1 PD13 ---—> QUADSPI_BK1_IO3 PD11 ---—> QUADSPI_BK1_IO0 PA5 ---—> USB_OTG_HS_ULPI_CK PA3 ---—> USB_OTG_HS_ULPI_D0 PB1 ---—> USB_OTG_HS_ULPI_D2 PB0 ---—> USB_OTG_HS_ULPI_D1 PB11 ---—> USB_OTG_HS_ULPI_D4
Definition at line 54 of file gpio.c.
References __HAL_RCC_GPIOA_CLK_ENABLE, __HAL_RCC_GPIOB_CLK_ENABLE, __HAL_RCC_GPIOC_CLK_ENABLE, __HAL_RCC_GPIOD_CLK_ENABLE, __HAL_RCC_GPIOE_CLK_ENABLE, __HAL_RCC_GPIOF_CLK_ENABLE, __HAL_RCC_GPIOG_CLK_ENABLE, __HAL_RCC_GPIOH_CLK_ENABLE, __HAL_RCC_GPIOI_CLK_ENABLE, GPIO_InitTypeDef::Alternate, Audio_INT_GPIO_Port, Audio_INT_Pin, EXT_RST_GPIO_Port, EXT_RST_Pin, GPIO_MODE_AF_PP, GPIO_MODE_EVT_RISING, GPIO_MODE_INPUT, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_PIN_2, GPIO_PIN_RESET, GPIO_SPEED_FREQ_LOW, GPIO_SPEED_FREQ_VERY_HIGH, GPIOA, GPIOB, GPIOC, GPIOD, HAL_GPIO_Init(), HAL_GPIO_WritePin(), GPIO_InitTypeDef::Mode, NC2_GPIO_Port, NC2_Pin, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, QSPI_D0_Pin, QSPI_D1_Pin, QSPI_D2_GPIO_Port, QSPI_D2_Pin, QSPI_D3_Pin, QSPI_NCS_GPIO_Port, QSPI_NCS_Pin, RMII_RXER_GPIO_Port, RMII_RXER_Pin, GPIO_InitTypeDef::Speed, ULPI_CLK_Pin, ULPI_D0_Pin, ULPI_D1_Pin, ULPI_D2_Pin, ULPI_D4_Pin, ULPI_D5_Pin, ULPI_D6_Pin, ULPI_D7_Pin, ULPI_DIR_Pin, ULPI_NXT_GPIO_Port, ULPI_NXT_Pin, ULPI_STP_Pin, USERBUTTON_GPIO_Port, and USERBUTTON_Pin.
Referenced by main().