Sensorclient: SAI_Exported_Functions_Group1
SAI_Exported_Functions_Group1
STM32F7xx_HAL_Driver » SAI » SAI_Exported_Functions
Functions
HAL_StatusTypeDef HAL_SAI_InitProtocol (SAI_HandleTypeDef *hsai, uint32_t protocol, uint32_t datasize, uint32_t nbslot)
HAL_StatusTypeDef HAL_SAI_Init (SAI_HandleTypeDef *hsai)
HAL_StatusTypeDef HAL_SAI_DeInit (SAI_HandleTypeDef *hsai)
void HAL_SAI_MspInit (SAI_HandleTypeDef *hsai)
void HAL_SAI_MspDeInit (SAI_HandleTypeDef *hsai)
Detailed Description
Function Documentation
HAL_SAI_DeInit()
HAL_StatusTypeDef HAL_SAI_DeInit (SAI_HandleTypeDef * hsai)
HAL_SAI_Init()
HAL_StatusTypeDef HAL_SAI_Init (SAI_HandleTypeDef * hsai)
Referenced by BSP_AUDIO_OUT_SetAudioFrameSlot(), and BSP_AUDIO_OUT_SetFrequency().
HAL_SAI_InitProtocol()
HAL_StatusTypeDef HAL_SAI_InitProtocol (SAI_HandleTypeDef * hsai, uint32_t protocol, uint32_t datasize, uint32_t nbslot)
Referenced by MX_SAI1_Init().
HAL_SAI_MspDeInit()
void HAL_SAI_MspDeInit (SAI_HandleTypeDef * hsai)
SAI1_A_Block_A GPIO Configuration PE4 ---—> SAI1_FS_A PE5 ---—> SAI1_SCK_A PE6 ---—> SAI1_SD_A
Definition at line 97 of file sai.c.
References __HAL_RCC_SAI1_CLK_DISABLE, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIOE, HAL_GPIO_DeInit(), HAL_NVIC_DisableIRQ(), __SAI_HandleTypeDef::Instance, SAI1_Block_A, SAI1_client, and SAI1_IRQn.
HAL_SAI_MspInit()
void HAL_SAI_MspInit (SAI_HandleTypeDef * hsai)
SAI1_A_Block_A GPIO Configuration PE4 ---—> SAI1_FS_A PE5 ---—> SAI1_SCK_A PE6 ---—> SAI1_SD_A
Definition at line 64 of file sai.c.
References __HAL_RCC_SAI1_CLK_ENABLE, GPIO_InitTypeDef::Alternate, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_SPEED_FREQ_LOW, GPIOE, HAL_GPIO_Init(), HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), __SAI_HandleTypeDef::Instance, GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, SAI1_Block_A, SAI1_client, SAI1_IRQn, and GPIO_InitTypeDef::Speed.