Sensorclient: STM32746G_DISCOVERY QSPI Exported Functions
STM32746G_DISCOVERY QSPI Exported Functions
STM32F7xx_HAL_Examples » BSP » STM32746G_DISCOVERY » STM32746G-Discovery QSPI
Functions
uint8_t BSP_QSPI_Init (void)
Initializes the QSPI interface.
uint8_t BSP_QSPI_DeInit (void)
De-Initializes the QSPI interface.
uint8_t BSP_QSPI_Read (uint8_t *pData, uint32_t ReadAddr, uint32_t Size)
Reads an amount of data from the QSPI memory.
uint8_t BSP_QSPI_Write (uint8_t *pData, uint32_t WriteAddr, uint32_t Size)
Writes an amount of data to the QSPI memory.
uint8_t BSP_QSPI_Erase_Block (uint32_t BlockAddress)
Erases the specified block of the QSPI memory.
uint8_t BSP_QSPI_Erase_Chip (void)
Erases the entire QSPI memory.
uint8_t BSP_QSPI_GetStatus (void)
Reads current status of the QSPI memory.
uint8_t BSP_QSPI_GetInfo (QSPI_Info *pInfo)
Return the configuration of the QSPI memory.
uint8_t BSP_QSPI_EnableMemoryMappedMode (void)
Configure the QSPI in memory-mapped mode.
void BSP_QSPI_MspInit (QSPI_HandleTypeDef *hqspi, void *Params)
QSPI MSP Initialization This function configures the hardware resources used in this example:
void BSP_QSPI_MspDeInit (QSPI_HandleTypeDef *hqspi, void *Params)
QSPI MSP De-Initialization This function frees the hardware resources used in this example:
Detailed Description
Function Documentation
BSP_QSPI_DeInit()
uint8_t BSP_QSPI_DeInit (void)
De-Initializes the QSPI interface.
Return values
QSPI memory status
Definition at line 156 of file stm32746g_discovery_qspi.c.
References BSP_QSPI_MspDeInit(), HAL_OK, NULL, QSPI_ERROR, QSPI_OK, QSPIHandle, and QUADSPI.
BSP_QSPI_EnableMemoryMappedMode()
uint8_t BSP_QSPI_EnableMemoryMappedMode (void)
Configure the QSPI in memory-mapped mode.
Return values
QSPI memory status
Definition at line 450 of file stm32746g_discovery_qspi.c.
References HAL_OK, QSPI_ERROR, QSPI_OK, and QSPIHandle.
BSP_QSPI_Erase_Block()
uint8_t BSP_QSPI_Erase_Block (uint32_t BlockAddress)
Erases the specified block of the QSPI memory.
Parameters
BlockAddress Block address to erase
Return values
QSPI memory status
Definition at line 299 of file stm32746g_discovery_qspi.c.
References HAL_OK, QSPI_AutoPollingMemReady(), QSPI_ERROR, QSPI_OK, QSPI_WriteEnable(), and QSPIHandle.
BSP_QSPI_Erase_Chip()
uint8_t BSP_QSPI_Erase_Chip (void)
Erases the entire QSPI memory.
Return values
QSPI memory status
Definition at line 341 of file stm32746g_discovery_qspi.c.
References HAL_OK, QSPI_AutoPollingMemReady(), QSPI_ERROR, QSPI_OK, QSPI_WriteEnable(), and QSPIHandle.
BSP_QSPI_GetInfo()
uint8_t BSP_QSPI_GetInfo (QSPI_Info * pInfo)
Return the configuration of the QSPI memory.
Parameters
pInfo pointer on the configuration structure
Return values
QSPI memory status
Definition at line 434 of file stm32746g_discovery_qspi.c.
References QSPI_Info::EraseSectorSize, QSPI_Info::EraseSectorsNumber, QSPI_Info::FlashSize, QSPI_Info::ProgPageSize, QSPI_Info::ProgPagesNumber, and QSPI_OK.
BSP_QSPI_GetStatus()
uint8_t BSP_QSPI_GetStatus (void)
Reads current status of the QSPI memory.
Return values
QSPI memory status
Definition at line 381 of file stm32746g_discovery_qspi.c.
References HAL_OK, QSPI_BUSY, QSPI_ERROR, QSPI_OK, QSPI_SUSPENDED, and QSPIHandle.
BSP_QSPI_Init()
uint8_t BSP_QSPI_Init (void)
Initializes the QSPI interface.
Return values
QSPI memory status
Definition at line 109 of file stm32746g_discovery_qspi.c.
References BSP_QSPI_MspInit(), HAL_OK, NULL, POSITION_VAL, QSPI_DummyCyclesCfg(), QSPI_ERROR, QSPI_NOT_SUPPORTED, QSPI_OK, QSPI_ResetMemory(), QSPIHandle, and QUADSPI.
BSP_QSPI_MspDeInit()
void BSP_QSPI_MspDeInit (QSPI_HandleTypeDef * hqspi, void * Params)
QSPI MSP De-Initialization This function frees the hardware resources used in this example:
Disable the Peripheral's clock
Revert GPIO and NVIC configuration to their default state
Return values
None
Definition at line 561 of file stm32746g_discovery_qspi.c.
References HAL_GPIO_DeInit(), HAL_NVIC_DisableIRQ(), QSPI_CLK_DISABLE, QSPI_CLK_GPIO_PORT, QSPI_CLK_PIN, QSPI_CS_GPIO_PORT, QSPI_CS_PIN, QSPI_D0_GPIO_PORT, QSPI_D0_PIN, QSPI_D1_GPIO_PORT, QSPI_D1_PIN, QSPI_D2_GPIO_PORT, QSPI_D2_PIN, QSPI_D3_GPIO_PORT, QSPI_D3_PIN, QSPI_FORCE_RESET, QSPI_RELEASE_RESET, and QUADSPI_IRQn.
Referenced by BSP_QSPI_DeInit().
BSP_QSPI_MspInit()
void BSP_QSPI_MspInit (QSPI_HandleTypeDef * hqspi, void * Params)
QSPI MSP Initialization This function configures the hardware resources used in this example:
Peripheral's clock enable
Peripheral's GPIO Configuration
NVIC configuration for QSPI interrupt
Return values
None
Definition at line 495 of file stm32746g_discovery_qspi.c.
References GPIO_InitTypeDef::Alternate, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_PULLUP, HAL_GPIO_Init(), HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, QSPI_CLK_ENABLE, QSPI_CLK_GPIO_CLK_ENABLE, QSPI_CLK_GPIO_PORT, QSPI_CLK_PIN, QSPI_CS_GPIO_CLK_ENABLE, QSPI_CS_GPIO_PORT, QSPI_CS_PIN, QSPI_D0_GPIO_CLK_ENABLE, QSPI_D0_GPIO_PORT, QSPI_D0_PIN, QSPI_D1_GPIO_CLK_ENABLE, QSPI_D1_GPIO_PORT, QSPI_D1_PIN, QSPI_D2_GPIO_CLK_ENABLE, QSPI_D2_GPIO_PORT, QSPI_D2_PIN, QSPI_D3_GPIO_CLK_ENABLE, QSPI_D3_GPIO_PORT, QSPI_D3_PIN, QSPI_FORCE_RESET, QSPI_RELEASE_RESET, QUADSPI_IRQn, and GPIO_InitTypeDef::Speed.
Referenced by BSP_QSPI_Init().
BSP_QSPI_Read()
uint8_t BSP_QSPI_Read (uint8_t * pData, uint32_t ReadAddr, uint32_t Size)
Reads an amount of data from the QSPI memory.
Parameters
pData Pointer to data to be read
ReadAddr Read start address
Size Size of data to read
Return values
QSPI memory status
Definition at line 179 of file stm32746g_discovery_qspi.c.
References HAL_OK, MODIFY_REG, QSPI_ERROR, QSPI_OK, QSPIHandle, and QUADSPI_DCR_CSHT.
BSP_QSPI_Write()
uint8_t BSP_QSPI_Write (uint8_t * pData, uint32_t WriteAddr, uint32_t Size)
Writes an amount of data to the QSPI memory.
Parameters
pData Pointer to data to be written
WriteAddr Write start address
Size Size of data to write
Return values
QSPI memory status
Definition at line 225 of file stm32746g_discovery_qspi.c.
References HAL_OK, QSPI_AutoPollingMemReady(), QSPI_ERROR, QSPI_OK, QSPI_WriteEnable(), and QSPIHandle.