Sensorclient: STM32746G_DISCOVERY_CAMERA Exported Functions
STM32746G_DISCOVERY_CAMERA Exported Functions
STM32F7xx_HAL_Examples » BSP » STM32746G_DISCOVERY » STM32746G_DISCOVERY_CAMERA
Functions
uint8_t BSP_CAMERA_Init (uint32_t Resolution)
Initializes the camera.
uint8_t BSP_CAMERA_DeInit (void)
DeInitializes the camera.
void BSP_CAMERA_ContinuousStart (uint8_t *buff)
Starts the camera capture in continuous mode.
void BSP_CAMERA_SnapshotStart (uint8_t *buff)
Starts the camera capture in snapshot mode.
void BSP_CAMERA_Suspend (void)
Suspend the CAMERA capture.
void BSP_CAMERA_Resume (void)
Resume the CAMERA capture.
uint8_t BSP_CAMERA_Stop (void)
Stop the CAMERA capture.
void BSP_CAMERA_PwrUp (void)
CANERA power up.
void BSP_CAMERA_PwrDown (void)
CAMERA power down.
void BSP_CAMERA_ContrastBrightnessConfig (uint32_t contrast_level, uint32_t brightness_level)
Configures the camera contrast and brightness.
void BSP_CAMERA_BlackWhiteConfig (uint32_t Mode)
Configures the camera white balance.
void BSP_CAMERA_ColorEffectConfig (uint32_t Effect)
Configures the camera color effect.
__weak void BSP_CAMERA_MspInit (DCMI_HandleTypeDef *hdcmi, void *Params)
Initializes the DCMI MSP.
__weak void BSP_CAMERA_MspDeInit (DCMI_HandleTypeDef *hdcmi, void *Params)
DeInitializes the DCMI MSP.
void HAL_DCMI_LineEventCallback (DCMI_HandleTypeDef *hdcmi)
Line event callback.
__weak void BSP_CAMERA_LineEventCallback (void)
Line Event callback.
void HAL_DCMI_VsyncEventCallback (DCMI_HandleTypeDef *hdcmi)
VSYNC event callback.
__weak void BSP_CAMERA_VsyncEventCallback (void)
VSYNC Event callback.
void HAL_DCMI_FrameEventCallback (DCMI_HandleTypeDef *hdcmi)
Frame event callback.
__weak void BSP_CAMERA_FrameEventCallback (void)
Frame Event callback.
void HAL_DCMI_ErrorCallback (DCMI_HandleTypeDef *hdcmi)
Error callback.
__weak void BSP_CAMERA_ErrorCallback (void)
Error callback.
static uint32_t GetSize (uint32_t resolution)
Get the capture size in pixels unit.
Detailed Description
Function Documentation
BSP_CAMERA_BlackWhiteConfig()
void BSP_CAMERA_BlackWhiteConfig (uint32_t Mode)
Configures the camera white balance.
Parameters
Mode black_white mode This parameter can be one of the following values:
CAMERA_BLACK_WHITE_BW
CAMERA_BLACK_WHITE_NEGATIVE
CAMERA_BLACK_WHITE_BW_NEGATIVE
CAMERA_BLACK_WHITE_NORMAL
Return values
None
Definition at line 356 of file stm32746g_discovery_camera.c.
References camera_drv, CameraHwAddress, and NULL.
BSP_CAMERA_ColorEffectConfig()
void BSP_CAMERA_ColorEffectConfig (uint32_t Effect)
Configures the camera color effect.
Parameters
Effect Color effect This parameter can be one of the following values:
CAMERA_COLOR_EFFECT_ANTIQUE
CAMERA_COLOR_EFFECT_BLUE
CAMERA_COLOR_EFFECT_GREEN
CAMERA_COLOR_EFFECT_RED
Return values
None
Definition at line 374 of file stm32746g_discovery_camera.c.
References camera_drv, CameraHwAddress, and NULL.
BSP_CAMERA_ContinuousStart()
void BSP_CAMERA_ContinuousStart (uint8_t * buff)
Starts the camera capture in continuous mode.
Parameters
buff pointer to the camera output buffer
Return values
None
Definition at line 216 of file stm32746g_discovery_camera.c.
References CameraCurrentResolution, GetSize(), and hDcmiHandler.
BSP_CAMERA_ContrastBrightnessConfig()
void BSP_CAMERA_ContrastBrightnessConfig (uint32_t contrast_level, uint32_t brightness_level)
Configures the camera contrast and brightness.
Parameters
contrast_level Contrast level This parameter can be one of the following values:
CAMERA_CONTRAST_LEVEL4: for contrast +2
CAMERA_CONTRAST_LEVEL3: for contrast +1
CAMERA_CONTRAST_LEVEL2: for contrast 0
CAMERA_CONTRAST_LEVEL1: for contrast -1
CAMERA_CONTRAST_LEVEL0: for contrast -2
brightness_level Contrast level This parameter can be one of the following values:
CAMERA_BRIGHTNESS_LEVEL4: for brightness +2
CAMERA_BRIGHTNESS_LEVEL3: for brightness +1
CAMERA_BRIGHTNESS_LEVEL2: for brightness 0
CAMERA_BRIGHTNESS_LEVEL1: for brightness -1
CAMERA_BRIGHTNESS_LEVEL0: for brightness -2
Return values
None
Definition at line 338 of file stm32746g_discovery_camera.c.
References camera_drv, CameraHwAddress, and NULL.
BSP_CAMERA_DeInit()
uint8_t BSP_CAMERA_DeInit (void)
DeInitializes the camera.
Return values
Camera status
Definition at line 202 of file stm32746g_discovery_camera.c.
References BSP_CAMERA_MspDeInit(), CAMERA_OK, DCMI, hDcmiHandler, and NULL.
BSP_CAMERA_ErrorCallback()
void BSP_CAMERA_ErrorCallback (void)
Error callback.
Return values
None
Definition at line 621 of file stm32746g_discovery_camera.c.
Referenced by HAL_DCMI_ErrorCallback().
BSP_CAMERA_FrameEventCallback()
void BSP_CAMERA_FrameEventCallback (void)
Frame Event callback.
Return values
None
Definition at line 600 of file stm32746g_discovery_camera.c.
Referenced by HAL_DCMI_FrameEventCallback().
BSP_CAMERA_Init()
uint8_t BSP_CAMERA_Init (uint32_t Resolution)
Initializes the camera.
Parameters
Resolution : camera sensor requested resolution (x, y) : standard resolution naming QQVGA, QVGA, VGA ...
Return values
Camera status
Definition at line 133 of file stm32746g_discovery_camera.c.
References BSP_CAMERA_MspInit(), BSP_CAMERA_PwrUp(), CAMERA_480x272_RES_X, CAMERA_480x272_RES_Y, camera_drv, CAMERA_ERROR, CAMERA_I2C_ADDRESS, CAMERA_NOT_SUPPORTED, CAMERA_OK, CAMERA_VGA_RES_X, CAMERA_VGA_RES_Y, CameraCurrentResolution, CameraHwAddress, DCMI, HAL_DCMI_ConfigCROP, HAL_DCMI_DisableCROP, HAL_DCMI_EnableCROP, hDcmiHandler, and NULL.
BSP_CAMERA_LineEventCallback()
void BSP_CAMERA_LineEventCallback (void)
Line Event callback.
Return values
None
Definition at line 558 of file stm32746g_discovery_camera.c.
Referenced by HAL_DCMI_LineEventCallback().
BSP_CAMERA_MspDeInit()
void BSP_CAMERA_MspDeInit (DCMI_HandleTypeDef * hdcmi, void * Params)
DeInitializes the DCMI MSP.
Parameters
hdcmi HDMI handle
Params
Return values
None
Definition at line 526 of file stm32746g_discovery_camera.c.
References DCMI_IRQn, DMA2_Stream1_IRQn, HAL_DMA_DeInit(), and HAL_NVIC_DisableIRQ().
Referenced by BSP_CAMERA_DeInit().
BSP_CAMERA_MspInit()
void BSP_CAMERA_MspInit (DCMI_HandleTypeDef * hdcmi, void * Params)
Initializes the DCMI MSP.
Parameters
hdcmi HDMI handle
Params
Return values
None
Definition at line 429 of file stm32746g_discovery_camera.c.
References __HAL_LINKDMA, __HAL_RCC_DMA2_CLK_ENABLE, __HAL_RCC_GPIOA_CLK_ENABLE, __HAL_RCC_GPIOD_CLK_ENABLE, __HAL_RCC_GPIOE_CLK_ENABLE, __HAL_RCC_GPIOG_CLK_ENABLE, __HAL_RCC_GPIOH_CLK_ENABLE, GPIO_InitTypeDef::Alternate, DMA_InitTypeDef::Channel, DCMI_IRQn, DMA_InitTypeDef::Direction, DMA2_Stream1, DMA2_Stream1_IRQn, DMA_CHANNEL_1, DMA_CIRCULAR, DMA_FIFO_THRESHOLD_FULL, DMA_FIFOMODE_DISABLE, DMA_MBURST_SINGLE, DMA_MDATAALIGN_WORD, DMA_MINC_ENABLE, DMA_PBURST_SINGLE, DMA_PDATAALIGN_WORD, DMA_PERIPH_TO_MEMORY, DMA_PINC_DISABLE, DMA_PRIORITY_HIGH, DMA_InitTypeDef::FIFOMode, DMA_InitTypeDef::FIFOThreshold, GPIO_MODE_AF_PP, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_14, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_9, GPIO_PULLUP, GPIOA, GPIOD, GPIOE, GPIOG, GPIOH, HAL_DMA_Init(), HAL_GPIO_Init(), HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), __DMA_HandleTypeDef::Init, __DMA_HandleTypeDef::Instance, DMA_InitTypeDef::MemBurst, DMA_InitTypeDef::MemDataAlignment, DMA_InitTypeDef::MemInc, GPIO_InitTypeDef::Mode, DMA_InitTypeDef::Mode, DMA_InitTypeDef::PeriphBurst, DMA_InitTypeDef::PeriphDataAlignment, DMA_InitTypeDef::PeriphInc, GPIO_InitTypeDef::Pin, DMA_InitTypeDef::Priority, GPIO_InitTypeDef::Pull, and GPIO_InitTypeDef::Speed.
Referenced by BSP_CAMERA_Init().
BSP_CAMERA_PwrDown()
void BSP_CAMERA_PwrDown (void)
CAMERA power down.
Return values
None
Definition at line 301 of file stm32746g_discovery_camera.c.
References __HAL_RCC_GPIOH_CLK_ENABLE, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_PIN_13, GPIO_PIN_SET, GPIOH, HAL_GPIO_Init(), HAL_GPIO_WritePin(), GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, and GPIO_InitTypeDef::Speed.
Referenced by BSP_CAMERA_Stop().
BSP_CAMERA_PwrUp()
void BSP_CAMERA_PwrUp (void)
CANERA power up.
Return values
None
Definition at line 276 of file stm32746g_discovery_camera.c.
References __HAL_RCC_GPIOH_CLK_ENABLE, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_PIN_13, GPIO_PIN_RESET, GPIOH, HAL_Delay(), HAL_GPIO_Init(), HAL_GPIO_WritePin(), GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, and GPIO_InitTypeDef::Speed.
Referenced by BSP_CAMERA_Init().
BSP_CAMERA_Resume()
void BSP_CAMERA_Resume (void)
Resume the CAMERA capture.
Return values
None
Definition at line 247 of file stm32746g_discovery_camera.c.
References hDcmiHandler.
BSP_CAMERA_SnapshotStart()
void BSP_CAMERA_SnapshotStart (uint8_t * buff)
Starts the camera capture in snapshot mode.
Parameters
buff pointer to the camera output buffer
Return values
None
Definition at line 227 of file stm32746g_discovery_camera.c.
References CameraCurrentResolution, GetSize(), and hDcmiHandler.
BSP_CAMERA_Stop()
uint8_t BSP_CAMERA_Stop (void)
Stop the CAMERA capture.
Return values
Camera status
Definition at line 257 of file stm32746g_discovery_camera.c.
References BSP_CAMERA_PwrDown(), CAMERA_ERROR, CAMERA_OK, HAL_OK, and hDcmiHandler.
BSP_CAMERA_Suspend()
void BSP_CAMERA_Suspend (void)
Suspend the CAMERA capture.
Return values
None
Definition at line 237 of file stm32746g_discovery_camera.c.
References hDcmiHandler.
BSP_CAMERA_VsyncEventCallback()
void BSP_CAMERA_VsyncEventCallback (void)
VSYNC Event callback.
Return values
None
Definition at line 579 of file stm32746g_discovery_camera.c.
Referenced by HAL_DCMI_VsyncEventCallback().
GetSize()
static uint32_t GetSize (uint32_t resolution) static
Get the capture size in pixels unit.
Parameters
resolution the current resolution.
Return values
capture size in pixels unit.
Definition at line 387 of file stm32746g_discovery_camera.c.
Referenced by BSP_CAMERA_ContinuousStart(), and BSP_CAMERA_SnapshotStart().
HAL_DCMI_ErrorCallback()
void HAL_DCMI_ErrorCallback (DCMI_HandleTypeDef * hdcmi)
Error callback.
Parameters
hdcmi pointer to the DCMI handle
Return values
None
Definition at line 612 of file stm32746g_discovery_camera.c.
References BSP_CAMERA_ErrorCallback().
HAL_DCMI_FrameEventCallback()
void HAL_DCMI_FrameEventCallback (DCMI_HandleTypeDef * hdcmi)
Frame event callback.
Parameters
hdcmi pointer to the DCMI handle
Return values
None
Definition at line 591 of file stm32746g_discovery_camera.c.
References BSP_CAMERA_FrameEventCallback().
HAL_DCMI_LineEventCallback()
void HAL_DCMI_LineEventCallback (DCMI_HandleTypeDef * hdcmi)
Line event callback.
Parameters
hdcmi pointer to the DCMI handle
Return values
None
Definition at line 549 of file stm32746g_discovery_camera.c.
References BSP_CAMERA_LineEventCallback().
HAL_DCMI_VsyncEventCallback()
void HAL_DCMI_VsyncEventCallback (DCMI_HandleTypeDef * hdcmi)
VSYNC event callback.
Parameters
hdcmi pointer to the DCMI handle
Return values
None
Definition at line 570 of file stm32746g_discovery_camera.c.
References BSP_CAMERA_VsyncEventCallback().