Sensorclient: STM32746G_DISCOVERY AUDIO Out Exported Functions
STM32746G_DISCOVERY AUDIO Out Exported Functions
STM32F7xx_HAL_Examples » BSP » STM32746G_DISCOVERY » STM32746G_DISCOVERY AUDIO
Functions
uint8_t BSP_AUDIO_OUT_Init (uint16_t OutputDevice, uint8_t Volume, uint32_t AudioFreq)
Configures the audio peripherals.
uint8_t BSP_AUDIO_OUT_Play (uint16_t *pBuffer, uint32_t Size)
Starts playing audio stream from a data buffer for a determined size.
void BSP_AUDIO_OUT_ChangeBuffer (uint16_t *pData, uint16_t Size)
Sends n-Bytes on the SAI interface.
uint8_t BSP_AUDIO_OUT_Pause (void)
This function Pauses the audio file stream. In case of using DMA, the DMA Pause feature is used.
uint8_t BSP_AUDIO_OUT_Resume (void)
This function Resumes the audio file stream.
uint8_t BSP_AUDIO_OUT_Stop (uint32_t Option)
Stops audio playing and Power down the Audio Codec.
uint8_t BSP_AUDIO_OUT_SetVolume (uint8_t Volume)
Controls the current audio volume level.
uint8_t BSP_AUDIO_OUT_SetMute (uint32_t Cmd)
Enables or disables the MUTE mode by software.
uint8_t BSP_AUDIO_OUT_SetOutputMode (uint8_t Output)
Switch dynamically (while audio file is played) the output target (speaker or headphone).
void BSP_AUDIO_OUT_SetFrequency (uint32_t AudioFreq)
Updates the audio frequency.
void BSP_AUDIO_OUT_SetAudioFrameSlot (uint32_t AudioFrameSlot)
Updates the Audio frame slot configuration.
void BSP_AUDIO_OUT_DeInit (void)
Deinit the audio peripherals.
void HAL_SAI_TxCpltCallback (SAI_HandleTypeDef *hsai)
Tx Transfer completed callbacks.
void HAL_SAI_TxHalfCpltCallback (SAI_HandleTypeDef *hsai)
Tx Half Transfer completed callbacks.
void HAL_SAI_ErrorCallback (SAI_HandleTypeDef *hsai)
SAI error callbacks.
__weak void BSP_AUDIO_OUT_TransferComplete_CallBack (void)
Manages the DMA full Transfer complete event.
__weak void BSP_AUDIO_OUT_HalfTransfer_CallBack (void)
Manages the DMA Half Transfer complete event.
__weak void BSP_AUDIO_OUT_Error_CallBack (void)
Manages the DMA FIFO error event.
__weak void BSP_AUDIO_OUT_MspInit (SAI_HandleTypeDef *hsai, void *Params)
Initializes BSP_AUDIO_OUT MSP.
__weak void BSP_AUDIO_OUT_MspDeInit (SAI_HandleTypeDef *hsai, void *Params)
Deinitializes SAI MSP.
__weak void BSP_AUDIO_OUT_ClockConfig (SAI_HandleTypeDef *hsai, uint32_t AudioFreq, void *Params)
Clock Config.
static void SAIx_Out_Init (uint32_t AudioFreq)
Initializes the output Audio Codec audio interface (SAI).
static void SAIx_Out_DeInit (void)
Deinitializes the output Audio Codec audio interface (SAI).
Detailed Description
Function Documentation
BSP_AUDIO_OUT_ChangeBuffer()
void BSP_AUDIO_OUT_ChangeBuffer (uint16_t * pData, uint16_t Size)
Sends n-Bytes on the SAI interface.
Parameters
pData pointer on data address
Size number of data to be written
Return values
None
Definition at line 239 of file stm32746g_discovery_audio.c.
References HAL_SAI_Transmit_DMA(), and haudio_out_sai.
BSP_AUDIO_OUT_ClockConfig()
void BSP_AUDIO_OUT_ClockConfig (SAI_HandleTypeDef * hsai, uint32_t AudioFreq, void * Params)
Clock Config.
Parameters
hsai might be required to set audio peripheral predivider if any.
AudioFreq Audio frequency used to play the audio stream.
Params
Note
This API is called by BSP_AUDIO_OUT_Init() and BSP_AUDIO_OUT_SetFrequency() Being __weak it can be overwritten by the application
Return values
None
Definition at line 650 of file stm32746g_discovery_audio.c.
References HAL_RCCEx_GetPeriphCLKConfig(), HAL_RCCEx_PeriphCLKConfig(), RCC_PeriphCLKInitTypeDef::PeriphClockSelection, RCC_PeriphCLKInitTypeDef::PLLI2S, RCC_PeriphCLKInitTypeDef::PLLI2SDivQ, RCC_PLLI2SInitTypeDef::PLLI2SN, RCC_PLLI2SInitTypeDef::PLLI2SQ, RCC_PERIPHCLK_SAI2, RCC_SAI2CLKSOURCE_PLLI2S, and RCC_PeriphCLKInitTypeDef::Sai2ClockSelection.
Referenced by BSP_AUDIO_OUT_Init(), and BSP_AUDIO_OUT_SetFrequency().
BSP_AUDIO_OUT_DeInit()
void BSP_AUDIO_OUT_DeInit (void)
Deinit the audio peripherals.
Return values
None
Definition at line 436 of file stm32746g_discovery_audio.c.
References BSP_AUDIO_OUT_MspDeInit(), haudio_out_sai, NULL, and SAIx_Out_DeInit().
BSP_AUDIO_OUT_Error_CallBack()
void BSP_AUDIO_OUT_Error_CallBack (void)
Manages the DMA FIFO error event.
Return values
None
Definition at line 512 of file stm32746g_discovery_audio.c.
Referenced by HAL_SAI_ErrorCallback().
BSP_AUDIO_OUT_HalfTransfer_CallBack()
void BSP_AUDIO_OUT_HalfTransfer_CallBack (void)
Manages the DMA Half Transfer complete event.
Return values
None
Definition at line 504 of file stm32746g_discovery_audio.c.
Referenced by HAL_SAI_TxHalfCpltCallback().
BSP_AUDIO_OUT_Init()
uint8_t BSP_AUDIO_OUT_Init (uint16_t OutputDevice, uint8_t Volume, uint32_t AudioFreq)
Configures the audio peripherals.
Parameters
OutputDevice OUTPUT_DEVICE_SPEAKER, OUTPUT_DEVICE_HEADPHONE, or OUTPUT_DEVICE_BOTH.
Volume Initial volume level (from 0 (Mute) to 100 (Max))
AudioFreq Audio frequency used to play the audio stream.
Note
The I2S PLL input clock must be done in the user application.
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 164 of file stm32746g_discovery_audio.c.
References audio_drv, AUDIO_ERROR, AUDIO_I2C_ADDRESS, AUDIO_OK, AUDIO_OUT_SAIx, BSP_AUDIO_OUT_ClockConfig(), BSP_AUDIO_OUT_MspInit(), HAL_SAI_GetState(), HAL_SAI_STATE_RESET, haudio_out_sai, __SAI_HandleTypeDef::Instance, NULL, SAIx_Out_DeInit(), and SAIx_Out_Init().
BSP_AUDIO_OUT_MspDeInit()
void BSP_AUDIO_OUT_MspDeInit (SAI_HandleTypeDef * hsai, void * Params)
Deinitializes SAI MSP.
Parameters
hsai SAI handle
Params
Return values
None
Definition at line 605 of file stm32746g_discovery_audio.c.
References __HAL_SAI_DISABLE, AUDIO_OUT_SAIx, AUDIO_OUT_SAIx_CLK_DISABLE, AUDIO_OUT_SAIx_DMAx_IRQ, AUDIO_OUT_SAIx_FS_GPIO_PORT, AUDIO_OUT_SAIx_FS_PIN, AUDIO_OUT_SAIx_MCLK_GPIO_PORT, AUDIO_OUT_SAIx_MCLK_PIN, AUDIO_OUT_SAIx_SCK_PIN, AUDIO_OUT_SAIx_SCK_SD_GPIO_PORT, AUDIO_OUT_SAIx_SD_PIN, HAL_DMA_DeInit(), HAL_GPIO_DeInit(), HAL_NVIC_DisableIRQ(), __SAI_HandleTypeDef::hdmatx, __SAI_HandleTypeDef::Instance, and GPIO_InitTypeDef::Pin.
Referenced by BSP_AUDIO_OUT_DeInit().
BSP_AUDIO_OUT_MspInit()
void BSP_AUDIO_OUT_MspInit (SAI_HandleTypeDef * hsai, void * Params)
Initializes BSP_AUDIO_OUT MSP.
Parameters
hsai SAI handle
Params
Return values
None
Definition at line 522 of file stm32746g_discovery_audio.c.
References __HAL_LINKDMA, GPIO_InitTypeDef::Alternate, AUDIO_OUT_IRQ_PREPRIO, AUDIO_OUT_SAIx, AUDIO_OUT_SAIx_CLK_ENABLE, AUDIO_OUT_SAIx_DMAx_CHANNEL, AUDIO_OUT_SAIx_DMAx_CLK_ENABLE, AUDIO_OUT_SAIx_DMAx_IRQ, AUDIO_OUT_SAIx_DMAx_MEM_DATA_SIZE, AUDIO_OUT_SAIx_DMAx_PERIPH_DATA_SIZE, AUDIO_OUT_SAIx_DMAx_STREAM, AUDIO_OUT_SAIx_FS_ENABLE, AUDIO_OUT_SAIx_FS_GPIO_PORT, AUDIO_OUT_SAIx_FS_PIN, AUDIO_OUT_SAIx_FS_SD_MCLK_AF, AUDIO_OUT_SAIx_MCLK_ENABLE, AUDIO_OUT_SAIx_MCLK_GPIO_PORT, AUDIO_OUT_SAIx_MCLK_PIN, AUDIO_OUT_SAIx_SCK_AF, AUDIO_OUT_SAIx_SCK_PIN, AUDIO_OUT_SAIx_SCK_SD_ENABLE, AUDIO_OUT_SAIx_SCK_SD_GPIO_PORT, AUDIO_OUT_SAIx_SD_PIN, DMA_InitTypeDef::Channel, DMA_InitTypeDef::Direction, DMA_CIRCULAR, DMA_FIFO_THRESHOLD_FULL, DMA_FIFOMODE_ENABLE, DMA_MBURST_SINGLE, DMA_MEMORY_TO_PERIPH, DMA_MINC_ENABLE, DMA_PBURST_SINGLE, DMA_PINC_DISABLE, DMA_PRIORITY_HIGH, DMA_InitTypeDef::FIFOMode, DMA_InitTypeDef::FIFOThreshold, GPIO_MODE_AF_PP, GPIO_NOPULL, HAL_DMA_DeInit(), HAL_DMA_Init(), HAL_GPIO_Init(), HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), __DMA_HandleTypeDef::Init, __DMA_HandleTypeDef::Instance, __SAI_HandleTypeDef::Instance, DMA_InitTypeDef::MemBurst, DMA_InitTypeDef::MemDataAlignment, DMA_InitTypeDef::MemInc, GPIO_InitTypeDef::Mode, DMA_InitTypeDef::Mode, DMA_InitTypeDef::PeriphBurst, DMA_InitTypeDef::PeriphDataAlignment, DMA_InitTypeDef::PeriphInc, GPIO_InitTypeDef::Pin, DMA_InitTypeDef::Priority, GPIO_InitTypeDef::Pull, and GPIO_InitTypeDef::Speed.
Referenced by BSP_AUDIO_OUT_Init().
BSP_AUDIO_OUT_Pause()
uint8_t BSP_AUDIO_OUT_Pause (void)
This function Pauses the audio file stream. In case of using DMA, the DMA Pause feature is used.
Note
When calling BSP_AUDIO_OUT_Pause() function for pause, only BSP_AUDIO_OUT_Resume() function should be called for resume (use of BSP_AUDIO_OUT_Play() function for resume could lead to unexpected behaviour).
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 252 of file stm32746g_discovery_audio.c.
References audio_drv, AUDIO_ERROR, AUDIO_I2C_ADDRESS, AUDIO_OK, HAL_SAI_DMAPause(), and haudio_out_sai.
BSP_AUDIO_OUT_Play()
uint8_t BSP_AUDIO_OUT_Play (uint16_t * pBuffer, uint32_t Size)
Starts playing audio stream from a data buffer for a determined size.
Parameters
pBuffer Pointer to the buffer
Size Number of audio data in BYTES unit. In memory, first element is for left channel, second element is for right channel
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 217 of file stm32746g_discovery_audio.c.
References audio_drv, AUDIO_ERROR, AUDIO_I2C_ADDRESS, AUDIO_OK, AUDIODATA_SIZE, DMA_MAX, HAL_SAI_Transmit_DMA(), and haudio_out_sai.
BSP_AUDIO_OUT_Resume()
uint8_t BSP_AUDIO_OUT_Resume (void)
This function Resumes the audio file stream.
Note
When calling BSP_AUDIO_OUT_Pause() function for pause, only BSP_AUDIO_OUT_Resume() function should be called for resume (use of BSP_AUDIO_OUT_Play() function for resume could lead to unexpected behaviour).
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 276 of file stm32746g_discovery_audio.c.
References audio_drv, AUDIO_ERROR, AUDIO_I2C_ADDRESS, AUDIO_OK, HAL_SAI_DMAResume(), and haudio_out_sai.
BSP_AUDIO_OUT_SetAudioFrameSlot()
void BSP_AUDIO_OUT_SetAudioFrameSlot (uint32_t AudioFrameSlot)
Updates the Audio frame slot configuration.
Parameters
AudioFrameSlot specifies the audio Frame slot This parameter can be one of the following values
CODEC_AUDIOFRAME_SLOT_0123
CODEC_AUDIOFRAME_SLOT_02
CODEC_AUDIOFRAME_SLOT_13
Note
This API should be called after the BSP_AUDIO_OUT_Init() to adjust the audio frame slot.
Return values
None
Definition at line 419 of file stm32746g_discovery_audio.c.
References __HAL_SAI_DISABLE, __HAL_SAI_ENABLE, HAL_SAI_Init(), haudio_out_sai, SAI_SlotInitTypeDef::SlotActive, and __SAI_HandleTypeDef::SlotInit.
BSP_AUDIO_OUT_SetFrequency()
void BSP_AUDIO_OUT_SetFrequency (uint32_t AudioFreq)
Updates the audio frequency.
Parameters
AudioFreq Audio frequency used to play the audio stream.
Note
This API should be called after the BSP_AUDIO_OUT_Init() to adjust the audio frequency.
Return values
None
Definition at line 392 of file stm32746g_discovery_audio.c.
References __HAL_SAI_DISABLE, __HAL_SAI_ENABLE, SAI_InitTypeDef::AudioFrequency, BSP_AUDIO_OUT_ClockConfig(), HAL_SAI_Init(), haudio_out_sai, __SAI_HandleTypeDef::Init, and NULL.
BSP_AUDIO_OUT_SetMute()
uint8_t BSP_AUDIO_OUT_SetMute (uint32_t Cmd)
Enables or disables the MUTE mode by software.
Parameters
Cmd Could be AUDIO_MUTE_ON to mute sound or AUDIO_MUTE_OFF to unmute the codec and restore previous volume level.
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 350 of file stm32746g_discovery_audio.c.
References audio_drv, AUDIO_ERROR, AUDIO_I2C_ADDRESS, and AUDIO_OK.
BSP_AUDIO_OUT_SetOutputMode()
uint8_t BSP_AUDIO_OUT_SetOutputMode (uint8_t Output)
Switch dynamically (while audio file is played) the output target (speaker or headphone).
Parameters
Output The audio output target: OUTPUT_DEVICE_SPEAKER, OUTPUT_DEVICE_HEADPHONE or OUTPUT_DEVICE_BOTH
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 371 of file stm32746g_discovery_audio.c.
References audio_drv, AUDIO_ERROR, AUDIO_I2C_ADDRESS, and AUDIO_OK.
BSP_AUDIO_OUT_SetVolume()
uint8_t BSP_AUDIO_OUT_SetVolume (uint8_t Volume)
Controls the current audio volume level.
Parameters
Volume Volume level to be set in percentage from 0% to 100% (0 for Mute and 100 for Max volume level).
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 330 of file stm32746g_discovery_audio.c.
References audio_drv, AUDIO_ERROR, AUDIO_I2C_ADDRESS, and AUDIO_OK.
BSP_AUDIO_OUT_Stop()
uint8_t BSP_AUDIO_OUT_Stop (uint32_t Option)
Stops audio playing and Power down the Audio Codec.
Parameters
Option could be one of the following parameters
CODEC_PDWN_SW: for software power off (by writing registers). Then no need to reconfigure the Codec after power on.
CODEC_PDWN_HW: completely shut down the codec (physically). Then need to reconfigure the Codec after power on.
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 302 of file stm32746g_discovery_audio.c.
References audio_drv, AUDIO_ERROR, AUDIO_I2C_ADDRESS, AUDIO_OK, HAL_Delay(), HAL_SAI_DMAStop(), and haudio_out_sai.
BSP_AUDIO_OUT_TransferComplete_CallBack()
void BSP_AUDIO_OUT_TransferComplete_CallBack (void)
Manages the DMA full Transfer complete event.
Return values
None
Definition at line 496 of file stm32746g_discovery_audio.c.
Referenced by HAL_SAI_TxCpltCallback().
HAL_SAI_ErrorCallback()
void HAL_SAI_ErrorCallback (SAI_HandleTypeDef * hsai)
SAI error callbacks.
Parameters
hsai SAI handle
Return values
None
Definition at line 472 of file stm32746g_discovery_audio.c.
References BSP_AUDIO_IN_Error_CallBack(), BSP_AUDIO_OUT_Error_CallBack(), HAL_SAI_GetState(), HAL_SAI_STATE_BUSY, HAL_SAI_STATE_BUSY_RX, HAL_SAI_STATE_BUSY_TX, haudio_in_sai, and haudio_out_sai.
HAL_SAI_TxCpltCallback()
void HAL_SAI_TxCpltCallback (SAI_HandleTypeDef * hsai)
Tx Transfer completed callbacks.
Parameters
hsai SAI handle
Return values
None
Definition at line 448 of file stm32746g_discovery_audio.c.
References BSP_AUDIO_OUT_TransferComplete_CallBack().
HAL_SAI_TxHalfCpltCallback()
void HAL_SAI_TxHalfCpltCallback (SAI_HandleTypeDef * hsai)
Tx Half Transfer completed callbacks.
Parameters
hsai SAI handle
Return values
None
Definition at line 460 of file stm32746g_discovery_audio.c.
References BSP_AUDIO_OUT_HalfTransfer_CallBack().
SAIx_Out_DeInit()
static void SAIx_Out_DeInit (void) static
Deinitializes the output Audio Codec audio interface (SAI).
Return values
None
Definition at line 754 of file stm32746g_discovery_audio.c.
Referenced by BSP_AUDIO_OUT_DeInit(), and BSP_AUDIO_OUT_Init().
SAIx_Out_Init()
static void SAIx_Out_Init (uint32_t AudioFreq) static
Initializes the output Audio Codec audio interface (SAI).
Parameters
AudioFreq Audio frequency to be configured for the SAI peripheral.
Note
The default SlotActive configuration is set to CODEC_AUDIOFRAME_SLOT_0123 and user can update this configuration using
Return values
None
Definition at line 698 of file stm32746g_discovery_audio.c.
Referenced by BSP_AUDIO_OUT_Init().