var group__SAI__Exported__Constants =
[
    [ "SAI Error Code", "group__SAI__Error__Code.html", "group__SAI__Error__Code" ],
    [ "SAI External synchronisation", "group__SAI__Block__SyncExt.html", "group__SAI__Block__SyncExt" ],
    [ "SAI Supported protocol", "group__SAI__Protocol.html", "group__SAI__Protocol" ],
    [ "SAI protocol data size", "group__SAI__Protocol__DataSize.html", "group__SAI__Protocol__DataSize" ],
    [ "SAI Audio Frequency", "group__SAI__Audio__Frequency.html", "group__SAI__Audio__Frequency" ],
    [ "SAI Block Mode", "group__SAI__Block__Mode.html", "group__SAI__Block__Mode" ],
    [ "SAI Block Protocol", "group__SAI__Block__Protocol.html", "group__SAI__Block__Protocol" ],
    [ "SAI Block Data Size", "group__SAI__Block__Data__Size.html", "group__SAI__Block__Data__Size" ],
    [ "SAI Block MSB LSB transmission", "group__SAI__Block__MSB__LSB__transmission.html", "group__SAI__Block__MSB__LSB__transmission" ],
    [ "SAI Block Clock Strobing", "group__SAI__Block__Clock__Strobing.html", "group__SAI__Block__Clock__Strobing" ],
    [ "SAI Block Synchronization", "group__SAI__Block__Synchronization.html", "group__SAI__Block__Synchronization" ],
    [ "SAI Block Output Drive", "group__SAI__Block__Output__Drive.html", "group__SAI__Block__Output__Drive" ],
    [ "SAI Block NoDivider", "group__SAI__Block__NoDivider.html", "group__SAI__Block__NoDivider" ],
    [ "SAI Block FS Definition", "group__SAI__Block__FS__Definition.html", "group__SAI__Block__FS__Definition" ],
    [ "SAI Block FS Polarity", "group__SAI__Block__FS__Polarity.html", "group__SAI__Block__FS__Polarity" ],
    [ "SAI Block FS Offset", "group__SAI__Block__FS__Offset.html", "group__SAI__Block__FS__Offset" ],
    [ "SAI Block Slot Size", "group__SAI__Block__Slot__Size.html", "group__SAI__Block__Slot__Size" ],
    [ "SAI Block Slot Active", "group__SAI__Block__Slot__Active.html", "group__SAI__Block__Slot__Active" ],
    [ "SAI Mono Stereo Mode", "group__SAI__Mono__Stereo__Mode.html", "group__SAI__Mono__Stereo__Mode" ],
    [ "SAI TRIState Management", "group__SAI__TRIState__Management.html", "group__SAI__TRIState__Management" ],
    [ "SAI Block Fifo Threshold", "group__SAI__Block__Fifo__Threshold.html", "group__SAI__Block__Fifo__Threshold" ],
    [ "SAI Block Companding Mode", "group__SAI__Block__Companding__Mode.html", "group__SAI__Block__Companding__Mode" ],
    [ "SAI Block Mute Value", "group__SAI__Block__Mute__Value.html", "group__SAI__Block__Mute__Value" ],
    [ "SAI Block Interrupts Definition", "group__SAI__Block__Interrupts__Definition.html", "group__SAI__Block__Interrupts__Definition" ],
    [ "SAI Block Flags Definition", "group__SAI__Block__Flags__Definition.html", "group__SAI__Block__Flags__Definition" ],
    [ "SAI Block Fifo Status Level", "group__SAI__Block__Fifo__Status__Level.html", "group__SAI__Block__Fifo__Status__Level" ]
];