var group__RCC__Exported__Macros =
[
    [ "AHB1 Peripheral Clock Enable Disable", "group__RCC__AHB1__Clock__Enable__Disable.html", "group__RCC__AHB1__Clock__Enable__Disable" ],
    [ "APB1 Peripheral Clock Enable Disable", "group__RCC__APB1__Clock__Enable__Disable.html", "group__RCC__APB1__Clock__Enable__Disable" ],
    [ "APB2 Peripheral Clock Enable Disable", "group__RCC__APB2__Clock__Enable__Disable.html", "group__RCC__APB2__Clock__Enable__Disable" ],
    [ "AHB1 Peripheral Clock Enable Disable Status", "group__RCC__AHB1__Peripheral__Clock__Enable__Disable__Status.html", "group__RCC__AHB1__Peripheral__Clock__Enable__Disable__Status" ],
    [ "APB1 Peripheral Clock Enable Disable  Status", "group__RCC__APB1__Clock__Enable__Disable__Status.html", "group__RCC__APB1__Clock__Enable__Disable__Status" ],
    [ "APB2 Peripheral Clock Enable Disable Status", "group__RCC__APB2__Clock__Enable__Disable__Status.html", "group__RCC__APB2__Clock__Enable__Disable__Status" ],
    [ "RCC Peripheral Clock Force Release", "group__RCC__Peripheral__Clock__Force__Release.html", "group__RCC__Peripheral__Clock__Force__Release" ],
    [ "APB1 Force Release Reset", "group__RCC__APB1__Force__Release__Reset.html", "group__RCC__APB1__Force__Release__Reset" ],
    [ "APB2 Force Release Reset", "group__RCC__APB2__Force__Release__Reset.html", "group__RCC__APB2__Force__Release__Reset" ],
    [ "RCC Peripheral Clock Sleep Enable Disable", "group__RCC__Peripheral__Clock__Sleep__Enable__Disable.html", "group__RCC__Peripheral__Clock__Sleep__Enable__Disable" ],
    [ "AHB1 Peripheral Clock Sleep Enable Disable Status", "group__RCC__AHB1__Clock__Sleep__Enable__Disable__Status.html", "group__RCC__AHB1__Clock__Sleep__Enable__Disable__Status" ],
    [ "APB1 Peripheral Clock Sleep Enable Disable Status", "group__RCC__APB1__Clock__Sleep__Enable__Disable__Status.html", "group__RCC__APB1__Clock__Sleep__Enable__Disable__Status" ],
    [ "APB2 Peripheral Clock Sleep Enable Disable Status", "group__RCC__APB2__Clock__Sleep__Enable__Disable__Status.html", "group__RCC__APB2__Clock__Sleep__Enable__Disable__Status" ],
    [ "HSI Configuration", "group__RCC__HSI__Configuration.html", "group__RCC__HSI__Configuration" ],
    [ "LSI Configuration", "group__RCC__LSI__Configuration.html", "group__RCC__LSI__Configuration" ],
    [ "HSE Configuration", "group__RCC__HSE__Configuration.html", "group__RCC__HSE__Configuration" ],
    [ "LSE Configuration", "group__RCC__LSE__Configuration.html", "group__RCC__LSE__Configuration" ],
    [ "RTC Clock Configuration", "group__RCC__Internal__RTC__Clock__Configuration.html", "group__RCC__Internal__RTC__Clock__Configuration" ],
    [ "PLL Configuration", "group__RCC__PLL__Configuration.html", "group__RCC__PLL__Configuration" ],
    [ "PLL I2S Configuration", "group__RCC__PLL__I2S__Configuration.html", "group__RCC__PLL__I2S__Configuration" ],
    [ "Get Clock source", "group__RCC__Get__Clock__source.html", "group__RCC__Get__Clock__source" ],
    [ "RCC Extended MCOx Clock Config", "group__RCCEx__MCOx__Clock__Config.html", "group__RCCEx__MCOx__Clock__Config" ],
    [ "Flags Interrupts Management", "group__RCC__Flags__Interrupts__Management.html", "group__RCC__Flags__Interrupts__Management" ]
];