Sensorclient: BSP
BSP
STM32F7xx_HAL_Examples
Modules
Component
STM32746G_DISCOVERY
Macros
#define CIRCLE_RADIUS 30
#define CIRCLE_XPOS(i) ((i * BSP_LCD_GetXSize()) / 5)
#define CIRCLE_YPOS(i) (BSP_LCD_GetYSize() - CIRCLE_RADIUS - 60)
Functions
static void Touchscreen_SetHint (void)
Display TS Demo Hint.
static void Touchscreen_DrawBackground (uint8_t state)
Draw Touchscreen Background.
void Touchscreen_demo (void)
Touchscreen Demo.
Variables
static TS_StateTypeDef TS_State
Detailed Description
Macro Definition Documentation
CIRCLE_RADIUS
#define CIRCLE_RADIUS 30
Definition at line 32 of file touchscreen.c.
CIRCLE_XPOS
#define CIRCLE_XPOS (i) ((i * BSP_LCD_GetXSize()) / 5)
Definition at line 34 of file touchscreen.c.
CIRCLE_YPOS
#define CIRCLE_YPOS (i) (BSP_LCD_GetYSize() - CIRCLE_RADIUS - 60)
Definition at line 35 of file touchscreen.c.
Function Documentation
Touchscreen_demo()
void Touchscreen_demo (void)
Touchscreen Demo.
Parameters
None
Return values
None
Definition at line 48 of file touchscreen.c.
References BSP_LCD_DisplayStringAt(), BSP_LCD_FillCircle(), BSP_LCD_GetXSize(), BSP_LCD_GetYSize(), BSP_LCD_SetBackColor(), BSP_LCD_SetTextColor(), BSP_TS_GetState(), BSP_TS_Init(), CENTER_MODE, CIRCLE_RADIUS, CIRCLE_XPOS, CIRCLE_YPOS, HAL_Delay(), LCD_COLOR_BLACK, LCD_COLOR_BLUE, LCD_COLOR_GREEN, LCD_COLOR_RED, LCD_COLOR_WHITE, LCD_COLOR_YELLOW, LEFT_MODE, TS_StateTypeDef::touchDetected, Touchscreen_DrawBackground(), Touchscreen_SetHint(), TS_StateTypeDef::touchX, TS_StateTypeDef::touchY, TS_OK, and TS_State.
Touchscreen_DrawBackground()
static void Touchscreen_DrawBackground (uint8_t state) static
Draw Touchscreen Background.
Parameters
state : touch zone state
Return values
None
Definition at line 276 of file touchscreen.c.
References BSP_LCD_FillCircle(), BSP_LCD_SetTextColor(), CIRCLE_RADIUS, CIRCLE_XPOS, CIRCLE_YPOS, LCD_COLOR_BLUE, LCD_COLOR_GREEN, LCD_COLOR_RED, LCD_COLOR_WHITE, and LCD_COLOR_YELLOW.
Referenced by Touchscreen_demo().
Touchscreen_SetHint()
static void Touchscreen_SetHint (void) static
Display TS Demo Hint.
Parameters
None
Return values
None
Definition at line 247 of file touchscreen.c.
References BSP_LCD_Clear(), BSP_LCD_DisplayStringAt(), BSP_LCD_DrawRect(), BSP_LCD_FillRect(), BSP_LCD_GetXSize(), BSP_LCD_GetYSize(), BSP_LCD_SetBackColor(), BSP_LCD_SetFont(), BSP_LCD_SetTextColor(), CENTER_MODE, LCD_COLOR_BLUE, and LCD_COLOR_WHITE.
Referenced by Touchscreen_demo().
Variable Documentation
TS_State
TS_StateTypeDef TS_State static
Definition at line 37 of file touchscreen.c.
Referenced by AUDIO_REC_Process(), BSP_TS_GetState(), BSP_TS_ResetTouchData(), and Touchscreen_demo().