Sensorclient: STM32746G_DISCOVERY QSPI Private Functions
STM32746G_DISCOVERY QSPI Private Functions
STM32F7xx_HAL_Examples » BSP » STM32746G_DISCOVERY » STM32746G-Discovery QSPI
Functions
static uint8_t QSPI_ResetMemory (QSPI_HandleTypeDef *hqspi)
This function reset the QSPI memory.
static uint8_t QSPI_DummyCyclesCfg (QSPI_HandleTypeDef *hqspi)
This function configure the dummy cycles on memory side.
static uint8_t QSPI_WriteEnable (QSPI_HandleTypeDef *hqspi)
This function send a Write Enable and wait it is effective.
static uint8_t QSPI_AutoPollingMemReady (QSPI_HandleTypeDef *hqspi, uint32_t Timeout)
This function read the SR of the memory and wait the EOP.
__weak void BSP_QSPI_MspInit (QSPI_HandleTypeDef *hqspi, void *Params)
QSPI MSP Initialization This function configures the hardware resources used in this example:
__weak void BSP_QSPI_MspDeInit (QSPI_HandleTypeDef *hqspi, void *Params)
QSPI MSP De-Initialization This function frees the hardware resources used in this example:
Detailed Description
Function Documentation
BSP_QSPI_MspDeInit()
__weak void BSP_QSPI_MspDeInit (QSPI_HandleTypeDef * hqspi, void * Params)
QSPI MSP De-Initialization This function frees the hardware resources used in this example:
Disable the Peripheral's clock
Revert GPIO and NVIC configuration to their default state
Return values
None
Definition at line 561 of file stm32746g_discovery_qspi.c.
References HAL_GPIO_DeInit(), HAL_NVIC_DisableIRQ(), QSPI_CLK_DISABLE, QSPI_CLK_GPIO_PORT, QSPI_CLK_PIN, QSPI_CS_GPIO_PORT, QSPI_CS_PIN, QSPI_D0_GPIO_PORT, QSPI_D0_PIN, QSPI_D1_GPIO_PORT, QSPI_D1_PIN, QSPI_D2_GPIO_PORT, QSPI_D2_PIN, QSPI_D3_GPIO_PORT, QSPI_D3_PIN, QSPI_FORCE_RESET, QSPI_RELEASE_RESET, and QUADSPI_IRQn.
Referenced by BSP_QSPI_DeInit().
BSP_QSPI_MspInit()
__weak void BSP_QSPI_MspInit (QSPI_HandleTypeDef * hqspi, void * Params)
QSPI MSP Initialization This function configures the hardware resources used in this example:
Peripheral's clock enable
Peripheral's GPIO Configuration
NVIC configuration for QSPI interrupt
Return values
None
Definition at line 495 of file stm32746g_discovery_qspi.c.
References GPIO_InitTypeDef::Alternate, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_PULLUP, HAL_GPIO_Init(), HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, QSPI_CLK_ENABLE, QSPI_CLK_GPIO_CLK_ENABLE, QSPI_CLK_GPIO_PORT, QSPI_CLK_PIN, QSPI_CS_GPIO_CLK_ENABLE, QSPI_CS_GPIO_PORT, QSPI_CS_PIN, QSPI_D0_GPIO_CLK_ENABLE, QSPI_D0_GPIO_PORT, QSPI_D0_PIN, QSPI_D1_GPIO_CLK_ENABLE, QSPI_D1_GPIO_PORT, QSPI_D1_PIN, QSPI_D2_GPIO_CLK_ENABLE, QSPI_D2_GPIO_PORT, QSPI_D2_PIN, QSPI_D3_GPIO_CLK_ENABLE, QSPI_D3_GPIO_PORT, QSPI_D3_PIN, QSPI_FORCE_RESET, QSPI_RELEASE_RESET, QUADSPI_IRQn, and GPIO_InitTypeDef::Speed.
Referenced by BSP_QSPI_Init().
QSPI_AutoPollingMemReady()
static uint8_t QSPI_AutoPollingMemReady (QSPI_HandleTypeDef * hqspi, uint32_t Timeout) static
This function read the SR of the memory and wait the EOP.
Parameters
hqspi QSPI handle
Timeout
Return values
None
Definition at line 736 of file stm32746g_discovery_qspi.c.
References HAL_OK, QSPI_ERROR, and QSPI_OK.
Referenced by BSP_QSPI_Erase_Block(), BSP_QSPI_Erase_Chip(), BSP_QSPI_Write(), and QSPI_ResetMemory().
QSPI_DummyCyclesCfg()
static uint8_t QSPI_DummyCyclesCfg (QSPI_HandleTypeDef * hqspi) static
This function configure the dummy cycles on memory side.
Parameters
hqspi QSPI handle
Return values
None
Definition at line 631 of file stm32746g_discovery_qspi.c.
References HAL_OK, MODIFY_REG, POSITION_VAL, QSPI_ERROR, QSPI_OK, and QSPI_WriteEnable().
Referenced by BSP_QSPI_Init().
QSPI_ResetMemory()
static uint8_t QSPI_ResetMemory (QSPI_HandleTypeDef * hqspi) static
This function reset the QSPI memory.
Parameters
hqspi QSPI handle
Return values
None
Definition at line 589 of file stm32746g_discovery_qspi.c.
References HAL_OK, QSPI_AutoPollingMemReady(), QSPI_ERROR, and QSPI_OK.
Referenced by BSP_QSPI_Init().
QSPI_WriteEnable()
static uint8_t QSPI_WriteEnable (QSPI_HandleTypeDef * hqspi) static
This function send a Write Enable and wait it is effective.
Parameters
hqspi QSPI handle
Return values
None
Definition at line 690 of file stm32746g_discovery_qspi.c.
References HAL_OK, QSPI_ERROR, and QSPI_OK.
Referenced by BSP_QSPI_Erase_Block(), BSP_QSPI_Erase_Chip(), BSP_QSPI_Write(), and QSPI_DummyCyclesCfg().