Sensorclient: STM32746G_DISCOVERY_SDRAM Exported Functions
STM32746G_DISCOVERY_SDRAM Exported Functions
STM32F7xx_HAL_Examples » BSP » STM32746G_DISCOVERY » STM32746G_DISCOVERY_SDRAM
Functions
uint8_t BSP_SDRAM_Init (void)
Initializes the SDRAM device.
uint8_t BSP_SDRAM_DeInit (void)
DeInitializes the SDRAM device.
void BSP_SDRAM_Initialization_sequence (uint32_t RefreshCount)
Programs the SDRAM device.
uint8_t BSP_SDRAM_ReadData (uint32_t uwStartAddress, uint32_t *pData, uint32_t uwDataSize)
Reads an amount of data from the SDRAM memory in polling mode.
uint8_t BSP_SDRAM_ReadData_DMA (uint32_t uwStartAddress, uint32_t *pData, uint32_t uwDataSize)
Reads an amount of data from the SDRAM memory in DMA mode.
uint8_t BSP_SDRAM_WriteData (uint32_t uwStartAddress, uint32_t *pData, uint32_t uwDataSize)
Writes an amount of data to the SDRAM memory in polling mode.
uint8_t BSP_SDRAM_WriteData_DMA (uint32_t uwStartAddress, uint32_t *pData, uint32_t uwDataSize)
Writes an amount of data to the SDRAM memory in DMA mode.
uint8_t BSP_SDRAM_Sendcmd (FMC_SDRAM_CommandTypeDef *SdramCmd)
Sends command to the SDRAM bank.
__weak void BSP_SDRAM_MspInit (SDRAM_HandleTypeDef *hsdram, void *Params)
Initializes SDRAM MSP.
__weak void BSP_SDRAM_MspDeInit (SDRAM_HandleTypeDef *hsdram, void *Params)
DeInitializes SDRAM MSP.
Detailed Description
Function Documentation
BSP_SDRAM_DeInit()
uint8_t BSP_SDRAM_DeInit (void)
DeInitializes the SDRAM device.
Return values
SDRAM status
Definition at line 180 of file stm32746g_discovery_sdram.c.
References BSP_SDRAM_MspDeInit(), FMC_SDRAM_DEVICE, HAL_OK, HAL_SDRAM_DeInit(), SDRAM_HandleTypeDef::Instance, NULL, SDRAM_ERROR, SDRAM_OK, and sdramHandle.
BSP_SDRAM_Init()
uint8_t BSP_SDRAM_Init (void)
Initializes the SDRAM device.
Return values
SDRAM status
Definition at line 131 of file stm32746g_discovery_sdram.c.
References BSP_SDRAM_Initialization_sequence(), BSP_SDRAM_MspInit(), FMC_SDRAM_InitTypeDef::CASLatency, FMC_SDRAM_InitTypeDef::ColumnBitsNumber, FMC_SDRAM_TimingTypeDef::ExitSelfRefreshDelay, FMC_SDRAM_BANK1, FMC_SDRAM_CAS_LATENCY_2, FMC_SDRAM_COLUMN_BITS_NUM_8, FMC_SDRAM_DEVICE, FMC_SDRAM_INTERN_BANKS_NUM_4, FMC_SDRAM_RBURST_ENABLE, FMC_SDRAM_ROW_BITS_NUM_12, FMC_SDRAM_RPIPE_DELAY_0, FMC_SDRAM_WRITE_PROTECTION_DISABLE, HAL_OK, HAL_SDRAM_Init(), SDRAM_HandleTypeDef::Init, SDRAM_HandleTypeDef::Instance, FMC_SDRAM_InitTypeDef::InternalBankNumber, FMC_SDRAM_TimingTypeDef::LoadToActiveDelay, FMC_SDRAM_InitTypeDef::MemoryDataWidth, NULL, FMC_SDRAM_TimingTypeDef::RCDDelay, FMC_SDRAM_InitTypeDef::ReadBurst, FMC_SDRAM_InitTypeDef::ReadPipeDelay, REFRESH_COUNT, FMC_SDRAM_InitTypeDef::RowBitsNumber, FMC_SDRAM_TimingTypeDef::RowCycleDelay, FMC_SDRAM_TimingTypeDef::RPDelay, FMC_SDRAM_InitTypeDef::SDBank, SDCLOCK_PERIOD, FMC_SDRAM_InitTypeDef::SDClockPeriod, SDRAM_ERROR, SDRAM_MEMORY_WIDTH, SDRAM_OK, sdramHandle, FMC_SDRAM_TimingTypeDef::SelfRefreshTime, Timing, FMC_SDRAM_InitTypeDef::WriteProtection, and FMC_SDRAM_TimingTypeDef::WriteRecoveryTime.
Referenced by BSP_LCD_Init().
BSP_SDRAM_Initialization_sequence()
void BSP_SDRAM_Initialization_sequence (uint32_t RefreshCount)
Programs the SDRAM device.
Parameters
RefreshCount SDRAM refresh counter value
Return values
None
Definition at line 206 of file stm32746g_discovery_sdram.c.
References __IO, FMC_SDRAM_CommandTypeDef::AutoRefreshNumber, Command, FMC_SDRAM_CommandTypeDef::CommandMode, FMC_SDRAM_CommandTypeDef::CommandTarget, FMC_SDRAM_CMD_AUTOREFRESH_MODE, FMC_SDRAM_CMD_CLK_ENABLE, FMC_SDRAM_CMD_LOAD_MODE, FMC_SDRAM_CMD_PALL, FMC_SDRAM_CMD_TARGET_BANK1, HAL_Delay(), HAL_SDRAM_ProgramRefreshRate(), HAL_SDRAM_SendCommand(), FMC_SDRAM_CommandTypeDef::ModeRegisterDefinition, SDRAM_MODEREG_BURST_LENGTH_1, SDRAM_MODEREG_BURST_TYPE_SEQUENTIAL, SDRAM_MODEREG_CAS_LATENCY_2, SDRAM_MODEREG_OPERATING_MODE_STANDARD, SDRAM_MODEREG_WRITEBURST_MODE_SINGLE, SDRAM_TIMEOUT, and sdramHandle.
Referenced by BSP_SDRAM_Init().
BSP_SDRAM_MspDeInit()
void BSP_SDRAM_MspDeInit (SDRAM_HandleTypeDef * hsdram, void * Params)
DeInitializes SDRAM MSP.
Parameters
hsdram SDRAM handle
Params
Return values
None
Definition at line 451 of file stm32746g_discovery_sdram.c.
References HAL_DMA_DeInit(), HAL_NVIC_DisableIRQ(), __DMA_HandleTypeDef::Instance, SDRAM_DMAx_IRQn, and SDRAM_DMAx_STREAM.
Referenced by BSP_SDRAM_DeInit().
BSP_SDRAM_MspInit()
void BSP_SDRAM_MspInit (SDRAM_HandleTypeDef * hsdram, void * Params)
Initializes SDRAM MSP.
Parameters
hsdram SDRAM handle
Params
Return values
None
Definition at line 360 of file stm32746g_discovery_sdram.c.
References __DMAx_CLK_ENABLE, __HAL_LINKDMA, __HAL_RCC_FMC_CLK_ENABLE, __HAL_RCC_GPIOC_CLK_ENABLE, __HAL_RCC_GPIOD_CLK_ENABLE, __HAL_RCC_GPIOE_CLK_ENABLE, __HAL_RCC_GPIOF_CLK_ENABLE, __HAL_RCC_GPIOG_CLK_ENABLE, __HAL_RCC_GPIOH_CLK_ENABLE, GPIO_InitTypeDef::Alternate, DMA_InitTypeDef::Channel, DMA_InitTypeDef::Direction, DMA_FIFO_THRESHOLD_FULL, DMA_FIFOMODE_DISABLE, DMA_MBURST_SINGLE, DMA_MDATAALIGN_WORD, DMA_MEMORY_TO_MEMORY, DMA_MINC_ENABLE, DMA_NORMAL, DMA_PBURST_SINGLE, DMA_PDATAALIGN_WORD, DMA_PINC_ENABLE, DMA_PRIORITY_HIGH, DMA_InitTypeDef::FIFOMode, DMA_InitTypeDef::FIFOThreshold, GPIO_MODE_AF_PP, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_7, GPIO_PIN_8, GPIO_PIN_9, GPIO_PULLUP, GPIOC, GPIOD, GPIOE, GPIOF, GPIOG, GPIOH, HAL_DMA_DeInit(), HAL_DMA_Init(), HAL_GPIO_Init(), HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), __DMA_HandleTypeDef::Init, __DMA_HandleTypeDef::Instance, DMA_InitTypeDef::MemBurst, DMA_InitTypeDef::MemDataAlignment, DMA_InitTypeDef::MemInc, GPIO_InitTypeDef::Mode, DMA_InitTypeDef::Mode, DMA_InitTypeDef::PeriphBurst, DMA_InitTypeDef::PeriphDataAlignment, DMA_InitTypeDef::PeriphInc, GPIO_InitTypeDef::Pin, DMA_InitTypeDef::Priority, GPIO_InitTypeDef::Pull, SDRAM_DMAx_CHANNEL, SDRAM_DMAx_IRQn, SDRAM_DMAx_STREAM, and GPIO_InitTypeDef::Speed.
Referenced by BSP_SDRAM_Init().
BSP_SDRAM_ReadData()
uint8_t BSP_SDRAM_ReadData (uint32_t uwStartAddress, uint32_t * pData, uint32_t uwDataSize)
Reads an amount of data from the SDRAM memory in polling mode.
Parameters
uwStartAddress Read start address
pData Pointer to data to be read
uwDataSize Size of read data from the memory
Return values
SDRAM status
Definition at line 268 of file stm32746g_discovery_sdram.c.
References HAL_OK, HAL_SDRAM_Read_32b(), SDRAM_ERROR, SDRAM_OK, and sdramHandle.
BSP_SDRAM_ReadData_DMA()
uint8_t BSP_SDRAM_ReadData_DMA (uint32_t uwStartAddress, uint32_t * pData, uint32_t uwDataSize)
Reads an amount of data from the SDRAM memory in DMA mode.
Parameters
uwStartAddress Read start address
pData Pointer to data to be read
uwDataSize Size of read data from the memory
Return values
SDRAM status
Definition at line 287 of file stm32746g_discovery_sdram.c.
References HAL_OK, HAL_SDRAM_Read_DMA(), SDRAM_ERROR, SDRAM_OK, and sdramHandle.
BSP_SDRAM_Sendcmd()
uint8_t BSP_SDRAM_Sendcmd (FMC_SDRAM_CommandTypeDef * SdramCmd)
Sends command to the SDRAM bank.
Parameters
SdramCmd Pointer to SDRAM command structure
Return values
SDRAM status
Definition at line 342 of file stm32746g_discovery_sdram.c.
References HAL_OK, HAL_SDRAM_SendCommand(), SDRAM_ERROR, SDRAM_OK, SDRAM_TIMEOUT, and sdramHandle.
BSP_SDRAM_WriteData()
uint8_t BSP_SDRAM_WriteData (uint32_t uwStartAddress, uint32_t * pData, uint32_t uwDataSize)
Writes an amount of data to the SDRAM memory in polling mode.
Parameters
uwStartAddress Write start address
pData Pointer to data to be written
uwDataSize Size of written data from the memory
Return values
SDRAM status
Definition at line 306 of file stm32746g_discovery_sdram.c.
References HAL_OK, HAL_SDRAM_Write_32b(), SDRAM_ERROR, SDRAM_OK, and sdramHandle.
BSP_SDRAM_WriteData_DMA()
uint8_t BSP_SDRAM_WriteData_DMA (uint32_t uwStartAddress, uint32_t * pData, uint32_t uwDataSize)
Writes an amount of data to the SDRAM memory in DMA mode.
Parameters
uwStartAddress Write start address
pData Pointer to data to be written
uwDataSize Size of written data from the memory
Return values
SDRAM status
Definition at line 325 of file stm32746g_discovery_sdram.c.
References HAL_OK, HAL_SDRAM_Write_DMA(), SDRAM_ERROR, SDRAM_OK, and sdramHandle.