Sensorclient: STM32746G_DISCOVERY_LOW_LEVELSTM32746G_DISCOVERY_LOW_LEVEL Exported Functions
STM32746G_DISCOVERY_LOW_LEVELSTM32746G_DISCOVERY_LOW_LEVEL Exported Functions
STM32F7xx_HAL_Examples » BSP » STM32746G_DISCOVERY » STM32746G_DISCOVERY_LOW_LEVEL
Functions
uint32_t BSP_GetVersion (void)
This method returns the STM32746G DISCOVERY BSP Driver revision.
void BSP_LED_Init (Led_TypeDef Led)
Configures LED on GPIO.
void BSP_LED_DeInit (Led_TypeDef Led)
DeInit LEDs.
void BSP_LED_On (Led_TypeDef Led)
Turns selected LED On.
void BSP_LED_Off (Led_TypeDef Led)
Turns selected LED Off.
void BSP_LED_Toggle (Led_TypeDef Led)
Toggles the selected LED.
void BSP_PB_Init (Button_TypeDef Button, ButtonMode_TypeDef ButtonMode)
Configures button GPIO and EXTI Line.
void BSP_PB_DeInit (Button_TypeDef Button)
Push Button DeInit.
uint32_t BSP_PB_GetState (Button_TypeDef Button)
Returns the selected button state.
void BSP_COM_Init (COM_TypeDef COM, UART_HandleTypeDef *huart)
Configures COM port.
void BSP_COM_DeInit (COM_TypeDef COM, UART_HandleTypeDef *huart)
DeInit COM port.
static void I2Cx_MspInit (I2C_HandleTypeDef *i2c_handler)
Initializes I2C MSP.
static void I2Cx_Init (I2C_HandleTypeDef *i2c_handler)
Initializes I2C HAL.
static HAL_StatusTypeDef I2Cx_ReadMultiple (I2C_HandleTypeDef *i2c_handler, uint8_t Addr, uint16_t Reg, uint16_t MemAddress, uint8_t *Buffer, uint16_t Length)
Reads multiple data.
static HAL_StatusTypeDef I2Cx_WriteMultiple (I2C_HandleTypeDef *i2c_handler, uint8_t Addr, uint16_t Reg, uint16_t MemAddress, uint8_t *Buffer, uint16_t Length)
Writes a value in a register of the device through BUS in using DMA mode.
static HAL_StatusTypeDef I2Cx_IsDeviceReady (I2C_HandleTypeDef *i2c_handler, uint16_t DevAddress, uint32_t Trials)
Checks if target device is ready for communication.
static void I2Cx_Error (I2C_HandleTypeDef *i2c_handler, uint8_t Addr)
Manages error callback by re-initializing I2C.
void AUDIO_IO_Init (void)
Initializes Audio low level.
void AUDIO_IO_DeInit (void)
Deinitializes Audio low level.
void AUDIO_IO_Write (uint8_t Addr, uint16_t Reg, uint16_t Value)
Writes a single data.
uint16_t AUDIO_IO_Read (uint8_t Addr, uint16_t Reg)
Reads a single data.
void AUDIO_IO_Delay (uint32_t Delay)
AUDIO Codec delay.
void CAMERA_IO_Init (void)
Initializes Camera low level.
void CAMERA_IO_Write (uint8_t Addr, uint8_t Reg, uint8_t Value)
Camera writes single data.
uint8_t CAMERA_IO_Read (uint8_t Addr, uint8_t Reg)
Camera reads single data.
void CAMERA_Delay (uint32_t Delay)
Camera delay.
void EEPROM_IO_Init (void)
Initializes peripherals used by the I2C EEPROM driver.
HAL_StatusTypeDef EEPROM_IO_WriteData (uint16_t DevAddress, uint16_t MemAddress, uint8_t *pBuffer, uint32_t BufferSize)
Write data to I2C EEPROM driver in using DMA channel.
HAL_StatusTypeDef EEPROM_IO_ReadData (uint16_t DevAddress, uint16_t MemAddress, uint8_t *pBuffer, uint32_t BufferSize)
Read data from I2C EEPROM driver in using DMA channel.
HAL_StatusTypeDef EEPROM_IO_IsDeviceReady (uint16_t DevAddress, uint32_t Trials)
Checks if target device is ready for communication.
void TS_IO_Init (void)
Initializes Touchscreen low level.
void TS_IO_Write (uint8_t Addr, uint8_t Reg, uint8_t Value)
Writes a single data.
uint8_t TS_IO_Read (uint8_t Addr, uint8_t Reg)
Reads a single data.
void TS_IO_Delay (uint32_t Delay)
TS delay.
Detailed Description
Function Documentation
AUDIO_IO_DeInit()
void AUDIO_IO_DeInit (void)
Deinitializes Audio low level.
Return values
None
Definition at line 669 of file stm32746g_discovery.c.
AUDIO_IO_Delay()
void AUDIO_IO_Delay (uint32_t Delay)
AUDIO Codec delay.
Parameters
Delay Delay in ms
Return values
None
Definition at line 717 of file stm32746g_discovery.c.
AUDIO_IO_Init()
void AUDIO_IO_Init (void)
Initializes Audio low level.
Return values
None
Definition at line 660 of file stm32746g_discovery.c.
AUDIO_IO_Read()
uint16_t AUDIO_IO_Read (uint8_t Addr, uint16_t Reg)
Reads a single data.
Parameters
Addr I2C address
Reg Reg address
Return values
Data to be read
Definition at line 697 of file stm32746g_discovery.c.
AUDIO_IO_Write()
void AUDIO_IO_Write (uint8_t Addr, uint16_t Reg, uint16_t Value)
Writes a single data.
Parameters
Addr I2C address
Reg Reg address
Value Data to be written
Return values
None
Definition at line 680 of file stm32746g_discovery.c.
BSP_COM_DeInit()
void BSP_COM_DeInit (COM_TypeDef COM, UART_HandleTypeDef * huart)
DeInit COM port.
Parameters
COM COM port to be configured. This parameter can be one of the following values:
COM1
COM2
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified USART peripheral.
Return values
None
Definition at line 423 of file stm32746g_discovery.c.
References COM_USART, DISCOVERY_COMx_CLK_DISABLE, HAL_UART_DeInit(), and __UART_HandleTypeDef::Instance.
BSP_COM_Init()
void BSP_COM_Init (COM_TypeDef COM, UART_HandleTypeDef * huart)
Configures COM port.
Parameters
COM COM port to be configured. This parameter can be one of the following values:
COM1
COM2
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified USART peripheral.
Return values
None
Definition at line 383 of file stm32746g_discovery.c.
References GPIO_InitTypeDef::Alternate, COM_RX_AF, COM_RX_PIN, COM_RX_PORT, COM_TX_AF, COM_TX_PIN, COM_TX_PORT, COM_USART, DISCOVERY_COMx_CLK_ENABLE, DISCOVERY_COMx_RX_GPIO_CLK_ENABLE, DISCOVERY_COMx_TX_GPIO_CLK_ENABLE, GPIO_MODE_AF_PP, GPIO_PULLUP, HAL_GPIO_Init(), HAL_UART_Init(), __UART_HandleTypeDef::Instance, GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, and GPIO_InitTypeDef::Speed.
BSP_GetVersion()
uint32_t BSP_GetVersion (void)
This method returns the STM32746G DISCOVERY BSP Driver revision.
Return values
version 0xXYZR (8bits for each decimal, R for RC)
Definition at line 161 of file stm32746g_discovery.c.
References __STM32746G_DISCO_BSP_VERSION.
BSP_LED_DeInit()
void BSP_LED_DeInit (Led_TypeDef Led)
DeInit LEDs.
Parameters
Led LED to be configured. This parameter can be one of the following values:
LED1
Note
Led DeInit does not disable the GPIO clock
Return values
None
Definition at line 205 of file stm32746g_discovery.c.
References GPIO_PIN, GPIO_PIN_RESET, HAL_GPIO_DeInit(), HAL_GPIO_WritePin(), LED1, LED1_GPIO_PORT, and GPIO_InitTypeDef::Pin.
BSP_LED_Init()
void BSP_LED_Init (Led_TypeDef Led)
Configures LED on GPIO.
Parameters
Led LED to be configured. This parameter can be one of the following values:
LED1
Return values
None
Definition at line 173 of file stm32746g_discovery.c.
References GPIO_MODE_OUTPUT_PP, GPIO_PIN, GPIO_PIN_RESET, GPIO_PULLUP, HAL_GPIO_Init(), HAL_GPIO_WritePin(), LED1, LED1_GPIO_CLK_ENABLE, LED1_GPIO_PORT, GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, and GPIO_InitTypeDef::Speed.
BSP_LED_Off()
void BSP_LED_Off (Led_TypeDef Led)
Turns selected LED Off.
Parameters
Led LED to be set off This parameter can be one of the following values:
LED1
Return values
None
Definition at line 246 of file stm32746g_discovery.c.
References GPIO_PIN, GPIO_PIN_RESET, HAL_GPIO_WritePin(), LED1, and LED1_GPIO_PORT.
BSP_LED_On()
void BSP_LED_On (Led_TypeDef Led)
Turns selected LED On.
Parameters
Led LED to be set on This parameter can be one of the following values:
LED1
Return values
None
Definition at line 228 of file stm32746g_discovery.c.
References GPIO_PIN, GPIO_PIN_SET, HAL_GPIO_WritePin(), LED1, and LED1_GPIO_PORT.
BSP_LED_Toggle()
void BSP_LED_Toggle (Led_TypeDef Led)
Toggles the selected LED.
Parameters
Led LED to be toggled This parameter can be one of the following values:
LED1
Return values
None
Definition at line 264 of file stm32746g_discovery.c.
References GPIO_PIN, HAL_GPIO_TogglePin(), LED1, and LED1_GPIO_PORT.
BSP_PB_DeInit()
void BSP_PB_DeInit (Button_TypeDef Button)
Push Button DeInit.
Parameters
Button Button to be configured This parameter can be one of the following values:
BUTTON_WAKEUP: Wakeup Push Button
BUTTON_TAMPER: Tamper Push Button
BUTTON_KEY: Key Push Button
Note
On STM32746G-Discovery board, the three buttons (Wakeup, Tamper and key buttons) are mapped on the same push button named "User" on the board serigraphy.
PB DeInit does not disable the GPIO clock
Return values
None
Definition at line 346 of file stm32746g_discovery.c.
References BUTTON_IRQn, BUTTON_PIN, BUTTON_PORT, HAL_GPIO_DeInit(), HAL_NVIC_DisableIRQ(), and GPIO_InitTypeDef::Pin.
BSP_PB_GetState()
uint32_t BSP_PB_GetState (Button_TypeDef Button)
Returns the selected button state.
Parameters
Button Button to be checked This parameter can be one of the following values:
BUTTON_WAKEUP: Wakeup Push Button
BUTTON_TAMPER: Tamper Push Button
BUTTON_KEY: Key Push Button
Note
On STM32746G-Discovery board, the three buttons (Wakeup, Tamper and key buttons) are mapped on the same push button named "User" on the board serigraphy.
Return values
The Button GPIO pin value
Definition at line 368 of file stm32746g_discovery.c.
References BUTTON_PIN, BUTTON_PORT, and HAL_GPIO_ReadPin().
BSP_PB_Init()
void BSP_PB_Init (Button_TypeDef Button, ButtonMode_TypeDef ButtonMode)
Configures button GPIO and EXTI Line.
Parameters
Button Button to be configured This parameter can be one of the following values:
BUTTON_WAKEUP: Wakeup Push Button
BUTTON_TAMPER: Tamper Push Button
BUTTON_KEY: Key Push Button
ButtonMode Button mode This parameter can be one of the following values:
BUTTON_MODE_GPIO: Button will be used as simple IO
BUTTON_MODE_EXTI: Button will be connected to EXTI line with interrupt generation capability
Note
On STM32746G-Discovery board, the three buttons (Wakeup, Tamper and key buttons) are mapped on the same push button named "User" on the board serigraphy.
Return values
None
Definition at line 292 of file stm32746g_discovery.c.
References BUTTON_IRQn, BUTTON_MODE_EXTI, BUTTON_MODE_GPIO, BUTTON_PIN, BUTTON_PORT, BUTTON_WAKEUP, BUTTONx_GPIO_CLK_ENABLE, GPIO_MODE_INPUT, GPIO_MODE_IT_FALLING, GPIO_MODE_IT_RISING, GPIO_NOPULL, HAL_GPIO_Init(), HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, and GPIO_InitTypeDef::Speed.
CAMERA_Delay()
void CAMERA_Delay (uint32_t Delay)
Camera delay.
Parameters
Delay Delay in ms
Return values
None
Definition at line 765 of file stm32746g_discovery.c.
CAMERA_IO_Init()
void CAMERA_IO_Init (void)
Initializes Camera low level.
Return values
None
Definition at line 728 of file stm32746g_discovery.c.
CAMERA_IO_Read()
uint8_t CAMERA_IO_Read (uint8_t Addr, uint8_t Reg)
Camera reads single data.
Parameters
Addr I2C address
Reg Register address
Return values
Read data
Definition at line 751 of file stm32746g_discovery.c.
CAMERA_IO_Write()
void CAMERA_IO_Write (uint8_t Addr, uint8_t Reg, uint8_t Value)
Camera writes single data.
Parameters
Addr I2C address
Reg Register address
Value Data to be written
Return values
None
Definition at line 740 of file stm32746g_discovery.c.
EEPROM_IO_Init()
void EEPROM_IO_Init (void)
Initializes peripherals used by the I2C EEPROM driver.
Return values
None
Definition at line 776 of file stm32746g_discovery.c.
Referenced by BSP_EEPROM_Init().
EEPROM_IO_IsDeviceReady()
HAL_StatusTypeDef EEPROM_IO_IsDeviceReady (uint16_t DevAddress, uint32_t Trials)
Checks if target device is ready for communication.
Note
This function is used with Memory devices
Parameters
DevAddress Target device address
Trials Number of trials
Return values
HAL status
Definition at line 814 of file stm32746g_discovery.c.
Referenced by BSP_EEPROM_Init(), and BSP_EEPROM_WaitEepromStandbyState().
EEPROM_IO_ReadData()
HAL_StatusTypeDef EEPROM_IO_ReadData (uint16_t DevAddress, uint16_t MemAddress, uint8_t * pBuffer, uint32_t BufferSize)
Read data from I2C EEPROM driver in using DMA channel.
Parameters
DevAddress Target device address
MemAddress Internal memory address
pBuffer Pointer to data buffer
BufferSize Amount of data to be read
Return values
HAL status
Definition at line 802 of file stm32746g_discovery.c.
Referenced by BSP_EEPROM_ReadBuffer().
EEPROM_IO_WriteData()
HAL_StatusTypeDef EEPROM_IO_WriteData (uint16_t DevAddress, uint16_t MemAddress, uint8_t * pBuffer, uint32_t BufferSize)
Write data to I2C EEPROM driver in using DMA channel.
Parameters
DevAddress Target device address
MemAddress Internal memory address
pBuffer Pointer to data buffer
BufferSize Amount of data to be sent
Return values
HAL status
Definition at line 789 of file stm32746g_discovery.c.
Referenced by BSP_EEPROM_WritePage().
I2Cx_Error()
static void I2Cx_Error (I2C_HandleTypeDef * i2c_handler, uint8_t Addr) static
Manages error callback by re-initializing I2C.
Parameters
i2c_handler : I2C handler
Addr I2C Address
Return values
None
Definition at line 642 of file stm32746g_discovery.c.
I2Cx_Init()
static void I2Cx_Init (I2C_HandleTypeDef * i2c_handler) static
Initializes I2C HAL.
Parameters
i2c_handler : I2C handler
Return values
None
Definition at line 535 of file stm32746g_discovery.c.
I2Cx_IsDeviceReady()
static HAL_StatusTypeDef I2Cx_IsDeviceReady (I2C_HandleTypeDef * i2c_handler, uint16_t DevAddress, uint32_t Trials) static
Checks if target device is ready for communication.
Note
This function is used with Memory devices
Parameters
i2c_handler : I2C handler
DevAddress Target device address
Trials Number of trials
Return values
HAL status
Definition at line 631 of file stm32746g_discovery.c.
I2Cx_MspInit()
static void I2Cx_MspInit (I2C_HandleTypeDef * i2c_handler) static
Initializes I2C MSP.
Parameters
i2c_handler : I2C handler
Return values
None
Definition at line 448 of file stm32746g_discovery.c.
I2Cx_ReadMultiple()
static HAL_StatusTypeDef I2Cx_ReadMultiple (I2C_HandleTypeDef * i2c_handler, uint8_t Addr, uint16_t Reg, uint16_t MemAddress, uint8_t * Buffer, uint16_t Length) static
Reads multiple data.
Parameters
i2c_handler : I2C handler
Addr I2C address
Reg Reg address
MemAddress Memory address
Buffer Pointer to data buffer
Length Length of the data
Return values
Number of read data
Definition at line 573 of file stm32746g_discovery.c.
I2Cx_WriteMultiple()
static HAL_StatusTypeDef I2Cx_WriteMultiple (I2C_HandleTypeDef * i2c_handler, uint8_t Addr, uint16_t Reg, uint16_t MemAddress, uint8_t * Buffer, uint16_t Length) static
Writes a value in a register of the device through BUS in using DMA mode.
Parameters
i2c_handler : I2C handler
Addr Device address on BUS Bus.
Reg The target register address to write
MemAddress Memory address
Buffer The target register value to be written
Length buffer size to be written
Return values
HAL status
Definition at line 603 of file stm32746g_discovery.c.
TS_IO_Delay()
void TS_IO_Delay (uint32_t Delay)
TS delay.
Parameters
Delay Delay in ms
Return values
None
Definition at line 862 of file stm32746g_discovery.c.
TS_IO_Init()
void TS_IO_Init (void)
Initializes Touchscreen low level.
Return values
None
Definition at line 825 of file stm32746g_discovery.c.
TS_IO_Read()
uint8_t TS_IO_Read (uint8_t Addr, uint8_t Reg)
Reads a single data.
Parameters
Addr I2C address
Reg Reg address
Return values
Data to be read
Definition at line 848 of file stm32746g_discovery.c.
TS_IO_Write()
void TS_IO_Write (uint8_t Addr, uint8_t Reg, uint8_t Value)
Writes a single data.
Parameters
Addr I2C address
Reg Reg address
Value Data to be written
Return values
None
Definition at line 837 of file stm32746g_discovery.c.