Sensorclient: STM32746G_DISCOVERY_LCD Exported Functions
STM32746G_DISCOVERY_LCD Exported Functions
STM32F7xx_HAL_Examples » BSP » STM32746G_DISCOVERY » STM32746G_DISCOVERY_LCD
Functions
uint8_t BSP_LCD_Init (void)
Initializes the LCD.
uint8_t BSP_LCD_DeInit (void)
DeInitializes the LCD.
uint32_t BSP_LCD_GetXSize (void)
Gets the LCD X size.
uint32_t BSP_LCD_GetYSize (void)
Gets the LCD Y size.
void BSP_LCD_SetXSize (uint32_t imageWidthPixels)
Set the LCD X size.
void BSP_LCD_SetYSize (uint32_t imageHeightPixels)
Set the LCD Y size.
void BSP_LCD_LayerDefaultInit (uint16_t LayerIndex, uint32_t FB_Address)
Initializes the LCD layer in ARGB8888 format (32 bits per pixel).
void BSP_LCD_LayerRgb565Init (uint16_t LayerIndex, uint32_t FB_Address)
Initializes the LCD layer in RGB565 format (16 bits per pixel).
void BSP_LCD_SelectLayer (uint32_t LayerIndex)
Selects the LCD Layer.
void BSP_LCD_SetLayerVisible (uint32_t LayerIndex, FunctionalState State)
Sets an LCD Layer visible.
void BSP_LCD_SetLayerVisible_NoReload (uint32_t LayerIndex, FunctionalState State)
Sets an LCD Layer visible without reloading.
void BSP_LCD_SetTransparency (uint32_t LayerIndex, uint8_t Transparency)
Configures the transparency.
void BSP_LCD_SetTransparency_NoReload (uint32_t LayerIndex, uint8_t Transparency)
Configures the transparency without reloading.
void BSP_LCD_SetLayerAddress (uint32_t LayerIndex, uint32_t Address)
Sets an LCD layer frame buffer address.
void BSP_LCD_SetLayerAddress_NoReload (uint32_t LayerIndex, uint32_t Address)
Sets an LCD layer frame buffer address without reloading.
void BSP_LCD_SetLayerWindow (uint16_t LayerIndex, uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Sets display window.
void BSP_LCD_SetLayerWindow_NoReload (uint16_t LayerIndex, uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Sets display window without reloading.
void BSP_LCD_SetColorKeying (uint32_t LayerIndex, uint32_t RGBValue)
Configures and sets the color keying.
void BSP_LCD_SetColorKeying_NoReload (uint32_t LayerIndex, uint32_t RGBValue)
Configures and sets the color keying without reloading.
void BSP_LCD_ResetColorKeying (uint32_t LayerIndex)
Disables the color keying.
void BSP_LCD_ResetColorKeying_NoReload (uint32_t LayerIndex)
Disables the color keying without reloading.
void BSP_LCD_Reload (uint32_t ReloadType)
Disables the color keying without reloading.
void BSP_LCD_SetTextColor (uint32_t Color)
Sets the LCD text color.
uint32_t BSP_LCD_GetTextColor (void)
Gets the LCD text color.
void BSP_LCD_SetBackColor (uint32_t Color)
Sets the LCD background color.
uint32_t BSP_LCD_GetBackColor (void)
Gets the LCD background color.
void BSP_LCD_SetFont (sFONT *fonts)
Sets the LCD text font.
sFONT * BSP_LCD_GetFont (void)
Gets the LCD text font.
uint32_t BSP_LCD_ReadPixel (uint16_t Xpos, uint16_t Ypos)
Reads an LCD pixel.
void BSP_LCD_Clear (uint32_t Color)
Clears the hole LCD.
void BSP_LCD_ClearStringLine (uint32_t Line)
Clears the selected line.
void BSP_LCD_DisplayChar (uint16_t Xpos, uint16_t Ypos, uint8_t Ascii)
Displays one character.
void BSP_LCD_DisplayStringAt (uint16_t Xpos, uint16_t Ypos, uint8_t *Text, Text_AlignModeTypdef Mode)
Displays characters on the LCD.
void BSP_LCD_DisplayStringAtLine (uint16_t Line, uint8_t *ptr)
Displays a maximum of 60 characters on the LCD.
void BSP_LCD_DrawHLine (uint16_t Xpos, uint16_t Ypos, uint16_t Length)
Draws an horizontal line.
void BSP_LCD_DrawVLine (uint16_t Xpos, uint16_t Ypos, uint16_t Length)
Draws a vertical line.
void BSP_LCD_DrawLine (uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2)
Draws an uni-line (between two points).
void BSP_LCD_DrawRect (uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Draws a rectangle.
void BSP_LCD_DrawCircle (uint16_t Xpos, uint16_t Ypos, uint16_t Radius)
Draws a circle.
void BSP_LCD_DrawPolygon (pPoint Points, uint16_t PointCount)
Draws an poly-line (between many points).
void BSP_LCD_DrawEllipse (int Xpos, int Ypos, int XRadius, int YRadius)
Draws an ellipse on LCD.
void BSP_LCD_DrawPixel (uint16_t Xpos, uint16_t Ypos, uint32_t RGB_Code)
Draws a pixel on LCD.
void BSP_LCD_DrawBitmap (uint32_t Xpos, uint32_t Ypos, uint8_t *pbmp)
Draws a bitmap picture loaded in the internal Flash in ARGB888 format (32 bits per pixel).
void BSP_LCD_FillRect (uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Draws a full rectangle.
void BSP_LCD_FillCircle (uint16_t Xpos, uint16_t Ypos, uint16_t Radius)
Draws a full circle.
void BSP_LCD_FillPolygon (pPoint Points, uint16_t PointCount)
Draws a full poly-line (between many points).
void BSP_LCD_FillEllipse (int Xpos, int Ypos, int XRadius, int YRadius)
Draws a full ellipse.
void BSP_LCD_DisplayOn (void)
Enables the display.
void BSP_LCD_DisplayOff (void)
Disables the display.
__weak void BSP_LCD_MspInit (LTDC_HandleTypeDef *hltdc, void *Params)
Initializes the LTDC MSP.
__weak void BSP_LCD_MspDeInit (LTDC_HandleTypeDef *hltdc, void *Params)
DeInitializes BSP_LCD MSP.
__weak void BSP_LCD_ClockConfig (LTDC_HandleTypeDef *hltdc, void *Params)
Clock Config.
static void DrawChar (uint16_t Xpos, uint16_t Ypos, const uint8_t *c)
Draws a character on LCD.
static void FillTriangle (uint16_t x1, uint16_t x2, uint16_t x3, uint16_t y1, uint16_t y2, uint16_t y3)
Fills a triangle (between 3 points).
static void LL_FillBuffer (uint32_t LayerIndex, void *pDst, uint32_t xSize, uint32_t ySize, uint32_t OffLine, uint32_t ColorIndex)
Fills a buffer.
static void LL_ConvertLineToARGB8888 (void *pSrc, void *pDst, uint32_t xSize, uint32_t ColorMode)
Converts a line to an ARGB8888 pixel format.
Detailed Description
Function Documentation
BSP_LCD_Clear()
void BSP_LCD_Clear (uint32_t Color)
Clears the hole LCD.
Parameters
Color Color of the background
Return values
None
Definition at line 628 of file stm32746g_discovery_lcd.c.
References ActiveLayer, BSP_LCD_GetXSize(), BSP_LCD_GetYSize(), hLtdcHandler, and LL_FillBuffer().
Referenced by Touchscreen_SetHint().
BSP_LCD_ClearStringLine()
void BSP_LCD_ClearStringLine (uint32_t Line)
Clears the selected line.
Parameters
Line Line to be cleared
Return values
None
Definition at line 639 of file stm32746g_discovery_lcd.c.
References ActiveLayer, LCD_DrawPropTypeDef::BackColor, BSP_LCD_FillRect(), BSP_LCD_GetXSize(), BSP_LCD_SetTextColor(), DrawProp, and LCD_DrawPropTypeDef::TextColor.
Referenced by AUDIO_REC_Process(), and AUDIO_REC_Start().
BSP_LCD_ClockConfig()
void BSP_LCD_ClockConfig (LTDC_HandleTypeDef * hltdc, void * Params)
Clock Config.
Parameters
hltdc LTDC handle
Params
Note
This API is called by BSP_LCD_Init() Being __weak it can be overwritten by the application
Return values
None
Definition at line 1400 of file stm32746g_discovery_lcd.c.
References HAL_RCCEx_PeriphCLKConfig(), RCC_PeriphCLKInitTypeDef::PeriphClockSelection, RCC_PeriphCLKInitTypeDef::PLLSAI, RCC_PeriphCLKInitTypeDef::PLLSAIDivR, RCC_PLLSAIInitTypeDef::PLLSAIN, and RCC_PLLSAIDIVR_4.
Referenced by BSP_LCD_Init().
BSP_LCD_DeInit()
uint8_t BSP_LCD_DeInit (void)
DeInitializes the LCD.
Return values
LCD state
Definition at line 211 of file stm32746g_discovery_lcd.c.
References BSP_LCD_MspDeInit(), hLtdcHandler, LCD_OK, LTDC, and NULL.
BSP_LCD_DisplayChar()
void BSP_LCD_DisplayChar (uint16_t Xpos, uint16_t Ypos, uint8_t Ascii)
Displays one character.
Parameters
Xpos Start column address
Ypos Line where to display the character shape.
Ascii Character ascii code This parameter must be a number between Min_Data = 0x20 and Max_Data = 0x7E
Return values
None
Definition at line 659 of file stm32746g_discovery_lcd.c.
References ActiveLayer, DrawChar(), DrawProp, and LCD_DrawPropTypeDef::pFont.
Referenced by BSP_LCD_DisplayStringAt().
BSP_LCD_DisplayOff()
void BSP_LCD_DisplayOff (void)
Disables the display.
Return values
None
Definition at line 1265 of file stm32746g_discovery_lcd.c.
References GPIO_PIN_RESET, HAL_GPIO_WritePin(), hLtdcHandler, LCD_BL_CTRL_GPIO_PORT, LCD_BL_CTRL_PIN, LCD_DISP_GPIO_PORT, and LCD_DISP_PIN.
BSP_LCD_DisplayOn()
void BSP_LCD_DisplayOn (void)
Enables the display.
Return values
None
Definition at line 1253 of file stm32746g_discovery_lcd.c.
References GPIO_PIN_SET, HAL_GPIO_WritePin(), hLtdcHandler, LCD_BL_CTRL_GPIO_PORT, LCD_BL_CTRL_PIN, LCD_DISP_GPIO_PORT, and LCD_DISP_PIN.
BSP_LCD_DisplayStringAt()
void BSP_LCD_DisplayStringAt (uint16_t Xpos, uint16_t Ypos, uint8_t * Text, Text_AlignModeTypdef Mode)
Displays characters on the LCD.
Parameters
Xpos X position (in pixel)
Ypos Y position (in pixel)
Text Pointer to string to display on LCD
Mode Display mode This parameter can be one of the following values:
CENTER_MODE
RIGHT_MODE
LEFT_MODE
Return values
None
Definition at line 677 of file stm32746g_discovery_lcd.c.
References ActiveLayer, BSP_LCD_DisplayChar(), BSP_LCD_GetXSize(), CENTER_MODE, DrawProp, LEFT_MODE, LCD_DrawPropTypeDef::pFont, and RIGHT_MODE.
Referenced by AUDIO_REC_Process(), AUDIO_REC_Start(), BSP_LCD_DisplayStringAtLine(), Touchscreen_demo(), and Touchscreen_SetHint().
BSP_LCD_DisplayStringAtLine()
void BSP_LCD_DisplayStringAtLine (uint16_t Line, uint8_t * ptr)
Displays a maximum of 60 characters on the LCD.
Parameters
Line Line where to display the character shape
ptr Pointer to string to display on LCD
Return values
None
Definition at line 738 of file stm32746g_discovery_lcd.c.
References BSP_LCD_DisplayStringAt(), and LEFT_MODE.
Referenced by AUDIO_REC_Process(), and AUDIO_REC_Start().
BSP_LCD_DrawBitmap()
void BSP_LCD_DrawBitmap (uint32_t Xpos, uint32_t Ypos, uint8_t * pbmp)
Draws a bitmap picture loaded in the internal Flash in ARGB888 format (32 bits per pixel).
Parameters
Xpos Bmp X position in the LCD
Ypos Bmp Y position in the LCD
pbmp Pointer to Bmp picture address in the internal Flash
Return values
None
Definition at line 1022 of file stm32746g_discovery_lcd.c.
References ActiveLayer, BSP_LCD_GetXSize(), hLtdcHandler, and LL_ConvertLineToARGB8888().
BSP_LCD_DrawCircle()
void BSP_LCD_DrawCircle (uint16_t Xpos, uint16_t Ypos, uint16_t Radius)
Draws a circle.
Parameters
Xpos X position
Ypos Y position
Radius Circle radius
Return values
None
Definition at line 894 of file stm32746g_discovery_lcd.c.
References ActiveLayer, BSP_LCD_DrawPixel(), and DrawProp.
Referenced by BSP_LCD_FillCircle().
BSP_LCD_DrawEllipse()
void BSP_LCD_DrawEllipse (int Xpos, int Ypos, int XRadius, int YRadius)
Draws an ellipse on LCD.
Parameters
Xpos X position
Ypos Y position
XRadius Ellipse X radius
YRadius Ellipse Y radius
Return values
None
Definition at line 969 of file stm32746g_discovery_lcd.c.
References ActiveLayer, BSP_LCD_DrawPixel(), and DrawProp.
BSP_LCD_DrawHLine()
void BSP_LCD_DrawHLine (uint16_t Xpos, uint16_t Ypos, uint16_t Length)
Draws an horizontal line.
Parameters
Xpos X position
Ypos Y position
Length Line length
Return values
None
Definition at line 750 of file stm32746g_discovery_lcd.c.
References ActiveLayer, BSP_LCD_GetXSize(), DrawProp, hLtdcHandler, and LL_FillBuffer().
Referenced by BSP_LCD_DrawRect(), BSP_LCD_FillCircle(), and BSP_LCD_FillEllipse().
BSP_LCD_DrawLine()
void BSP_LCD_DrawLine (uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2)
Draws an uni-line (between two points).
Parameters
x1 Point 1 X position
y1 Point 1 Y position
x2 Point 2 X position
y2 Point 2 Y position
Return values
None
Definition at line 801 of file stm32746g_discovery_lcd.c.
References ABS, ActiveLayer, BSP_LCD_DrawPixel(), and DrawProp.
Referenced by BSP_LCD_DrawPolygon().
BSP_LCD_DrawPixel()
void BSP_LCD_DrawPixel (uint16_t Xpos, uint16_t Ypos, uint32_t RGB_Code)
Draws a pixel on LCD.
Parameters
Xpos X position
Ypos Y position
RGB_Code Pixel color in ARGB mode (8-8-8-8)
Return values
None
Definition at line 1002 of file stm32746g_discovery_lcd.c.
References __IO, ActiveLayer, BSP_LCD_GetXSize(), and hLtdcHandler.
Referenced by BSP_LCD_DrawCircle(), BSP_LCD_DrawEllipse(), and BSP_LCD_DrawLine().
BSP_LCD_DrawPolygon()
void BSP_LCD_DrawPolygon (pPoint Points, uint16_t PointCount)
Draws an poly-line (between many points).
Parameters
Points Pointer to the points array
PointCount Number of points
Return values
None
Definition at line 941 of file stm32746g_discovery_lcd.c.
References BSP_LCD_DrawLine(), Point::X, and Point::Y.
BSP_LCD_DrawRect()
void BSP_LCD_DrawRect (uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Draws a rectangle.
Parameters
Xpos X position
Ypos Y position
Width Rectangle width
Height Rectangle height
Return values
None
Definition at line 876 of file stm32746g_discovery_lcd.c.
References BSP_LCD_DrawHLine(), and BSP_LCD_DrawVLine().
Referenced by Touchscreen_SetHint().
BSP_LCD_DrawVLine()
void BSP_LCD_DrawVLine (uint16_t Xpos, uint16_t Ypos, uint16_t Length)
Draws a vertical line.
Parameters
Xpos X position
Ypos Y position
Length Line length
Return values
None
Definition at line 775 of file stm32746g_discovery_lcd.c.
References ActiveLayer, BSP_LCD_GetXSize(), DrawProp, hLtdcHandler, and LL_FillBuffer().
Referenced by BSP_LCD_DrawRect().
BSP_LCD_FillCircle()
void BSP_LCD_FillCircle (uint16_t Xpos, uint16_t Ypos, uint16_t Radius)
Draws a full circle.
Parameters
Xpos X position
Ypos Y position
Radius Circle radius
Return values
None
Definition at line 1107 of file stm32746g_discovery_lcd.c.
References ActiveLayer, BSP_LCD_DrawCircle(), BSP_LCD_DrawHLine(), BSP_LCD_SetTextColor(), and DrawProp.
Referenced by AUDIO_REC_Process(), Touchscreen_demo(), and Touchscreen_DrawBackground().
BSP_LCD_FillEllipse()
void BSP_LCD_FillEllipse (int Xpos, int Ypos, int XRadius, int YRadius)
Draws a full ellipse.
Parameters
Xpos X position
Ypos Y position
XRadius Ellipse X radius
YRadius Ellipse Y radius
Return values
None
Definition at line 1223 of file stm32746g_discovery_lcd.c.
References BSP_LCD_DrawHLine().
BSP_LCD_FillPolygon()
void BSP_LCD_FillPolygon (pPoint Points, uint16_t PointCount)
Draws a full poly-line (between many points).
Parameters
Points Pointer to the points array
PointCount Number of points
Return values
None
Definition at line 1155 of file stm32746g_discovery_lcd.c.
References FillTriangle(), POLY_X, POLY_Y, Point::X, and Point::Y.
BSP_LCD_FillRect()
void BSP_LCD_FillRect (uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Draws a full rectangle.
Parameters
Xpos X position
Ypos Y position
Width Rectangle width
Height Rectangle height
Return values
None
Definition at line 1080 of file stm32746g_discovery_lcd.c.
References ActiveLayer, BSP_LCD_GetXSize(), BSP_LCD_SetTextColor(), DrawProp, hLtdcHandler, and LL_FillBuffer().
Referenced by AUDIO_REC_Process(), BSP_LCD_ClearStringLine(), and Touchscreen_SetHint().
BSP_LCD_GetBackColor()
uint32_t BSP_LCD_GetBackColor (void)
Gets the LCD background color.
Return values
Used background colour
Definition at line 563 of file stm32746g_discovery_lcd.c.
References ActiveLayer, LCD_DrawPropTypeDef::BackColor, and DrawProp.
BSP_LCD_GetFont()
sFONT * BSP_LCD_GetFont (void)
Gets the LCD text font.
Return values
Used layer font
Definition at line 582 of file stm32746g_discovery_lcd.c.
References ActiveLayer, DrawProp, and LCD_DrawPropTypeDef::pFont.
BSP_LCD_GetTextColor()
uint32_t BSP_LCD_GetTextColor (void)
Gets the LCD text color.
Return values
Used text color.
Definition at line 544 of file stm32746g_discovery_lcd.c.
References ActiveLayer, DrawProp, and LCD_DrawPropTypeDef::TextColor.
BSP_LCD_GetXSize()
uint32_t BSP_LCD_GetXSize (void)
Gets the LCD X size.
Return values
Used LCD X size
Definition at line 232 of file stm32746g_discovery_lcd.c.
References ActiveLayer, and hLtdcHandler.
Referenced by BSP_LCD_Clear(), BSP_LCD_ClearStringLine(), BSP_LCD_DisplayStringAt(), BSP_LCD_DrawBitmap(), BSP_LCD_DrawHLine(), BSP_LCD_DrawPixel(), BSP_LCD_DrawVLine(), BSP_LCD_FillRect(), BSP_LCD_LayerDefaultInit(), BSP_LCD_LayerRgb565Init(), BSP_LCD_ReadPixel(), Touchscreen_demo(), and Touchscreen_SetHint().
BSP_LCD_GetYSize()
uint32_t BSP_LCD_GetYSize (void)
Gets the LCD Y size.
Return values
Used LCD Y size
Definition at line 241 of file stm32746g_discovery_lcd.c.
References ActiveLayer, and hLtdcHandler.
Referenced by BSP_LCD_Clear(), BSP_LCD_LayerDefaultInit(), BSP_LCD_LayerRgb565Init(), Touchscreen_demo(), and Touchscreen_SetHint().
BSP_LCD_Init()
uint8_t BSP_LCD_Init (void)
Initializes the LCD.
Return values
LCD state
Definition at line 149 of file stm32746g_discovery_lcd.c.
References BSP_LCD_ClockConfig(), BSP_LCD_MspInit(), BSP_LCD_SetFont(), BSP_SDRAM_Init(), GPIO_PIN_SET, HAL_GPIO_WritePin(), hLtdcHandler, LCD_BL_CTRL_GPIO_PORT, LCD_BL_CTRL_PIN, LCD_DEFAULT_FONT, LCD_DISP_GPIO_PORT, LCD_DISP_PIN, LCD_OK, LTDC, and NULL.
BSP_LCD_LayerDefaultInit()
void BSP_LCD_LayerDefaultInit (uint16_t LayerIndex, uint32_t FB_Address)
Initializes the LCD layer in ARGB8888 format (32 bits per pixel).
Parameters
LayerIndex Layer foreground or background
FB_Address Layer frame buffer
Return values
None
Definition at line 272 of file stm32746g_discovery_lcd.c.
References LCD_DrawPropTypeDef::BackColor, BSP_LCD_GetXSize(), BSP_LCD_GetYSize(), DrawProp, hLtdcHandler, LCD_COLOR_BLACK, LCD_COLOR_WHITE, LCD_LayerCfgTypeDef, LCD_DrawPropTypeDef::pFont, and LCD_DrawPropTypeDef::TextColor.
BSP_LCD_LayerRgb565Init()
void BSP_LCD_LayerRgb565Init (uint16_t LayerIndex, uint32_t FB_Address)
Initializes the LCD layer in RGB565 format (16 bits per pixel).
Parameters
LayerIndex Layer foreground or background
FB_Address Layer frame buffer
Return values
None
Definition at line 306 of file stm32746g_discovery_lcd.c.
References LCD_DrawPropTypeDef::BackColor, BSP_LCD_GetXSize(), BSP_LCD_GetYSize(), DrawProp, hLtdcHandler, LCD_COLOR_BLACK, LCD_COLOR_WHITE, LCD_LayerCfgTypeDef, LCD_DrawPropTypeDef::pFont, and LCD_DrawPropTypeDef::TextColor.
BSP_LCD_MspDeInit()
void BSP_LCD_MspDeInit (LTDC_HandleTypeDef * hltdc, void * Params)
DeInitializes BSP_LCD MSP.
Parameters
hltdc LTDC handle
Params
Return values
None
Definition at line 1351 of file stm32746g_discovery_lcd.c.
References GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_8, GPIO_PIN_9, GPIOE, GPIOG, GPIOI, GPIOJ, GPIOK, HAL_GPIO_DeInit(), hltdc, and GPIO_InitTypeDef::Pin.
Referenced by BSP_LCD_DeInit().
BSP_LCD_MspInit()
void BSP_LCD_MspInit (LTDC_HandleTypeDef * hltdc, void * Params)
Initializes the LTDC MSP.
Parameters
hltdc LTDC handle
Params
Return values
None
Definition at line 1279 of file stm32746g_discovery_lcd.c.
References __HAL_RCC_GPIOE_CLK_ENABLE, __HAL_RCC_GPIOG_CLK_ENABLE, __HAL_RCC_GPIOI_CLK_ENABLE, GPIO_InitTypeDef::Alternate, GPIO_MODE_AF_PP, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_9, GPIOE, GPIOG, GPIOI, GPIOJ, GPIOK, HAL_GPIO_Init(), LCD_BL_CTRL_GPIO_CLK_ENABLE, LCD_BL_CTRL_GPIO_PORT, LCD_BL_CTRL_PIN, LCD_DISP_GPIO_CLK_ENABLE, LCD_DISP_GPIO_PORT, LCD_DISP_PIN, GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, and GPIO_InitTypeDef::Speed.
Referenced by BSP_LCD_Init().
BSP_LCD_ReadPixel()
uint32_t BSP_LCD_ReadPixel (uint16_t Xpos, uint16_t Ypos)
Reads an LCD pixel.
Parameters
Xpos X position
Ypos Y position
Return values
RGB pixel color
Definition at line 593 of file stm32746g_discovery_lcd.c.
References __IO, ActiveLayer, BSP_LCD_GetXSize(), and hLtdcHandler.
BSP_LCD_Reload()
void BSP_LCD_Reload (uint32_t ReloadType)
Disables the color keying without reloading.
Parameters
ReloadType can be one of the following values
LCD_RELOAD_IMMEDIATE
LCD_RELOAD_VERTICAL_BLANKING
Return values
None
Definition at line 525 of file stm32746g_discovery_lcd.c.
References hLtdcHandler.
BSP_LCD_ResetColorKeying()
void BSP_LCD_ResetColorKeying (uint32_t LayerIndex)
Disables the color keying.
Parameters
LayerIndex Layer foreground or background
Return values
None
Definition at line 501 of file stm32746g_discovery_lcd.c.
References hLtdcHandler.
BSP_LCD_ResetColorKeying_NoReload()
void BSP_LCD_ResetColorKeying_NoReload (uint32_t LayerIndex)
Disables the color keying without reloading.
Parameters
LayerIndex Layer foreground or background
Return values
None
Definition at line 512 of file stm32746g_discovery_lcd.c.
References hLtdcHandler.
BSP_LCD_SelectLayer()
void BSP_LCD_SelectLayer (uint32_t LayerIndex)
Selects the LCD Layer.
Parameters
LayerIndex Layer foreground or background
Return values
None
Definition at line 339 of file stm32746g_discovery_lcd.c.
References ActiveLayer.
BSP_LCD_SetBackColor()
void BSP_LCD_SetBackColor (uint32_t Color)
Sets the LCD background color.
Parameters
Color Layer background color code ARGB(8-8-8-8)
Return values
None
Definition at line 554 of file stm32746g_discovery_lcd.c.
References ActiveLayer, LCD_DrawPropTypeDef::BackColor, and DrawProp.
Referenced by Touchscreen_demo(), and Touchscreen_SetHint().
BSP_LCD_SetColorKeying()
void BSP_LCD_SetColorKeying (uint32_t LayerIndex, uint32_t RGBValue)
Configures and sets the color keying.
Parameters
LayerIndex Layer foreground or background
RGBValue Color reference
Return values
None
Definition at line 476 of file stm32746g_discovery_lcd.c.
References hLtdcHandler.
BSP_LCD_SetColorKeying_NoReload()
void BSP_LCD_SetColorKeying_NoReload (uint32_t LayerIndex, uint32_t RGBValue)
Configures and sets the color keying without reloading.
Parameters
LayerIndex Layer foreground or background
RGBValue Color reference
Return values
None
Definition at line 489 of file stm32746g_discovery_lcd.c.
References hLtdcHandler.
BSP_LCD_SetFont()
void BSP_LCD_SetFont (sFONT * fonts)
Sets the LCD text font.
Parameters
fonts Layer font to be used
Return values
None
Definition at line 573 of file stm32746g_discovery_lcd.c.
References ActiveLayer, DrawProp, and LCD_DrawPropTypeDef::pFont.
Referenced by AUDIO_REC_Process(), BSP_LCD_Init(), and Touchscreen_SetHint().
BSP_LCD_SetLayerAddress()
void BSP_LCD_SetLayerAddress (uint32_t LayerIndex, uint32_t Address)
Sets an LCD layer frame buffer address.
Parameters
LayerIndex Layer foreground or background
Address New LCD frame buffer value
Return values
None
Definition at line 418 of file stm32746g_discovery_lcd.c.
References hLtdcHandler.
BSP_LCD_SetLayerAddress_NoReload()
void BSP_LCD_SetLayerAddress_NoReload (uint32_t LayerIndex, uint32_t Address)
Sets an LCD layer frame buffer address without reloading.
Parameters
LayerIndex Layer foreground or background
Address New LCD frame buffer value
Return values
None
Definition at line 429 of file stm32746g_discovery_lcd.c.
References hLtdcHandler.
BSP_LCD_SetLayerVisible()
void BSP_LCD_SetLayerVisible (uint32_t LayerIndex, FunctionalState State)
Sets an LCD Layer visible.
Parameters
LayerIndex Visible Layer
State New state of the specified layer This parameter can be one of the following values:
ENABLE
DISABLE
Return values
None
Definition at line 353 of file stm32746g_discovery_lcd.c.
References __HAL_LTDC_RELOAD_CONFIG, ENABLE, and hLtdcHandler.
BSP_LCD_SetLayerVisible_NoReload()
void BSP_LCD_SetLayerVisible_NoReload (uint32_t LayerIndex, FunctionalState State)
Sets an LCD Layer visible without reloading.
Parameters
LayerIndex Visible Layer
State New state of the specified layer This parameter can be one of the following values:
ENABLE
DISABLE
Return values
None
Definition at line 375 of file stm32746g_discovery_lcd.c.
References ENABLE, and hLtdcHandler.
BSP_LCD_SetLayerWindow()
void BSP_LCD_SetLayerWindow (uint16_t LayerIndex, uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Sets display window.
Parameters
LayerIndex Layer index
Xpos LCD X position
Ypos LCD Y position
Width LCD window width
Height LCD window height
Return values
None
Definition at line 443 of file stm32746g_discovery_lcd.c.
References hLtdcHandler.
BSP_LCD_SetLayerWindow_NoReload()
void BSP_LCD_SetLayerWindow_NoReload (uint16_t LayerIndex, uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Sets display window without reloading.
Parameters
LayerIndex Layer index
Xpos LCD X position
Ypos LCD Y position
Width LCD window width
Height LCD window height
Return values
None
Definition at line 461 of file stm32746g_discovery_lcd.c.
References hLtdcHandler.
BSP_LCD_SetTextColor()
void BSP_LCD_SetTextColor (uint32_t Color)
Sets the LCD text color.
Parameters
Color Text color code ARGB(8-8-8-8)
Return values
None
Definition at line 535 of file stm32746g_discovery_lcd.c.
References ActiveLayer, DrawProp, and LCD_DrawPropTypeDef::TextColor.
Referenced by AUDIO_REC_Process(), AUDIO_REC_Start(), BSP_LCD_ClearStringLine(), BSP_LCD_FillCircle(), BSP_LCD_FillRect(), Touchscreen_demo(), Touchscreen_DrawBackground(), and Touchscreen_SetHint().
BSP_LCD_SetTransparency()
void BSP_LCD_SetTransparency (uint32_t LayerIndex, uint8_t Transparency)
Configures the transparency.
Parameters
LayerIndex Layer foreground or background.
Transparency Transparency This parameter must be a number between Min_Data = 0x00 and Max_Data = 0xFF
Return values
None
Definition at line 395 of file stm32746g_discovery_lcd.c.
References hLtdcHandler.
BSP_LCD_SetTransparency_NoReload()
void BSP_LCD_SetTransparency_NoReload (uint32_t LayerIndex, uint8_t Transparency)
Configures the transparency without reloading.
Parameters
LayerIndex Layer foreground or background.
Transparency Transparency This parameter must be a number between Min_Data = 0x00 and Max_Data = 0xFF
Return values
None
Definition at line 407 of file stm32746g_discovery_lcd.c.
References hLtdcHandler.
BSP_LCD_SetXSize()
void BSP_LCD_SetXSize (uint32_t imageWidthPixels)
Set the LCD X size.
Parameters
imageWidthPixels : image width in pixels unit
Return values
None
Definition at line 251 of file stm32746g_discovery_lcd.c.
References ActiveLayer, and hLtdcHandler.
BSP_LCD_SetYSize()
void BSP_LCD_SetYSize (uint32_t imageHeightPixels)
Set the LCD Y size.
Parameters
imageHeightPixels : image height in lines unit
Return values
None
Definition at line 261 of file stm32746g_discovery_lcd.c.
References ActiveLayer, and hLtdcHandler.
DrawChar()
static void DrawChar (uint16_t Xpos, uint16_t Ypos, const uint8_t * c) static
Draws a character on LCD.
Parameters
Xpos Line where to display the character shape
Ypos Start column address
c Pointer to the character data
Return values
None
Definition at line 1427 of file stm32746g_discovery_lcd.c.
Referenced by BSP_LCD_DisplayChar().
FillTriangle()
static void FillTriangle (uint16_t x1, uint16_t x2, uint16_t x3, uint16_t y1, uint16_t y2, uint16_t y3) static
Fills a triangle (between 3 points).
Parameters
x1 Point 1 X position
y1 Point 1 Y position
x2 Point 2 X position
y2 Point 2 Y position
x3 Point 3 X position
y3 Point 3 Y position
Return values
None
Definition at line 1486 of file stm32746g_discovery_lcd.c.
Referenced by BSP_LCD_FillPolygon().
LL_ConvertLineToARGB8888()
static void LL_ConvertLineToARGB8888 (void * pSrc, void * pDst, uint32_t xSize, uint32_t ColorMode) static
Converts a line to an ARGB8888 pixel format.
Parameters
pSrc Pointer to source buffer
pDst Output color
xSize Buffer width
ColorMode Input color mode
Return values
None
Definition at line 1602 of file stm32746g_discovery_lcd.c.
Referenced by BSP_LCD_DrawBitmap().
LL_FillBuffer()
static void LL_FillBuffer (uint32_t LayerIndex, void * pDst, uint32_t xSize, uint32_t ySize, uint32_t OffLine, uint32_t ColorIndex) static
Fills a buffer.
Parameters
LayerIndex Layer index
pDst Pointer to destination buffer
xSize Buffer width
ySize Buffer height
OffLine Offset
ColorIndex Color index
Return values
None
Definition at line 1564 of file stm32746g_discovery_lcd.c.
Referenced by BSP_LCD_Clear(), BSP_LCD_DrawHLine(), BSP_LCD_DrawVLine(), and BSP_LCD_FillRect().