Sensorclient: STM32746G_DISCOVERY_AUDIO Out Private Functions
STM32746G_DISCOVERY_AUDIO Out Private Functions
STM32F7xx_HAL_Examples » BSP » STM32746G_DISCOVERY » STM32746G_DISCOVERY AUDIO
Functions
uint8_t BSP_AUDIO_IN_Init (uint32_t AudioFreq, uint32_t BitRes, uint32_t ChnlNbr)
Initializes wave recording.
uint8_t BSP_AUDIO_IN_InitEx (uint16_t InputDevice, uint32_t AudioFreq, uint32_t BitRes, uint32_t ChnlNbr)
Initializes wave recording.
uint8_t BSP_AUDIO_IN_OUT_Init (uint16_t InputDevice, uint16_t OutputDevice, uint32_t AudioFreq, uint32_t BitRes, uint32_t ChnlNbr)
Initializes wave recording and playback in parallel.
uint8_t BSP_AUDIO_IN_Record (uint16_t *pbuf, uint32_t size)
Starts audio recording.
uint8_t BSP_AUDIO_IN_Stop (uint32_t Option)
Stops audio recording.
uint8_t BSP_AUDIO_IN_Pause (void)
Pauses the audio file stream.
uint8_t BSP_AUDIO_IN_Resume (void)
Resumes the audio file stream.
uint8_t BSP_AUDIO_IN_SetVolume (uint8_t Volume)
Controls the audio in volume level.
void BSP_AUDIO_IN_DeInit (void)
Deinit the audio IN peripherals.
void HAL_SAI_RxCpltCallback (SAI_HandleTypeDef *hsai)
Rx Transfer completed callbacks.
void HAL_SAI_RxHalfCpltCallback (SAI_HandleTypeDef *hsai)
Rx Half Transfer completed callbacks.
__weak void BSP_AUDIO_IN_TransferComplete_CallBack (void)
User callback when record buffer is filled.
__weak void BSP_AUDIO_IN_HalfTransfer_CallBack (void)
Manages the DMA Half Transfer complete event.
__weak void BSP_AUDIO_IN_Error_CallBack (void)
Audio IN Error callback function.
__weak void BSP_AUDIO_IN_MspInit (SAI_HandleTypeDef *hsai, void *Params)
Initializes BSP_AUDIO_IN MSP.
__weak void BSP_AUDIO_IN_MspDeInit (SAI_HandleTypeDef *hsai, void *Params)
DeInitializes BSP_AUDIO_IN MSP.
static void SAIx_In_Init (uint32_t SaiOutMode, uint32_t SlotActive, uint32_t AudioFreq)
Initializes the input Audio Codec audio interface (SAI).
static void SAIx_In_DeInit (void)
Deinitializes the output Audio Codec audio interface (SAI).
Detailed Description
Function Documentation
BSP_AUDIO_IN_DeInit()
void BSP_AUDIO_IN_DeInit (void)
Deinit the audio IN peripherals.
Return values
None
Definition at line 1048 of file stm32746g_discovery_audio.c.
BSP_AUDIO_IN_Error_CallBack()
__weak void BSP_AUDIO_IN_Error_CallBack (void)
Audio IN Error callback function.
Return values
None
Definition at line 1104 of file stm32746g_discovery_audio.c.
Referenced by HAL_SAI_ErrorCallback().
BSP_AUDIO_IN_HalfTransfer_CallBack()
__weak void BSP_AUDIO_IN_HalfTransfer_CallBack (void)
Manages the DMA Half Transfer complete event.
Manages the DMA Half Transfer complete interrupt.
Return values
None
Definition at line 1093 of file stm32746g_discovery_audio.c.
References BufferCtl.
BSP_AUDIO_IN_Init()
uint8_t BSP_AUDIO_IN_Init (uint32_t AudioFreq, uint32_t BitRes, uint32_t ChnlNbr)
Initializes wave recording.
Parameters
AudioFreq Audio frequency to be configured for the SAI peripheral.
BitRes Audio frequency to be configured.
ChnlNbr Channel number.
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 780 of file stm32746g_discovery_audio.c.
Referenced by AUDIO_REC_Start().
BSP_AUDIO_IN_InitEx()
uint8_t BSP_AUDIO_IN_InitEx (uint16_t InputDevice, uint32_t AudioFreq, uint32_t BitRes, uint32_t ChnlNbr)
Initializes wave recording.
Parameters
InputDevice INPUT_DEVICE_DIGITAL_MICROPHONE_2 or INPUT_DEVICE_INPUT_LINE_1
AudioFreq Audio frequency to be configured for the SAI peripheral.
BitRes Audio frequency to be configured.
ChnlNbr Channel number.
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 793 of file stm32746g_discovery_audio.c.
BSP_AUDIO_IN_MspDeInit()
__weak void BSP_AUDIO_IN_MspDeInit (SAI_HandleTypeDef * hsai, void * Params)
DeInitializes BSP_AUDIO_IN MSP.
Parameters
hsai SAI handle
Params
Return values
None
Definition at line 1189 of file stm32746g_discovery_audio.c.
BSP_AUDIO_IN_MspInit()
__weak void BSP_AUDIO_IN_MspInit (SAI_HandleTypeDef * hsai, void * Params)
Initializes BSP_AUDIO_IN MSP.
Parameters
hsai SAI handle
Params
Return values
None
Definition at line 1116 of file stm32746g_discovery_audio.c.
BSP_AUDIO_IN_OUT_Init()
uint8_t BSP_AUDIO_IN_OUT_Init (uint16_t InputDevice, uint16_t OutputDevice, uint32_t AudioFreq, uint32_t BitRes, uint32_t ChnlNbr)
Initializes wave recording and playback in parallel.
Parameters
InputDevice INPUT_DEVICE_DIGITAL_MICROPHONE_2
OutputDevice OUTPUT_DEVICE_SPEAKER, OUTPUT_DEVICE_HEADPHONE, or OUTPUT_DEVICE_BOTH.
AudioFreq Audio frequency to be configured for the SAI peripheral.
BitRes Audio frequency to be configured.
ChnlNbr Channel number.
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 871 of file stm32746g_discovery_audio.c.
BSP_AUDIO_IN_Pause()
uint8_t BSP_AUDIO_IN_Pause (void)
Pauses the audio file stream.
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 1003 of file stm32746g_discovery_audio.c.
Referenced by AUDIO_REC_Process().
BSP_AUDIO_IN_Record()
uint8_t BSP_AUDIO_IN_Record (uint16_t * pbuf, uint32_t size)
Starts audio recording.
Parameters
pbuf Main buffer pointer for the recorded data storing
size size of the recorded buffer in number of elements (typically number of half-words) Be careful that it is not the same unit than BSP_AUDIO_OUT_Play function
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 955 of file stm32746g_discovery_audio.c.
Referenced by AUDIO_REC_Start().
BSP_AUDIO_IN_Resume()
uint8_t BSP_AUDIO_IN_Resume (void)
Resumes the audio file stream.
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 1015 of file stm32746g_discovery_audio.c.
Referenced by AUDIO_REC_Process().
BSP_AUDIO_IN_SetVolume()
uint8_t BSP_AUDIO_IN_SetVolume (uint8_t Volume)
Controls the audio in volume level.
Parameters
Volume Volume level in range 0(Mute)..80(+0dB)..100(+17.625dB)
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 1028 of file stm32746g_discovery_audio.c.
Referenced by AUDIO_REC_Process().
BSP_AUDIO_IN_Stop()
uint8_t BSP_AUDIO_IN_Stop (uint32_t Option)
Stops audio recording.
Parameters
Option could be one of the following parameters
CODEC_PDWN_SW: for software power off (by writing registers). Then no need to reconfigure the Codec after power on.
CODEC_PDWN_HW: completely shut down the codec (physically). Then need to reconfigure the Codec after power on.
Return values
AUDIO_OK if correct communication, else wrong communication
Definition at line 977 of file stm32746g_discovery_audio.c.
Referenced by AUDIO_REC_Process().
BSP_AUDIO_IN_TransferComplete_CallBack()
__weak void BSP_AUDIO_IN_TransferComplete_CallBack (void)
User callback when record buffer is filled.
Calculates the remaining file size and new position of the pointer.
Return values
None
Definition at line 1082 of file stm32746g_discovery_audio.c.
References BufferCtl.
HAL_SAI_RxCpltCallback()
void HAL_SAI_RxCpltCallback (SAI_HandleTypeDef * hsai)
Rx Transfer completed callbacks.
Parameters
hsai SAI handle
Return values
None
Definition at line 1060 of file stm32746g_discovery_audio.c.
HAL_SAI_RxHalfCpltCallback()
void HAL_SAI_RxHalfCpltCallback (SAI_HandleTypeDef * hsai)
Rx Half Transfer completed callbacks.
Parameters
hsai SAI handle
Return values
None
Definition at line 1071 of file stm32746g_discovery_audio.c.
SAIx_In_DeInit()
static void SAIx_In_DeInit (void) static
Deinitializes the output Audio Codec audio interface (SAI).
Return values
None
Definition at line 1335 of file stm32746g_discovery_audio.c.
SAIx_In_Init()
static void SAIx_In_Init (uint32_t SaiOutMode, uint32_t SlotActive, uint32_t AudioFreq) static
Initializes the input Audio Codec audio interface (SAI).
Parameters
SaiOutMode SAI_MODEMASTER_TX (for record and playback in parallel) or SAI_MODEMASTER_RX (for record only).
SlotActive CODEC_AUDIOFRAME_SLOT_02 or CODEC_AUDIOFRAME_SLOT_13
AudioFreq Audio frequency to be configured for the SAI peripheral.
Return values
None
Definition at line 1230 of file stm32746g_discovery_audio.c.