Sensorclient: SDRAM_Exported_Functions_Group1
SDRAM_Exported_Functions_Group1
STM32F7xx_HAL_Driver » SDRAM » SDRAM Exported Functions
Functions
HAL_StatusTypeDef HAL_SDRAM_Init (SDRAM_HandleTypeDef *hsdram, FMC_SDRAM_TimingTypeDef *Timing)
HAL_StatusTypeDef HAL_SDRAM_DeInit (SDRAM_HandleTypeDef *hsdram)
void HAL_SDRAM_MspInit (SDRAM_HandleTypeDef *hsdram)
void HAL_SDRAM_MspDeInit (SDRAM_HandleTypeDef *hsdram)
void HAL_SDRAM_IRQHandler (SDRAM_HandleTypeDef *hsdram)
void HAL_SDRAM_RefreshErrorCallback (SDRAM_HandleTypeDef *hsdram)
void HAL_SDRAM_DMA_XferCpltCallback (DMA_HandleTypeDef *hdma)
void HAL_SDRAM_DMA_XferErrorCallback (DMA_HandleTypeDef *hdma)
Detailed Description
Function Documentation
HAL_SDRAM_DeInit()
HAL_StatusTypeDef HAL_SDRAM_DeInit (SDRAM_HandleTypeDef * hsdram)
Referenced by BSP_SDRAM_DeInit().
HAL_SDRAM_DMA_XferCpltCallback()
void HAL_SDRAM_DMA_XferCpltCallback (DMA_HandleTypeDef * hdma)
HAL_SDRAM_DMA_XferErrorCallback()
void HAL_SDRAM_DMA_XferErrorCallback (DMA_HandleTypeDef * hdma)
HAL_SDRAM_Init()
HAL_StatusTypeDef HAL_SDRAM_Init (SDRAM_HandleTypeDef * hsdram, FMC_SDRAM_TimingTypeDef * Timing)
Referenced by BSP_SDRAM_Init(), and MX_FMC_Init().
HAL_SDRAM_IRQHandler()
void HAL_SDRAM_IRQHandler (SDRAM_HandleTypeDef * hsdram)
HAL_SDRAM_MspDeInit()
void HAL_SDRAM_MspDeInit (SDRAM_HandleTypeDef * hsdram)
Definition at line 342 of file fmc.c.
References HAL_FMC_MspDeInit().
HAL_SDRAM_MspInit()
void HAL_SDRAM_MspInit (SDRAM_HandleTypeDef * hsdram)
Definition at line 229 of file fmc.c.
References HAL_FMC_MspInit().
HAL_SDRAM_RefreshErrorCallback()
void HAL_SDRAM_RefreshErrorCallback (SDRAM_HandleTypeDef * hsdram)