Sensorclient: STM32746G_DISCOVERY_SD Exported Functions
STM32746G_DISCOVERY_SD Exported Functions
STM32F7xx_HAL_Examples » BSP » STM32746G_DISCOVERY » STM32746G_DISCOVERY_SD
Functions
uint8_t BSP_SD_Init (void)
Initializes the SD card device.
uint8_t BSP_SD_DeInit (void)
DeInitializes the SD card device.
uint8_t BSP_SD_ITConfig (void)
Configures Interrupt mode for SD detection pin.
uint8_t BSP_SD_IsDetected (void)
Detects if SD card is correctly plugged in the memory slot or not.
uint8_t BSP_SD_ReadBlocks (uint32_t *pData, uint32_t ReadAddr, uint32_t NumOfBlocks, uint32_t Timeout)
Reads block(s) from a specified address in an SD card, in polling mode.
uint8_t BSP_SD_WriteBlocks (uint32_t *pData, uint32_t WriteAddr, uint32_t NumOfBlocks, uint32_t Timeout)
Writes block(s) to a specified address in an SD card, in polling mode.
uint8_t BSP_SD_ReadBlocks_DMA (uint32_t *pData, uint32_t ReadAddr, uint32_t NumOfBlocks)
Reads block(s) from a specified address in an SD card, in DMA mode.
uint8_t BSP_SD_WriteBlocks_DMA (uint32_t *pData, uint32_t WriteAddr, uint32_t NumOfBlocks)
Writes block(s) to a specified address in an SD card, in DMA mode.
uint8_t BSP_SD_Erase (uint32_t StartAddr, uint32_t EndAddr)
Erases the specified memory area of the given SD card.
__weak void BSP_SD_MspInit (SD_HandleTypeDef *hsd, void *Params)
Initializes the SD MSP.
__weak void BSP_SD_Detect_MspInit (SD_HandleTypeDef *hsd, void *Params)
Initializes the SD Detect pin MSP.
__weak void BSP_SD_MspDeInit (SD_HandleTypeDef *hsd, void *Params)
DeInitializes the SD MSP.
uint8_t BSP_SD_GetCardState (void)
Gets the current SD card data status.
void BSP_SD_GetCardInfo (HAL_SD_CardInfoTypeDef *CardInfo)
Get SD information about specific SD card.
void HAL_SD_AbortCallback (SD_HandleTypeDef *hsd)
SD Abort callbacks.
void HAL_SD_TxCpltCallback (SD_HandleTypeDef *hsd)
Tx Transfer completed callbacks.
void HAL_SD_RxCpltCallback (SD_HandleTypeDef *hsd)
Rx Transfer completed callbacks.
__weak void BSP_SD_AbortCallback (void)
BSP SD Abort callbacks.
__weak void BSP_SD_WriteCpltCallback (void)
BSP Tx Transfer completed callbacks.
__weak void BSP_SD_ReadCpltCallback (void)
BSP Rx Transfer completed callbacks.
Detailed Description
Function Documentation
BSP_SD_AbortCallback()
void BSP_SD_AbortCallback (void)
BSP SD Abort callbacks.
Return values
None
Definition at line 552 of file stm32746g_discovery_sd.c.
Referenced by HAL_SD_AbortCallback().
BSP_SD_DeInit()
uint8_t BSP_SD_DeInit (void)
DeInitializes the SD card device.
Return values
SD status
Definition at line 183 of file stm32746g_discovery_sd.c.
References BSP_SD_MspDeInit(), HAL_OK, MSD_ERROR, MSD_OK, NULL, SDMMC1, and uSdHandle.
BSP_SD_Detect_MspInit()
void BSP_SD_Detect_MspInit (SD_HandleTypeDef * hsd, void * Params)
Initializes the SD Detect pin MSP.
Parameters
hsd SD handle
Params
Return values
None
Definition at line 444 of file stm32746g_discovery_sd.c.
References GPIO_MODE_INPUT, GPIO_PULLUP, HAL_GPIO_Init(), GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, SD_DETECT_GPIO_CLK_ENABLE, SD_DETECT_GPIO_PORT, SD_DETECT_PIN, and GPIO_InitTypeDef::Speed.
Referenced by BSP_SD_Init().
BSP_SD_Erase()
uint8_t BSP_SD_Erase (uint32_t StartAddr, uint32_t EndAddr)
Erases the specified memory area of the given SD card.
Parameters
StartAddr Start byte address
EndAddr End byte address
Return values
SD status
Definition at line 327 of file stm32746g_discovery_sd.c.
References HAL_OK, MSD_ERROR, MSD_OK, and uSdHandle.
BSP_SD_GetCardInfo()
void BSP_SD_GetCardInfo (HAL_SD_CardInfoTypeDef * CardInfo)
Get SD information about specific SD card.
Parameters
CardInfo Pointer to HAL_SD_CardInfoTypedef structure
Return values
None
Definition at line 512 of file stm32746g_discovery_sd.c.
References uSdHandle.
BSP_SD_GetCardState()
uint8_t BSP_SD_GetCardState (void)
Gets the current SD card data status.
Return values
Data transfer state. This value can be one of the following values:
SD_TRANSFER_OK: No data transfer is acting
SD_TRANSFER_BUSY: Data transfer is acting
Definition at line 501 of file stm32746g_discovery_sd.c.
References SD_TRANSFER_BUSY, SD_TRANSFER_OK, and uSdHandle.
BSP_SD_Init()
uint8_t BSP_SD_Init (void)
Initializes the SD card device.
Return values
SD status
Definition at line 132 of file stm32746g_discovery_sd.c.
References BSP_SD_Detect_MspInit(), BSP_SD_IsDetected(), BSP_SD_MspInit(), HAL_OK, MSD_ERROR, MSD_ERROR_SD_NOT_PRESENT, MSD_OK, NULL, SD_PRESENT, SDMMC1, and uSdHandle.
BSP_SD_IsDetected()
uint8_t BSP_SD_IsDetected (void)
Detects if SD card is correctly plugged in the memory slot or not.
Return values
Returns if SD is detected or not
Definition at line 228 of file stm32746g_discovery_sd.c.
References __IO, GPIO_PIN_SET, HAL_GPIO_ReadPin(), SD_DETECT_GPIO_PORT, SD_DETECT_PIN, SD_NOT_PRESENT, and SD_PRESENT.
Referenced by BSP_SD_Init().
BSP_SD_ITConfig()
uint8_t BSP_SD_ITConfig (void)
Configures Interrupt mode for SD detection pin.
Return values
Returns MSD_OK
Definition at line 206 of file stm32746g_discovery_sd.c.
References GPIO_MODE_IT_RISING_FALLING, GPIO_PULLUP, HAL_GPIO_Init(), HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), GPIO_InitTypeDef::Mode, MSD_OK, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, SD_DETECT_EXTI_IRQn, SD_DETECT_GPIO_PORT, SD_DETECT_PIN, and GPIO_InitTypeDef::Speed.
BSP_SD_MspDeInit()
void BSP_SD_MspDeInit (SD_HandleTypeDef * hsd, void * Params)
DeInitializes the SD MSP.
Parameters
hsd SD handle
Params
Return values
None
Definition at line 464 of file stm32746g_discovery_sd.c.
References __HAL_RCC_SDMMC1_CLK_DISABLE, HAL_DMA_DeInit(), HAL_NVIC_DisableIRQ(), __DMA_HandleTypeDef::Instance, SD_DMAx_Rx_IRQn, SD_DMAx_Rx_STREAM, SD_DMAx_Tx_IRQn, SD_DMAx_Tx_STREAM, and SDMMC1_IRQn.
Referenced by BSP_SD_DeInit().
BSP_SD_MspInit()
void BSP_SD_MspInit (SD_HandleTypeDef * hsd, void * Params)
Initializes the SD MSP.
Parameters
hsd SD handle
Params
Return values
None
Definition at line 345 of file stm32746g_discovery_sd.c.
References __DMAx_TxRx_CLK_ENABLE, __HAL_LINKDMA, __HAL_RCC_GPIOC_CLK_ENABLE, __HAL_RCC_GPIOD_CLK_ENABLE, __HAL_RCC_SDMMC1_CLK_ENABLE, GPIO_InitTypeDef::Alternate, DMA_InitTypeDef::Channel, DMA_InitTypeDef::Direction, DMA_FIFO_THRESHOLD_FULL, DMA_FIFOMODE_ENABLE, DMA_MBURST_INC4, DMA_MDATAALIGN_WORD, DMA_MEMORY_TO_PERIPH, DMA_MINC_ENABLE, DMA_PBURST_INC4, DMA_PDATAALIGN_WORD, DMA_PERIPH_TO_MEMORY, DMA_PFCTRL, DMA_PINC_DISABLE, DMA_PRIORITY_VERY_HIGH, DMA_InitTypeDef::FIFOMode, DMA_InitTypeDef::FIFOThreshold, GPIO_MODE_AF_PP, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_2, GPIO_PIN_8, GPIO_PIN_9, GPIO_PULLUP, GPIOC, GPIOD, HAL_DMA_DeInit(), HAL_DMA_Init(), HAL_GPIO_Init(), HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), __DMA_HandleTypeDef::Init, __DMA_HandleTypeDef::Instance, DMA_InitTypeDef::MemBurst, DMA_InitTypeDef::MemDataAlignment, DMA_InitTypeDef::MemInc, GPIO_InitTypeDef::Mode, DMA_InitTypeDef::Mode, DMA_InitTypeDef::PeriphBurst, DMA_InitTypeDef::PeriphDataAlignment, DMA_InitTypeDef::PeriphInc, GPIO_InitTypeDef::Pin, DMA_InitTypeDef::Priority, GPIO_InitTypeDef::Pull, SD_DMAx_Rx_CHANNEL, SD_DMAx_Rx_IRQn, SD_DMAx_Rx_STREAM, SD_DMAx_Tx_CHANNEL, SD_DMAx_Tx_IRQn, SD_DMAx_Tx_STREAM, SDMMC1_IRQn, and GPIO_InitTypeDef::Speed.
Referenced by BSP_SD_Init().
BSP_SD_ReadBlocks()
uint8_t BSP_SD_ReadBlocks (uint32_t * pData, uint32_t ReadAddr, uint32_t NumOfBlocks, uint32_t Timeout)
Reads block(s) from a specified address in an SD card, in polling mode.
Parameters
pData Pointer to the buffer that will contain the data to transmit
ReadAddr Address from where data is to be read
NumOfBlocks Number of SD blocks to read
Timeout Timeout for read operation
Return values
SD status
Definition at line 249 of file stm32746g_discovery_sd.c.
References HAL_OK, MSD_ERROR, MSD_OK, and uSdHandle.
BSP_SD_ReadBlocks_DMA()
uint8_t BSP_SD_ReadBlocks_DMA (uint32_t * pData, uint32_t ReadAddr, uint32_t NumOfBlocks)
Reads block(s) from a specified address in an SD card, in DMA mode.
Parameters
pData Pointer to the buffer that will contain the data to transmit
ReadAddr Address from where data is to be read
NumOfBlocks Number of SD blocks to read
Return values
SD status
Definition at line 288 of file stm32746g_discovery_sd.c.
References HAL_OK, MSD_ERROR, MSD_OK, and uSdHandle.
BSP_SD_ReadCpltCallback()
void BSP_SD_ReadCpltCallback (void)
BSP Rx Transfer completed callbacks.
Return values
None
Definition at line 570 of file stm32746g_discovery_sd.c.
Referenced by HAL_SD_RxCpltCallback().
BSP_SD_WriteBlocks()
uint8_t BSP_SD_WriteBlocks (uint32_t * pData, uint32_t WriteAddr, uint32_t NumOfBlocks, uint32_t Timeout)
Writes block(s) to a specified address in an SD card, in polling mode.
Parameters
pData Pointer to the buffer that will contain the data to transmit
WriteAddr Address from where data is to be written
NumOfBlocks Number of SD blocks to write
Timeout Timeout for write operation
Return values
SD status
Definition at line 269 of file stm32746g_discovery_sd.c.
References HAL_OK, MSD_ERROR, MSD_OK, and uSdHandle.
BSP_SD_WriteBlocks_DMA()
uint8_t BSP_SD_WriteBlocks_DMA (uint32_t * pData, uint32_t WriteAddr, uint32_t NumOfBlocks)
Writes block(s) to a specified address in an SD card, in DMA mode.
Parameters
pData Pointer to the buffer that will contain the data to transmit
WriteAddr Address from where data is to be written
NumOfBlocks Number of SD blocks to write
Return values
SD status
Definition at line 308 of file stm32746g_discovery_sd.c.
References HAL_OK, MSD_ERROR, MSD_OK, and uSdHandle.
BSP_SD_WriteCpltCallback()
void BSP_SD_WriteCpltCallback (void)
BSP Tx Transfer completed callbacks.
Return values
None
Definition at line 561 of file stm32746g_discovery_sd.c.
Referenced by HAL_SD_TxCpltCallback().
HAL_SD_AbortCallback()
void HAL_SD_AbortCallback (SD_HandleTypeDef * hsd)
SD Abort callbacks.
Parameters
hsd SD handle
Return values
None
Definition at line 523 of file stm32746g_discovery_sd.c.
References BSP_SD_AbortCallback().
HAL_SD_RxCpltCallback()
void HAL_SD_RxCpltCallback (SD_HandleTypeDef * hsd)
Rx Transfer completed callbacks.
Parameters
hsd SD handle
Return values
None
Definition at line 543 of file stm32746g_discovery_sd.c.
References BSP_SD_ReadCpltCallback().
HAL_SD_TxCpltCallback()
void HAL_SD_TxCpltCallback (SD_HandleTypeDef * hsd)
Tx Transfer completed callbacks.
Parameters
hsd SD handle
Return values
None
Definition at line 533 of file stm32746g_discovery_sd.c.
References BSP_SD_WriteCpltCallback().