Sensorclient: STM32746G_DISCOVERY_TS Exported Functions
STM32746G_DISCOVERY_TS Exported Functions
STM32F7xx_HAL_Examples » BSP » STM32746G_DISCOVERY » STM32746G_DISCOVERY_TS
Modules
TS Private Functions
Functions
uint8_t BSP_TS_Init (uint16_t ts_SizeX, uint16_t ts_SizeY)
Initializes and configures the touch screen functionalities and configures all necessary hardware resources (GPIOs, I2C, clocks..).
uint8_t BSP_TS_DeInit (void)
DeInitializes the TouchScreen.
uint8_t BSP_TS_ITConfig (void)
Configures and enables the touch screen interrupts.
uint8_t BSP_TS_ITGetStatus (void)
Gets the touch screen interrupt status.
uint8_t BSP_TS_GetState (TS_StateTypeDef *TS_State)
Returns status and positions of the touch screen.
void BSP_TS_ITClear (void)
Clears all touch screen interrupts.
uint8_t BSP_TS_ResetTouchData (TS_StateTypeDef *TS_State)
Function used to reset all touch data before a new acquisition of touch information.
Detailed Description
Function Documentation
BSP_TS_DeInit()
uint8_t BSP_TS_DeInit (void)
DeInitializes the TouchScreen.
Return values
TS state
Definition at line 161 of file stm32746g_discovery_ts.c.
References TS_OK.
BSP_TS_GetState()
uint8_t BSP_TS_GetState (TS_StateTypeDef * TS_State)
Returns status and positions of the touch screen.
Parameters
TS_State Pointer to touch screen current state structure
Return values
TS_OK if all initializations are OK. Other value if error.
Definition at line 207 of file stm32746g_discovery_ts.c.
References I2cAddress, TOUCH_EVENT_CONTACT, TOUCH_EVENT_LIFT_UP, TOUCH_EVENT_NO_EVT, TOUCH_EVENT_PRESS_DOWN, TS_StateTypeDef::touchDetected, TS_StateTypeDef::touchX, TS_StateTypeDef::touchY, TS_ERROR, TS_MAX_NB_TOUCH, TS_OK, TS_State, TS_SWAP_NONE, TS_SWAP_X, TS_SWAP_XY, TS_SWAP_Y, tsDriver, tsOrientation, tsXBoundary, and tsYBoundary.
Referenced by AUDIO_REC_Process(), and Touchscreen_demo().
BSP_TS_Init()
uint8_t BSP_TS_Init (uint16_t ts_SizeX, uint16_t ts_SizeY)
Initializes and configures the touch screen functionalities and configures all necessary hardware resources (GPIOs, I2C, clocks..).
Parameters
ts_SizeX Maximum X size of the TS area on LCD
ts_SizeY Maximum Y size of the TS area on LCD
Return values
TS_OK if all initializations are OK. Other value if error.
Definition at line 131 of file stm32746g_discovery_ts.c.
References I2cAddress, TS_DEVICE_NOT_FOUND, TS_I2C_ADDRESS, TS_OK, TS_SWAP_XY, tsDriver, tsOrientation, tsXBoundary, and tsYBoundary.
Referenced by Touchscreen_demo().
BSP_TS_ITClear()
void BSP_TS_ITClear (void)
Clears all touch screen interrupts.
Definition at line 371 of file stm32746g_discovery_ts.c.
References I2cAddress, and tsDriver.
BSP_TS_ITConfig()
uint8_t BSP_TS_ITConfig (void)
Configures and enables the touch screen interrupts.
Return values
TS_OK if all initializations are OK. Other value if error.
Definition at line 171 of file stm32746g_discovery_ts.c.
References GPIO_MODE_IT_RISING, GPIO_NOPULL, HAL_GPIO_Init(), HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), I2cAddress, GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, GPIO_InitTypeDef::Speed, TS_INT_EXTI_IRQn, TS_INT_GPIO_PORT, TS_INT_PIN, TS_OK, and tsDriver.
BSP_TS_ITGetStatus()
uint8_t BSP_TS_ITGetStatus (void)
Gets the touch screen interrupt status.
Return values
TS_OK if all initializations are OK. Other value if error.
Definition at line 196 of file stm32746g_discovery_ts.c.
References I2cAddress, and tsDriver.
BSP_TS_ResetTouchData()
uint8_t BSP_TS_ResetTouchData (TS_StateTypeDef * TS_State)
Function used to reset all touch data before a new acquisition of touch information.
Parameters
TS_State Pointer to touch screen current state structure
Return values
TS_OK if OK, TE_ERROR if problem found.
Definition at line 389 of file stm32746g_discovery_ts.c.
References GEST_ID_NO_GESTURE, NULL, TOUCH_EVENT_NO_EVT, TS_StateTypeDef::touchDetected, TS_StateTypeDef::touchX, TS_StateTypeDef::touchY, TS_ERROR, TS_MAX_NB_TOUCH, TS_OK, and TS_State.