Sensorclient: Core/Src/ltdc.c File Reference
ltdc.c File Reference
This file provides code for the configuration of the LTDC instances.
#include "ltdc.h"
Functions
void MX_LTDC_Init (void)
void HAL_LTDC_MspInit (LTDC_HandleTypeDef *ltdcHandle)
void HAL_LTDC_MspDeInit (LTDC_HandleTypeDef *ltdcHandle)
Variables
LTDC_HandleTypeDef hltdc
Detailed Description
This file provides code for the configuration of the LTDC instances.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file ltdc.c.
Function Documentation
HAL_LTDC_MspDeInit()
void HAL_LTDC_MspDeInit (LTDC_HandleTypeDef * ltdcHandle)
LTDC GPIO Configuration PB8 ---—> LTDC_B6 PB9 ---—> LTDC_B7 PJ13 ---—> LTDC_B1 PJ12 ---—> LTDC_B0 PC10 ---—> LTDC_R2 PA12 ---—> LTDC_R5 PK7 ---—> LTDC_DE PG12 ---—> LTDC_B4 PG10 ---—> LTDC_G3 PJ14 ---—> LTDC_B2 PD3 ---—> LTDC_G7 PA11 ---—> LTDC_R4 PK4 ---—> LTDC_B5 PJ15 ---—> LTDC_B3 PI12 ---—> LTDC_HSYNC PK1 ---—> LTDC_G6 PA8 ---—> LTDC_R6 PI13 ---—> LTDC_VSYNC PI15 ---—> LTDC_R0 PJ11 ---—> LTDC_G4 PK0 ---—> LTDC_G5 PI14 ---—> LTDC_CLK PJ8 ---—> LTDC_G1 PJ7 ---—> LTDC_G0 PJ9 ---—> LTDC_G2 PG6 ---—> LTDC_R7 PJ2 ---—> LTDC_R3 PJ0 ---—> LTDC_R1
Definition at line 233 of file ltdc.c.
References GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_8, GPIO_PIN_9, GPIOA, GPIOB, GPIOC, GPIOD, GPIOG, GPIOI, GPIOJ, GPIOK, HAL_GPIO_DeInit(), HAL_NVIC_DisableIRQ(), LTDC, LTDC_ER_IRQn, and LTDC_IRQn.
HAL_LTDC_MspInit()
void HAL_LTDC_MspInit (LTDC_HandleTypeDef * ltdcHandle)
LTDC GPIO Configuration PB8 ---—> LTDC_B6 PB9 ---—> LTDC_B7 PJ13 ---—> LTDC_B1 PJ12 ---—> LTDC_B0 PC10 ---—> LTDC_R2 PA12 ---—> LTDC_R5 PK7 ---—> LTDC_DE PG12 ---—> LTDC_B4 PG10 ---—> LTDC_G3 PJ14 ---—> LTDC_B2 PD3 ---—> LTDC_G7 PA11 ---—> LTDC_R4 PK4 ---—> LTDC_B5 PJ15 ---—> LTDC_B3 PI12 ---—> LTDC_HSYNC PK1 ---—> LTDC_G6 PA8 ---—> LTDC_R6 PI13 ---—> LTDC_VSYNC PI15 ---—> LTDC_R0 PJ11 ---—> LTDC_G4 PK0 ---—> LTDC_G5 PI14 ---—> LTDC_CLK PJ8 ---—> LTDC_G1 PJ7 ---—> LTDC_G0 PJ9 ---—> LTDC_G2 PG6 ---—> LTDC_R7 PJ2 ---—> LTDC_R3 PJ0 ---—> LTDC_R1
Definition at line 107 of file ltdc.c.
References __HAL_RCC_GPIOA_CLK_ENABLE, __HAL_RCC_GPIOB_CLK_ENABLE, __HAL_RCC_GPIOC_CLK_ENABLE, __HAL_RCC_GPIOD_CLK_ENABLE, __HAL_RCC_GPIOG_CLK_ENABLE, __HAL_RCC_GPIOI_CLK_ENABLE, GPIO_InitTypeDef::Alternate, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_6, GPIO_PIN_7, GPIO_PIN_8, GPIO_PIN_9, GPIO_SPEED_FREQ_LOW, GPIOA, GPIOB, GPIOC, GPIOD, GPIOG, GPIOI, GPIOJ, GPIOK, HAL_GPIO_Init(), HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), LTDC, LTDC_ER_IRQn, LTDC_IRQn, GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, and GPIO_InitTypeDef::Speed.
MX_LTDC_Init()
void MX_LTDC_Init (void)
Definition at line 30 of file ltdc.c.
References Error_Handler(), HAL_OK, hltdc, and LTDC.
Referenced by main().
Variable Documentation
hltdc
LTDC_HandleTypeDef hltdc
Definition at line 27 of file ltdc.c.
Referenced by BSP_LCD_MspDeInit(), LTDC_ER_IRQHandler(), LTDC_IRQHandler(), and MX_LTDC_Init().