Sensorclient: LWIP/App/lwip.h File Reference
lwip.h File Reference
#include "lwip/opt.h"
#include "lwip/mem.h"
#include "lwip/memp.h"
#include "netif/etharp.h"
#include "lwip/dhcp.h"
#include "lwip/netif.h"
#include "lwip/timeouts.h"
#include "ethernetif.h"
Functions
void MX_LWIP_Init (void)
void MX_LWIP_Process (void)
Variables
ETH_HandleTypeDef heth
Function Documentation
MX_LWIP_Init()
void MX_LWIP_Init (void)
LwIP initialization function
Definition at line 60 of file lwip.c.
References ethernet_link_status_updated(), ethernetif_init(), gnetif, gw, ipaddr, lwip_init(), netif_add(), netif_is_link_up, netif_set_default(), netif_set_down(), netif_set_up(), netmask, and NULL.
Referenced by main().
MX_LWIP_Process()
void MX_LWIP_Process (void)
Function given to help user to continue LwIP Initialization Up to user to complete or change this function ...
Up to user to call this function in main.c in while (1) of main(void)
Read a received packet from the Ethernet buffers Send it to the lwIP stack for handling Handle timeouts if LWIP_TIMERS is set and without RTOS Handle the llink status if LWIP_NETIF_LINK_CALLBACK is set and without RTOS
Definition at line 138 of file lwip.c.
References Ethernet_Link_Periodic_Handle(), ethernetif_input(), and gnetif.
Variable Documentation
heth
ETH_HandleTypeDef heth
File Name : LWIP.h Description : This file provides code for the configuration of the LWIP.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition at line 120 of file ethernetif.c.