Sensorclient: LWIP/App/lwip.c File Reference
lwip.c File Reference
#include "lwip.h"
#include "lwip/init.h"
#include "lwip/netif.h"
#include "ethernetif.h"
Functions
static void ethernet_link_status_updated (struct netif *netif)
Notify the User about the network interface config status.
static void Ethernet_Link_Periodic_Handle (struct netif *netif)
Ethernet Link periodic check.
void Error_Handler (void)
This function is executed in case of error occurrence.
void MX_LWIP_Init (void)
void MX_LWIP_Process (void)
Variables
uint32_t DHCPfineTimer = 0
uint32_t DHCPcoarseTimer = 0
uint32_t EthernetLinkTimer
struct netif gnetif
ip4_addr_t ipaddr
ip4_addr_t netmask
ip4_addr_t gw
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 254 of file main.c.
Ethernet_Link_Periodic_Handle()
static void Ethernet_Link_Periodic_Handle (struct netif * netif) static
Ethernet Link periodic check.
Parameters
netif
Return values
None
Definition at line 112 of file lwip.c.
References ethernet_link_check_state(), EthernetLinkTimer, and HAL_GetTick().
Referenced by MX_LWIP_Process().
ethernet_link_status_updated()
static void ethernet_link_status_updated (struct netif * netif) static
Notify the User about the network interface config status.
File Name : LWIP.c Description : This file provides initialization code for LWIP middleWare.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Parameters
netif the network interface
Return values
None
Definition at line 160 of file lwip.c.
References netif_is_up.
Referenced by MX_LWIP_Init().
MX_LWIP_Init()
void MX_LWIP_Init (void)
LwIP initialization function
Definition at line 60 of file lwip.c.
References ethernet_link_status_updated(), ethernetif_init(), gnetif, gw, ipaddr, lwip_init(), netif_add(), netif_is_link_up, netif_set_default(), netif_set_down(), netif_set_up(), netmask, and NULL.
Referenced by main().
MX_LWIP_Process()
void MX_LWIP_Process (void)
Function given to help user to continue LwIP Initialization Up to user to complete or change this function ...
Up to user to call this function in main.c in while (1) of main(void)
Read a received packet from the Ethernet buffers Send it to the lwIP stack for handling Handle timeouts if LWIP_TIMERS is set and without RTOS Handle the llink status if LWIP_NETIF_LINK_CALLBACK is set and without RTOS
Definition at line 138 of file lwip.c.
References Ethernet_Link_Periodic_Handle(), ethernetif_input(), and gnetif.
Variable Documentation
DHCPcoarseTimer
uint32_t DHCPcoarseTimer = 0
Definition at line 41 of file lwip.c.
DHCPfineTimer
uint32_t DHCPfineTimer = 0
Definition at line 40 of file lwip.c.
EthernetLinkTimer
uint32_t EthernetLinkTimer
Definition at line 45 of file lwip.c.
Referenced by Ethernet_Link_Periodic_Handle().
gnetif
struct netif gnetif
Definition at line 48 of file lwip.c.
Referenced by MX_LWIP_Init(), and MX_LWIP_Process().
gw
ip4_addr_t gw
Definition at line 51 of file lwip.c.
Referenced by MX_LWIP_Init(), and netif_add().
ipaddr
ip4_addr_t ipaddr
Definition at line 49 of file lwip.c.
Referenced by MX_LWIP_Init(), and netif_add().
netmask
ip4_addr_t netmask
Definition at line 50 of file lwip.c.
Referenced by MX_LWIP_Init(), and netif_add().