Sensorclient: Core/Inc/main.h File Reference
main.h File Reference
: Header for main.c file. This file contains the common defines of the application.
#include "stm32f7xx_hal.h"
#include "stm32746g_discovery.h"
#include "stm32746g_discovery_ts.h"
#include "stm32746g_discovery_lcd.h"
#include "stm32746g_discovery_sdram.h"
#include "stm32746g_discovery_sd.h"
#include "stm32746g_discovery_eeprom.h"
#include "stm32746g_discovery_camera.h"
#include "stm32746g_discovery_audio.h"
#include "stm32746g_discovery_qspi.h"
Macros
#define QSPI_D2_Pin GPIO_PIN_2
#define QSPI_D2_GPIO_Port GPIOE
#define RMII_TXD1_Pin GPIO_PIN_14
#define RMII_TXD1_GPIO_Port GPIOG
#define ULPI_D7_Pin GPIO_PIN_5
#define ULPI_D7_GPIO_Port GPIOB
#define SWCLK_Pin GPIO_PIN_14
#define SWCLK_GPIO_Port GPIOA
#define SWDIO_Pin GPIO_PIN_13
#define SWDIO_GPIO_Port GPIOA
#define RMII_TXD0_Pin GPIO_PIN_13
#define RMII_TXD0_GPIO_Port GPIOG
#define VCP_RX_Pin GPIO_PIN_7
#define VCP_RX_GPIO_Port GPIOB
#define QSPI_NCS_Pin GPIO_PIN_6
#define QSPI_NCS_GPIO_Port GPIOB
#define RMII_TX_EN_Pin GPIO_PIN_11
#define RMII_TX_EN_GPIO_Port GPIOG
#define Audio_INT_Pin GPIO_PIN_6
#define Audio_INT_GPIO_Port GPIOD
#define NC1_Pin GPIO_PIN_8
#define NC1_GPIO_Port GPIOI
#define RCC_OSC32_IN_Pin GPIO_PIN_14
#define RCC_OSC32_IN_GPIO_Port GPIOC
#define VCP_TX_Pin GPIO_PIN_9
#define VCP_TX_GPIO_Port GPIOA
#define RCC_OSC32_OUT_Pin GPIO_PIN_15
#define RCC_OSC32_OUT_GPIO_Port GPIOC
#define USERBUTTON_Pin GPIO_PIN_11
#define USERBUTTON_GPIO_Port GPIOI
#define OSC_25M_Pin GPIO_PIN_0
#define OSC_25M_GPIO_Port GPIOH
#define ULPI_NXT_Pin GPIO_PIN_4
#define ULPI_NXT_GPIO_Port GPIOH
#define FMC_SDNE0_Pin GPIO_PIN_3
#define FMC_SDNE0_GPIO_Port GPIOH
#define NC2_Pin GPIO_PIN_2
#define NC2_GPIO_Port GPIOH
#define ULPI_D6_Pin GPIO_PIN_13
#define ULPI_D6_GPIO_Port GPIOB
#define FMC_SDCKE0_Pin GPIO_PIN_3
#define FMC_SDCKE0_GPIO_Port GPIOC
#define ULPI_D5_Pin GPIO_PIN_12
#define ULPI_D5_GPIO_Port GPIOB
#define ULPI_STP_Pin GPIO_PIN_0
#define ULPI_STP_GPIO_Port GPIOC
#define RMII_MDC_Pin GPIO_PIN_1
#define RMII_MDC_GPIO_Port GPIOC
#define ULPI_DIR_Pin GPIO_PIN_2
#define ULPI_DIR_GPIO_Port GPIOC
#define QSPI_D1_Pin GPIO_PIN_12
#define QSPI_D1_GPIO_Port GPIOD
#define QSPI_D3_Pin GPIO_PIN_13
#define QSPI_D3_GPIO_Port GPIOD
#define EXT_RST_Pin GPIO_PIN_3
#define EXT_RST_GPIO_Port GPIOG
#define RMII_RXER_Pin GPIO_PIN_2
#define RMII_RXER_GPIO_Port GPIOG
#define RMII_REF_CLK_Pin GPIO_PIN_1
#define RMII_REF_CLK_GPIO_Port GPIOA
#define RMII_RXD0_Pin GPIO_PIN_4
#define RMII_RXD0_GPIO_Port GPIOC
#define QSPI_D0_Pin GPIO_PIN_11
#define QSPI_D0_GPIO_Port GPIOD
#define RMII_MDIO_Pin GPIO_PIN_2
#define RMII_MDIO_GPIO_Port GPIOA
#define ULPI_CLK_Pin GPIO_PIN_5
#define ULPI_CLK_GPIO_Port GPIOA
#define RMII_RXD1_Pin GPIO_PIN_5
#define RMII_RXD1_GPIO_Port GPIOC
#define ULPI_D0_Pin GPIO_PIN_3
#define ULPI_D0_GPIO_Port GPIOA
#define RMII_CRS_DV_Pin GPIO_PIN_7
#define RMII_CRS_DV_GPIO_Port GPIOA
#define ULPI_D2_Pin GPIO_PIN_1
#define ULPI_D2_GPIO_Port GPIOB
#define ULPI_D1_Pin GPIO_PIN_0
#define ULPI_D1_GPIO_Port GPIOB
#define ULPI_D4_Pin GPIO_PIN_11
#define ULPI_D4_GPIO_Port GPIOB
#define LWIP_DHCP
Functions
void Error_Handler (void)
This function is executed in case of error occurrence.
Detailed Description
: Header for main.c file. This file contains the common defines of the application.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file main.h.
Macro Definition Documentation
Audio_INT_GPIO_Port
#define Audio_INT_GPIO_Port GPIOD
Definition at line 87 of file main.h.
Audio_INT_Pin
#define Audio_INT_Pin GPIO_PIN_6
Definition at line 86 of file main.h.
EXT_RST_GPIO_Port
#define EXT_RST_GPIO_Port GPIOG
Definition at line 123 of file main.h.
EXT_RST_Pin
#define EXT_RST_Pin GPIO_PIN_3
Definition at line 122 of file main.h.
FMC_SDCKE0_GPIO_Port
#define FMC_SDCKE0_GPIO_Port GPIOC
Definition at line 109 of file main.h.
FMC_SDCKE0_Pin
#define FMC_SDCKE0_Pin GPIO_PIN_3
Definition at line 108 of file main.h.
FMC_SDNE0_GPIO_Port
#define FMC_SDNE0_GPIO_Port GPIOH
Definition at line 103 of file main.h.
FMC_SDNE0_Pin
#define FMC_SDNE0_Pin GPIO_PIN_3
Definition at line 102 of file main.h.
LWIP_DHCP
#define LWIP_DHCP
Definition at line 150 of file main.h.
NC1_GPIO_Port
#define NC1_GPIO_Port GPIOI
Definition at line 89 of file main.h.
NC1_Pin
#define NC1_Pin GPIO_PIN_8
Definition at line 88 of file main.h.
NC2_GPIO_Port
#define NC2_GPIO_Port GPIOH
Definition at line 105 of file main.h.
NC2_Pin
#define NC2_Pin GPIO_PIN_2
Definition at line 104 of file main.h.
OSC_25M_GPIO_Port
#define OSC_25M_GPIO_Port GPIOH
Definition at line 99 of file main.h.
OSC_25M_Pin
#define OSC_25M_Pin GPIO_PIN_0
Definition at line 98 of file main.h.
QSPI_D0_GPIO_Port
#define QSPI_D0_GPIO_Port GPIOD
Definition at line 131 of file main.h.
QSPI_D0_Pin
#define QSPI_D0_Pin GPIO_PIN_11
Definition at line 130 of file main.h.
QSPI_D1_GPIO_Port
#define QSPI_D1_GPIO_Port GPIOD
Definition at line 119 of file main.h.
QSPI_D1_Pin
#define QSPI_D1_Pin GPIO_PIN_12
Definition at line 118 of file main.h.
QSPI_D2_GPIO_Port
#define QSPI_D2_GPIO_Port GPIOE
Definition at line 69 of file main.h.
QSPI_D2_Pin
#define QSPI_D2_Pin GPIO_PIN_2
Definition at line 68 of file main.h.
QSPI_D3_GPIO_Port
#define QSPI_D3_GPIO_Port GPIOD
Definition at line 121 of file main.h.
QSPI_D3_Pin
#define QSPI_D3_Pin GPIO_PIN_13
Definition at line 120 of file main.h.
QSPI_NCS_GPIO_Port
#define QSPI_NCS_GPIO_Port GPIOB
Definition at line 83 of file main.h.
QSPI_NCS_Pin
#define QSPI_NCS_Pin GPIO_PIN_6
Definition at line 82 of file main.h.
RCC_OSC32_IN_GPIO_Port
#define RCC_OSC32_IN_GPIO_Port GPIOC
Definition at line 91 of file main.h.
RCC_OSC32_IN_Pin
#define RCC_OSC32_IN_Pin GPIO_PIN_14
Definition at line 90 of file main.h.
RCC_OSC32_OUT_GPIO_Port
#define RCC_OSC32_OUT_GPIO_Port GPIOC
Definition at line 95 of file main.h.
RCC_OSC32_OUT_Pin
#define RCC_OSC32_OUT_Pin GPIO_PIN_15
Definition at line 94 of file main.h.
RMII_CRS_DV_GPIO_Port
#define RMII_CRS_DV_GPIO_Port GPIOA
Definition at line 141 of file main.h.
RMII_CRS_DV_Pin
#define RMII_CRS_DV_Pin GPIO_PIN_7
Definition at line 140 of file main.h.
RMII_MDC_GPIO_Port
#define RMII_MDC_GPIO_Port GPIOC
Definition at line 115 of file main.h.
RMII_MDC_Pin
#define RMII_MDC_Pin GPIO_PIN_1
Definition at line 114 of file main.h.
RMII_MDIO_GPIO_Port
#define RMII_MDIO_GPIO_Port GPIOA
Definition at line 133 of file main.h.
RMII_MDIO_Pin
#define RMII_MDIO_Pin GPIO_PIN_2
Definition at line 132 of file main.h.
RMII_REF_CLK_GPIO_Port
#define RMII_REF_CLK_GPIO_Port GPIOA
Definition at line 127 of file main.h.
RMII_REF_CLK_Pin
#define RMII_REF_CLK_Pin GPIO_PIN_1
Definition at line 126 of file main.h.
RMII_RXD0_GPIO_Port
#define RMII_RXD0_GPIO_Port GPIOC
Definition at line 129 of file main.h.
RMII_RXD0_Pin
#define RMII_RXD0_Pin GPIO_PIN_4
Definition at line 128 of file main.h.
RMII_RXD1_GPIO_Port
#define RMII_RXD1_GPIO_Port GPIOC
Definition at line 137 of file main.h.
RMII_RXD1_Pin
#define RMII_RXD1_Pin GPIO_PIN_5
Definition at line 136 of file main.h.
RMII_RXER_GPIO_Port
#define RMII_RXER_GPIO_Port GPIOG
Definition at line 125 of file main.h.
RMII_RXER_Pin
#define RMII_RXER_Pin GPIO_PIN_2
Definition at line 124 of file main.h.
RMII_TX_EN_GPIO_Port
#define RMII_TX_EN_GPIO_Port GPIOG
Definition at line 85 of file main.h.
RMII_TX_EN_Pin
#define RMII_TX_EN_Pin GPIO_PIN_11
Definition at line 84 of file main.h.
RMII_TXD0_GPIO_Port
#define RMII_TXD0_GPIO_Port GPIOG
Definition at line 79 of file main.h.
RMII_TXD0_Pin
#define RMII_TXD0_Pin GPIO_PIN_13
Definition at line 78 of file main.h.
RMII_TXD1_GPIO_Port
#define RMII_TXD1_GPIO_Port GPIOG
Definition at line 71 of file main.h.
RMII_TXD1_Pin
#define RMII_TXD1_Pin GPIO_PIN_14
Definition at line 70 of file main.h.
SWCLK_GPIO_Port
#define SWCLK_GPIO_Port GPIOA
Definition at line 75 of file main.h.
SWCLK_Pin
#define SWCLK_Pin GPIO_PIN_14
Definition at line 74 of file main.h.
SWDIO_GPIO_Port
#define SWDIO_GPIO_Port GPIOA
Definition at line 77 of file main.h.
SWDIO_Pin
#define SWDIO_Pin GPIO_PIN_13
Definition at line 76 of file main.h.
ULPI_CLK_GPIO_Port
#define ULPI_CLK_GPIO_Port GPIOA
Definition at line 135 of file main.h.
ULPI_CLK_Pin
#define ULPI_CLK_Pin GPIO_PIN_5
Definition at line 134 of file main.h.
ULPI_D0_GPIO_Port
#define ULPI_D0_GPIO_Port GPIOA
Definition at line 139 of file main.h.
ULPI_D0_Pin
#define ULPI_D0_Pin GPIO_PIN_3
Definition at line 138 of file main.h.
ULPI_D1_GPIO_Port
#define ULPI_D1_GPIO_Port GPIOB
Definition at line 145 of file main.h.
ULPI_D1_Pin
#define ULPI_D1_Pin GPIO_PIN_0
Definition at line 144 of file main.h.
ULPI_D2_GPIO_Port
#define ULPI_D2_GPIO_Port GPIOB
Definition at line 143 of file main.h.
ULPI_D2_Pin
#define ULPI_D2_Pin GPIO_PIN_1
Definition at line 142 of file main.h.
ULPI_D4_GPIO_Port
#define ULPI_D4_GPIO_Port GPIOB
Definition at line 147 of file main.h.
ULPI_D4_Pin
#define ULPI_D4_Pin GPIO_PIN_11
Definition at line 146 of file main.h.
ULPI_D5_GPIO_Port
#define ULPI_D5_GPIO_Port GPIOB
Definition at line 111 of file main.h.
ULPI_D5_Pin
#define ULPI_D5_Pin GPIO_PIN_12
Definition at line 110 of file main.h.
ULPI_D6_GPIO_Port
#define ULPI_D6_GPIO_Port GPIOB
Definition at line 107 of file main.h.
ULPI_D6_Pin
#define ULPI_D6_Pin GPIO_PIN_13
Definition at line 106 of file main.h.
ULPI_D7_GPIO_Port
#define ULPI_D7_GPIO_Port GPIOB
Definition at line 73 of file main.h.
ULPI_D7_Pin
#define ULPI_D7_Pin GPIO_PIN_5
Definition at line 72 of file main.h.
ULPI_DIR_GPIO_Port
#define ULPI_DIR_GPIO_Port GPIOC
Definition at line 117 of file main.h.
ULPI_DIR_Pin
#define ULPI_DIR_Pin GPIO_PIN_2
Definition at line 116 of file main.h.
ULPI_NXT_GPIO_Port
#define ULPI_NXT_GPIO_Port GPIOH
Definition at line 101 of file main.h.
ULPI_NXT_Pin
#define ULPI_NXT_Pin GPIO_PIN_4
Definition at line 100 of file main.h.
ULPI_STP_GPIO_Port
#define ULPI_STP_GPIO_Port GPIOC
Definition at line 113 of file main.h.
ULPI_STP_Pin
#define ULPI_STP_Pin GPIO_PIN_0
Definition at line 112 of file main.h.
USERBUTTON_GPIO_Port
#define USERBUTTON_GPIO_Port GPIOI
Definition at line 97 of file main.h.
USERBUTTON_Pin
#define USERBUTTON_Pin GPIO_PIN_11
Definition at line 96 of file main.h.
VCP_RX_GPIO_Port
#define VCP_RX_GPIO_Port GPIOB
Definition at line 81 of file main.h.
VCP_RX_Pin
#define VCP_RX_Pin GPIO_PIN_7
Definition at line 80 of file main.h.
VCP_TX_GPIO_Port
#define VCP_TX_GPIO_Port GPIOA
Definition at line 93 of file main.h.
VCP_TX_Pin
#define VCP_TX_Pin GPIO_PIN_9
Definition at line 92 of file main.h.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 254 of file main.c.
Referenced by HAL_RTC_MspInit(), HAL_UART_MspInit(), MX_CRC_Init(), MX_DMA2D_Init(), MX_FMC_Init(), MX_LTDC_Init(), MX_RNG_Init(), MX_RTC_Init(), MX_SAI1_Init(), MX_TIM1_Init(), and MX_USART1_UART_Init().