Sensorclient: Middlewares/Third_Party/LwIP/src/core/mem.c File Reference
mem.c File Reference
#include "lwip/opt.h"
#include "lwip/mem.h"
#include "lwip/def.h"
#include "lwip/sys.h"
#include "lwip/stats.h"
#include "lwip/err.h"
#include <string.h>
Classes
struct mem
Macros
#define LWIP_MEM_ILLEGAL_FREE(msg) LWIP_ASSERT(msg, 0)
#define MEM_STATS_INC_LOCKED(x) SYS_ARCH_LOCKED(MEM_STATS_INC(x))
#define MEM_STATS_INC_USED_LOCKED(x, y) SYS_ARCH_LOCKED(MEM_STATS_INC_USED(x, y))
#define MEM_STATS_DEC_USED_LOCKED(x, y) SYS_ARCH_LOCKED(MEM_STATS_DEC_USED(x, y))
#define MEM_SANITY_OFFSET 0
#define MEM_SANITY_OVERHEAD 0
#define MIN_SIZE 12
#define MIN_SIZE_ALIGNED LWIP_MEM_ALIGN_SIZE(MIN_SIZE)
#define SIZEOF_STRUCT_MEM LWIP_MEM_ALIGN_SIZE(sizeof(struct mem))
#define MEM_SIZE_ALIGNED LWIP_MEM_ALIGN_SIZE(MEM_SIZE)
#define LWIP_RAM_HEAP_POINTER ram_heap
#define LWIP_MEM_FREE_DECL_PROTECT()
#define LWIP_MEM_FREE_PROTECT() sys_mutex_lock(&mem_mutex)
#define LWIP_MEM_FREE_UNPROTECT() sys_mutex_unlock(&mem_mutex)
#define LWIP_MEM_ALLOC_DECL_PROTECT()
#define LWIP_MEM_ALLOC_PROTECT()
#define LWIP_MEM_ALLOC_UNPROTECT()
#define LWIP_MEM_LFREE_VOLATILE
#define MEM_SANITY()
#define mem_overflow_init_element(mem, size)
#define mem_overflow_check_element(mem)
Functions
LWIP_DECLARE_MEMORY_ALIGNED (ram_heap, MEM_SIZE_ALIGNED+(2U *SIZEOF_STRUCT_MEM))
static struct mem * ptr_to_mem (mem_size_t ptr)
static mem_size_t mem_to_ptr (void *mem)
static void plug_holes (struct mem *mem)
void mem_init (void)
static int mem_link_valid (struct mem *mem)
void mem_free (void *rmem)
void * mem_trim (void *rmem, mem_size_t new_size)
void * mem_malloc (mem_size_t size_in)
void * mem_calloc (mem_size_t count, mem_size_t size)
Variables
static u8_t * ram
static struct mem * ram_end
static sys_mutex_t mem_mutex
static struct mem *LWIP_MEM_LFREE_VOLATILE lfree
Detailed Description
Dynamic memory manager
This is a lightweight replacement for the standard C library malloc().
If you want to use the standard C library malloc() instead, define MEM_LIBC_MALLOC to 1 in your lwipopts.h
To let mem_malloc() use pools (prevents fragmentation and is much faster than a heap but might waste some memory), define MEM_USE_POOLS to 1, define MEMP_USE_CUSTOM_POOLS to 1 and create a file "lwippools.h" that includes a list of pools like this (more pools can be added between _START and _END):
Define three pools with sizes 256, 512, and 1512 bytes LWIP_MALLOC_MEMPOOL_START LWIP_MALLOC_MEMPOOL(20, 256) LWIP_MALLOC_MEMPOOL(10, 512) LWIP_MALLOC_MEMPOOL(5, 1512) LWIP_MALLOC_MEMPOOL_END
Definition in file mem.c.
Macro Definition Documentation
LWIP_MEM_ALLOC_DECL_PROTECT
#define LWIP_MEM_ALLOC_DECL_PROTECT ()
Definition at line 413 of file mem.c.
LWIP_MEM_ALLOC_PROTECT
#define LWIP_MEM_ALLOC_PROTECT ()
Definition at line 414 of file mem.c.
LWIP_MEM_ALLOC_UNPROTECT
#define LWIP_MEM_ALLOC_UNPROTECT ()
Definition at line 415 of file mem.c.
LWIP_MEM_FREE_DECL_PROTECT
#define LWIP_MEM_FREE_DECL_PROTECT ()
Definition at line 409 of file mem.c.
LWIP_MEM_FREE_PROTECT
#define LWIP_MEM_FREE_PROTECT () sys_mutex_lock(&mem_mutex)
Definition at line 410 of file mem.c.
LWIP_MEM_FREE_UNPROTECT
#define LWIP_MEM_FREE_UNPROTECT () sys_mutex_unlock(&mem_mutex)
Definition at line 411 of file mem.c.
LWIP_MEM_ILLEGAL_FREE
#define LWIP_MEM_ILLEGAL_FREE (msg) LWIP_ASSERT(msg, 0)
Definition at line 71 of file mem.c.
LWIP_MEM_LFREE_VOLATILE
#define LWIP_MEM_LFREE_VOLATILE
Definition at line 416 of file mem.c.
LWIP_RAM_HEAP_POINTER
#define LWIP_RAM_HEAP_POINTER ram_heap
Definition at line 380 of file mem.c.
mem_overflow_check_element
#define mem_overflow_check_element (mem)
Definition at line 447 of file mem.c.
mem_overflow_init_element
#define mem_overflow_init_element (mem, size)
Definition at line 446 of file mem.c.
MEM_SANITY
#define MEM_SANITY ()
Definition at line 427 of file mem.c.
MEM_SANITY_OFFSET
#define MEM_SANITY_OFFSET 0
Definition at line 82 of file mem.c.
MEM_SANITY_OVERHEAD
#define MEM_SANITY_OVERHEAD 0
Definition at line 83 of file mem.c.
MEM_SIZE_ALIGNED
#define MEM_SIZE_ALIGNED LWIP_MEM_ALIGN_SIZE(MEM_SIZE)
Definition at line 371 of file mem.c.
MEM_STATS_DEC_USED_LOCKED
#define MEM_STATS_DEC_USED_LOCKED (x, y) SYS_ARCH_LOCKED(MEM_STATS_DEC_USED(x, y))
Definition at line 76 of file mem.c.
MEM_STATS_INC_LOCKED
#define MEM_STATS_INC_LOCKED (x) SYS_ARCH_LOCKED(MEM_STATS_INC(x))
Definition at line 74 of file mem.c.
MEM_STATS_INC_USED_LOCKED
#define MEM_STATS_INC_USED_LOCKED (x, y) SYS_ARCH_LOCKED(MEM_STATS_INC_USED(x, y))
Definition at line 75 of file mem.c.
MIN_SIZE
#define MIN_SIZE 12
All allocated blocks will be MIN_SIZE bytes big, at least! MIN_SIZE can be overridden to suit your needs. Smaller values save space, larger values could prevent too small blocks to fragment the RAM too much.
Definition at line 366 of file mem.c.
MIN_SIZE_ALIGNED
#define MIN_SIZE_ALIGNED LWIP_MEM_ALIGN_SIZE(MIN_SIZE)
Definition at line 369 of file mem.c.
SIZEOF_STRUCT_MEM
#define SIZEOF_STRUCT_MEM LWIP_MEM_ALIGN_SIZE(sizeof(struct mem))
Definition at line 370 of file mem.c.
Function Documentation
LWIP_DECLARE_MEMORY_ALIGNED()
LWIP_DECLARE_MEMORY_ALIGNED (ram_heap , MEM_SIZE_ALIGNED+ 2U *SIZEOF_STRUCT_MEM)
If you want to relocate the heap to external memory, simply define LWIP_RAM_HEAP_POINTER as a void-pointer to that location. If so, make sure the memory at that location is big enough (see below on how that space is calculated). the heap. we need one struct mem at the end and some room for alignment
mem_calloc()
void* mem_calloc (mem_size_t count, mem_size_t size)
Contiguously allocates enough space for count objects that are size bytes of memory each and returns a pointer to the allocated memory.
The allocated memory is filled with bytes of value zero.
Parameters
count number of objects to allocate
size size of the objects to allocate
Returns
pointer to allocated memory / NULL pointer if there is an error
Definition at line 999 of file mem.c.
References LWIP_DBG_LEVEL_SERIOUS, LWIP_DEBUGF, MEM_DEBUG, mem_malloc(), NULL, and SZT_F.
Referenced by bridgeif_fdb_init().
mem_free()
void mem_free (void * rmem)
Put a struct mem back on the heap
Parameters
rmem is the data portion of a struct mem as returned by a previous call to mem_malloc()
Definition at line 617 of file mem.c.
References lfree, LWIP_DBG_LEVEL_SERIOUS, LWIP_DBG_LEVEL_SEVERE, LWIP_DBG_TRACE, LWIP_DEBUGF, LWIP_MEM_FREE_DECL_PROTECT, LWIP_MEM_FREE_PROTECT, LWIP_MEM_FREE_UNPROTECT, LWIP_MEM_ILLEGAL_FREE, MEM_ALIGNMENT, MEM_DEBUG, mem_link_valid(), mem_overflow_check_element, MEM_SANITY, MEM_SANITY_OFFSET, MEM_STATS_DEC_USED, MEM_STATS_INC_LOCKED, mem::next, NULL, plug_holes(), ram, ram_end, SIZEOF_STRUCT_MEM, and mem::used.
Referenced by do_memp_free_pool(), mem_free_callback(), pbuf_free(), and slipif_init().
mem_init()
void mem_init (void)
Zero the heap and initialize start, end and lowest-free
Definition at line 516 of file mem.c.
References ERR_OK, lfree, LWIP_ASSERT, LWIP_MEM_ALIGN, LWIP_RAM_HEAP_POINTER, MEM_ALIGNMENT, mem_mutex, MEM_SANITY, MEM_SIZE_ALIGNED, MEM_STATS_AVAIL, mem::next, mem::prev, ptr_to_mem(), ram, ram_end, SIZEOF_STRUCT_MEM, sys_mutex_new(), and mem::used.
Referenced by lwip_init().
mem_link_valid()
static int mem_link_valid (struct mem * mem) static
Definition at line 551 of file mem.c.
References MEM_SIZE_ALIGNED, mem_to_ptr(), mem::next, mem::prev, ptr_to_mem(), and ram_end.
Referenced by mem_free().
mem_malloc()
void* mem_malloc (mem_size_t size_in)
Allocate a block of memory with a minimum of 'size' bytes.
Parameters
size_in is the minimum size of the requested block in bytes.
Returns
pointer to allocated memory or NULL if no free memory was found.
Note that the returned value will always be aligned (as defined by MEM_ALIGNMENT).
Definition at line 831 of file mem.c.
References lfree, LWIP_ASSERT, LWIP_DBG_LEVEL_SERIOUS, LWIP_DEBUGF, LWIP_MEM_ALIGN_SIZE, LWIP_MEM_ALLOC_DECL_PROTECT, LWIP_MEM_ALLOC_PROTECT, LWIP_MEM_ALLOC_UNPROTECT, MEM_ALIGNMENT, MEM_DEBUG, mem_mutex, mem_overflow_init_element, MEM_SANITY, MEM_SANITY_OFFSET, MEM_SIZE_ALIGNED, MEM_STATS_INC, MEM_STATS_INC_USED, mem_to_ptr(), MIN_SIZE_ALIGNED, mem::next, NULL, mem::prev, ptr_to_mem(), ram_end, S16_F, SIZEOF_STRUCT_MEM, sys_mutex_lock(), sys_mutex_unlock(), and mem::used.
Referenced by do_memp_malloc_pool(), mem_calloc(), pbuf_alloc(), and slipif_init().
mem_to_ptr()
static mem_size_t mem_to_ptr (void * mem) static
Definition at line 457 of file mem.c.
References ram.
Referenced by mem_link_valid(), mem_malloc(), mem_trim(), and plug_holes().
mem_trim()
void* mem_trim (void * rmem, mem_size_t new_size)
Shrink memory returned by mem_malloc().
Parameters
rmem pointer to memory allocated by mem_malloc the is to be shrinked
new_size required size after shrinking (needs to be smaller than or equal to the previous size)
Returns
for compatibility reasons: is always == rmem, at the moment or NULL if newsize is > old size, in which case rmem is NOT touched or freed!
Definition at line 699 of file mem.c.
References lfree, LWIP_ASSERT, LWIP_DBG_LEVEL_SEVERE, LWIP_DEBUGF, LWIP_MEM_ALIGN_SIZE, LWIP_MEM_FREE_DECL_PROTECT, LWIP_MEM_FREE_PROTECT, LWIP_MEM_FREE_UNPROTECT, MEM_DEBUG, mem_overflow_check_element, mem_overflow_init_element, MEM_SANITY, MEM_SANITY_OFFSET, MEM_SANITY_OVERHEAD, MEM_SIZE_ALIGNED, MEM_STATS_DEC_USED, MEM_STATS_INC_LOCKED, mem_to_ptr(), MIN_SIZE_ALIGNED, mem::next, NULL, mem::prev, ptr_to_mem(), ram, ram_end, SIZEOF_STRUCT_MEM, and mem::used.
Referenced by pbuf_realloc().
plug_holes()
static void plug_holes (struct mem * mem) static
"Plug holes" by combining adjacent empty struct mems. After this function is through, there should not exist one empty struct mem pointing to another empty struct mem.
Parameters
mem this points to a struct mem which just has been freed
Definition at line 474 of file mem.c.
References lfree, LWIP_ASSERT, MEM_SIZE_ALIGNED, mem_to_ptr(), mem::next, mem::prev, ptr_to_mem(), ram, ram_end, and mem::used.
Referenced by mem_free().
ptr_to_mem()
static struct mem* ptr_to_mem (mem_size_t ptr) static
Definition at line 451 of file mem.c.
References ram.
Referenced by mem_init(), mem_link_valid(), mem_malloc(), mem_trim(), and plug_holes().
Variable Documentation
lfree
struct mem* LWIP_MEM_LFREE_VOLATILE lfree static
pointer to the lowest free block, this is used for faster search
Definition at line 421 of file mem.c.
Referenced by mem_free(), mem_init(), mem_malloc(), mem_trim(), and plug_holes().
mem_mutex
sys_mutex_t mem_mutex static
concurrent access protection
Definition at line 390 of file mem.c.
Referenced by mem_init(), and mem_malloc().
ram
u8_t* ram static
pointer to the heap (ram_heap): for alignment, ram is now a pointer instead of an array
Definition at line 384 of file mem.c.
Referenced by mem_free(), mem_init(), mem_to_ptr(), mem_trim(), plug_holes(), and ptr_to_mem().
ram_end
struct mem* ram_end static
the last entry, always unused!
Definition at line 386 of file mem.c.
Referenced by mem_free(), mem_init(), mem_link_valid(), mem_malloc(), mem_trim(), and plug_holes().