Sensorclient: Middlewares/Third_Party/LwIP/src/core/memp.c File Reference
memp.c File Reference
#include "lwip/opt.h"
#include "lwip/memp.h"
#include "lwip/sys.h"
#include "lwip/stats.h"
#include <string.h>
#include "lwip/pbuf.h"
#include "lwip/raw.h"
#include "lwip/udp.h"
#include "lwip/tcp.h"
#include "lwip/priv/tcp_priv.h"
#include "lwip/altcp.h"
#include "lwip/ip4_frag.h"
#include "lwip/netbuf.h"
#include "lwip/api.h"
#include "lwip/priv/tcpip_priv.h"
#include "lwip/priv/api_msg.h"
#include "lwip/priv/sockets_priv.h"
#include "lwip/etharp.h"
#include "lwip/igmp.h"
#include "lwip/timeouts.h"
#include "netif/ppp/ppp_opts.h"
#include "lwip/netdb.h"
#include "lwip/dns.h"
#include "lwip/priv/nd6_priv.h"
#include "lwip/ip6_frag.h"
#include "lwip/mld6.h"
#include "lwip/priv/memp_std.h"
Macros
#define LWIP_MEMPOOL(name, num, size, desc) LWIP_MEMPOOL_DECLARE(name,num,size,desc)
#define LWIP_MEMPOOL(name, num, size, desc) &memp_ ## name,
Functions
void memp_init_pool (const struct memp_desc *desc)
void memp_init (void)
static void * do_memp_malloc_pool (const struct memp_desc *desc)
void * memp_malloc_pool (const struct memp_desc *desc)
void * memp_malloc (memp_t type)
static void do_memp_free_pool (const struct memp_desc *desc, void *mem)
void memp_free_pool (const struct memp_desc *desc, void *mem)
void memp_free (memp_t type, void *mem)
Variables
const struct memp_desc *const memp_pools [MEMP_MAX]
Detailed Description
Dynamic pool memory manager
lwIP has dedicated pools for many structures (netconn, protocol control blocks, packet buffers, ...). All these pools are managed here.
Definition in file memp.c.
Macro Definition Documentation
LWIP_MEMPOOL [1/2]
#define LWIP_MEMPOOL (name, num, size, desc) LWIP_MEMPOOL_DECLARE(name,num,size,desc)
Definition at line 78 of file memp.c.
LWIP_MEMPOOL [2/2]
#define LWIP_MEMPOOL (name, num, size, desc) &memp_ ## name,
Definition at line 78 of file memp.c.
Function Documentation
do_memp_free_pool()
static void do_memp_free_pool (const struct memp_desc * desc, void * mem) static
Definition at line 359 of file memp.c.
References LWIP_ASSERT, LWIP_UNUSED_ARG, MEM_ALIGNMENT, mem_free(), MEMP_SIZE, memp::next, SYS_ARCH_DECL_PROTECT, SYS_ARCH_PROTECT, SYS_ARCH_UNPROTECT, and memp_desc::tab.
Referenced by memp_free(), and memp_free_pool().
do_memp_malloc_pool()
static void* do_memp_malloc_pool (const struct memp_desc * desc) static
Definition at line 245 of file memp.c.
References LWIP_ASSERT, LWIP_DBG_LEVEL_SERIOUS, LWIP_DEBUGF, MEM_ALIGNMENT, mem_malloc(), MEMP_ALIGN_SIZE, MEMP_DEBUG, MEMP_SIZE, memp::next, NULL, memp_desc::size, SYS_ARCH_DECL_PROTECT, SYS_ARCH_PROTECT, SYS_ARCH_UNPROTECT, and memp_desc::tab.
Referenced by memp_malloc(), and memp_malloc_pool().
memp_free()
void memp_free (memp_t type, void * mem)
Put an element back into its pool.
Parameters
type the pool where to put mem
mem the memp element to free
Definition at line 420 of file memp.c.
References do_memp_free_pool(), LWIP_ERROR, MEMP_MAX, memp_pools, NULL, and memp_desc::tab.
Referenced by pbuf_free(), tcpip_callbackmsg_delete(), tcpip_inpkt(), tcpip_thread_handle_msg(), and tcpip_try_callback().
memp_free_pool()
void memp_free_pool (const struct memp_desc * desc, void * mem)
Put a custom pool element back into its pool.
Parameters
desc the pool where to put mem
mem the memp element to free
Definition at line 403 of file memp.c.
References do_memp_free_pool(), LWIP_ASSERT, and NULL.
memp_init()
void memp_init (void)
Initializes lwIP built-in pools. Related functions: memp_malloc, memp_free
Carves out memp_memory into linked lists for each pool-type.
Definition at line 224 of file memp.c.
References LWIP_ARRAYSIZE, memp_init_pool(), and memp_pools.
Referenced by lwip_init().
memp_init_pool()
void memp_init_pool (const struct memp_desc * desc)
Initialize custom memory pool. Related functions: memp_malloc_pool, memp_free_pool
Parameters
desc pool to initialize
Definition at line 175 of file memp.c.
References memp_desc::base, LWIP_MEM_ALIGN, LWIP_UNUSED_ARG, MEMP_OVERFLOW_CHECK, MEMP_SIZE, memp::next, NULL, memp_desc::num, memp_desc::size, and memp_desc::tab.
Referenced by memp_init().
memp_malloc()
void* memp_malloc (memp_t type)
Get an element from a specific pool.
Parameters
type the pool to get an element from
Returns
a pointer to the allocated memory or a NULL pointer on error
Definition at line 337 of file memp.c.
References do_memp_malloc_pool(), LWIP_ERROR, MEMP_MAX, memp_pools, and NULL.
Referenced by pbuf_alloc(), pbuf_alloc_reference(), tcpip_callback(), tcpip_callbackmsg_new(), tcpip_inpkt(), and tcpip_try_callback().
memp_malloc_pool()
void* memp_malloc_pool (const struct memp_desc * desc)
Get an element from a custom pool.
Parameters
desc the pool to get an element from
Returns
a pointer to the allocated memory or a NULL pointer on error
Definition at line 311 of file memp.c.
References do_memp_malloc_pool(), LWIP_ASSERT, and NULL.
Variable Documentation
memp_pools
const struct memp_desc* const memp_pools[MEMP_MAX]
Initial value:
= {
#define LWIP_MEMPOOL(name,num,size,desc)
}
Definition at line 81 of file memp.c.
Referenced by memp_free(), memp_init(), and memp_malloc().