Sensorclient: Middlewares/Third_Party/LwIP/src/include/lwip/priv/memp_priv.h File Reference
memp_priv.h File Reference
#include "lwip/opt.h"
#include "lwip/mem.h"
#include "lwip/priv/mem_priv.h"
Classes
struct memp
struct memp_desc
Macros
#define MEMP_SIZE 0
#define MEMP_ALIGN_SIZE(x) (LWIP_MEM_ALIGN_SIZE(x))
#define DECLARE_LWIP_MEMPOOL_DESC(desc)
#define LWIP_MEMPOOL_DECLARE_STATS_INSTANCE(name)
#define LWIP_MEMPOOL_DECLARE_STATS_REFERENCE(name)
Functions
void memp_init_pool (const struct memp_desc *desc)
void * memp_malloc_pool (const struct memp_desc *desc)
void memp_free_pool (const struct memp_desc *desc, void *mem)
Detailed Description
memory pools lwIP internal implementations (do not use in application code)
Definition in file memp_priv.h.
Macro Definition Documentation
DECLARE_LWIP_MEMPOOL_DESC
#define DECLARE_LWIP_MEMPOOL_DESC (desc)
Definition at line 136 of file memp_priv.h.
LWIP_MEMPOOL_DECLARE_STATS_INSTANCE
#define LWIP_MEMPOOL_DECLARE_STATS_INSTANCE (name)
Definition at line 143 of file memp_priv.h.
LWIP_MEMPOOL_DECLARE_STATS_REFERENCE
#define LWIP_MEMPOOL_DECLARE_STATS_REFERENCE (name)
Definition at line 144 of file memp_priv.h.
MEMP_ALIGN_SIZE
#define MEMP_ALIGN_SIZE (x) (LWIP_MEM_ALIGN_SIZE(x))
Definition at line 64 of file memp_priv.h.
MEMP_SIZE
#define MEMP_SIZE 0
Definition at line 63 of file memp_priv.h.
Function Documentation
memp_free_pool()
void memp_free_pool (const struct memp_desc * desc, void * mem)
Put a custom pool element back into its pool.
Parameters
desc the pool where to put mem
mem the memp element to free
Definition at line 403 of file memp.c.
References do_memp_free_pool(), LWIP_ASSERT, and NULL.
memp_init_pool()
void memp_init_pool (const struct memp_desc * desc)
Initialize custom memory pool. Related functions: memp_malloc_pool, memp_free_pool
Parameters
desc pool to initialize
Definition at line 175 of file memp.c.
References memp_desc::base, LWIP_MEM_ALIGN, LWIP_UNUSED_ARG, MEMP_OVERFLOW_CHECK, MEMP_SIZE, memp::next, NULL, memp_desc::num, memp_desc::size, and memp_desc::tab.
Referenced by memp_init().
memp_malloc_pool()
void* memp_malloc_pool (const struct memp_desc * desc)
Get an element from a custom pool.
Parameters
desc the pool to get an element from
Returns
a pointer to the allocated memory or a NULL pointer on error
Definition at line 311 of file memp.c.
References do_memp_malloc_pool(), LWIP_ASSERT, and NULL.