var modules =
[
    [ "CMSIS Global Defines", "group__CMSIS__glob__defs.html", null ],
    [ "Defines and Type Definitions", "group__CMSIS__core__register.html", "group__CMSIS__core__register" ],
    [ "HAL CRYP Aliased Defines maintained for legacy purpose", "group__HAL__AES__Aliased__Defines.html", "group__HAL__AES__Aliased__Defines" ],
    [ "HAL ADC Aliased Defines maintained for legacy purpose", "group__HAL__ADC__Aliased__Defines.html", "group__HAL__ADC__Aliased__Defines" ],
    [ "HAL CEC Aliased Defines maintained for legacy purpose", "group__HAL__CEC__Aliased__Defines.html", "group__HAL__CEC__Aliased__Defines" ],
    [ "HAL COMP Aliased Defines maintained for legacy purpose", "group__HAL__COMP__Aliased__Defines.html", "group__HAL__COMP__Aliased__Defines" ],
    [ "HAL CORTEX Aliased Defines maintained for legacy purpose", "group__HAL__CORTEX__Aliased__Defines.html", "group__HAL__CORTEX__Aliased__Defines" ],
    [ "CRC API aliases", "group__CRC__Aliases.html", "group__CRC__Aliases" ],
    [ "HAL CRC Aliased Defines maintained for legacy purpose", "group__HAL__CRC__Aliased__Defines.html", "group__HAL__CRC__Aliased__Defines" ],
    [ "HAL DAC Aliased Defines maintained for legacy purpose", "group__HAL__DAC__Aliased__Defines.html", "group__HAL__DAC__Aliased__Defines" ],
    [ "HAL DMA Aliased Defines maintained for legacy purpose", "group__HAL__DMA__Aliased__Defines.html", "group__HAL__DMA__Aliased__Defines" ],
    [ "HAL FLASH Aliased Defines maintained for legacy purpose", "group__HAL__FLASH__Aliased__Defines.html", "group__HAL__FLASH__Aliased__Defines" ],
    [ "HAL JPEG Aliased Macros maintained for legacy purpose", "group__HAL__JPEG__Aliased__Macros.html", null ],
    [ "HAL SYSCFG Aliased Defines maintained for legacy purpose", "group__HAL__SYSCFG__Aliased__Defines.html", "group__HAL__SYSCFG__Aliased__Defines" ],
    [ "LL FMC Aliased Defines maintained for compatibility purpose", "group__LL__FMC__Aliased__Defines.html", null ],
    [ "LL FSMC Aliased Defines maintained for legacy purpose", "group__LL__FSMC__Aliased__Defines.html", "group__LL__FSMC__Aliased__Defines" ],
    [ "HAL GPIO Aliased Macros maintained for legacy purpose", "group__HAL__GPIO__Aliased__Macros.html", "group__HAL__GPIO__Aliased__Macros" ],
    [ "HAL GTZC Aliased Defines maintained for legacy purpose", "group__HAL__GTZC__Aliased__Defines.html", null ],
    [ "HAL HRTIM Aliased Macros maintained for legacy purpose", "group__HAL__HRTIM__Aliased__Macros.html", "group__HAL__HRTIM__Aliased__Macros" ],
    [ "HAL I2C Aliased Defines maintained for legacy purpose", "group__HAL__I2C__Aliased__Defines.html", "group__HAL__I2C__Aliased__Defines" ],
    [ "HAL IRDA Aliased Defines maintained for legacy purpose", "group__HAL__IRDA__Aliased__Defines.html", "group__HAL__IRDA__Aliased__Defines" ],
    [ "HAL IWDG Aliased Defines maintained for legacy purpose", "group__HAL__IWDG__Aliased__Defines.html", "group__HAL__IWDG__Aliased__Defines" ],
    [ "HAL LPTIM Aliased Defines maintained for legacy purpose", "group__HAL__LPTIM__Aliased__Defines.html", "group__HAL__LPTIM__Aliased__Defines" ],
    [ "HAL NAND Aliased Defines maintained for legacy purpose", "group__HAL__NAND__Aliased__Defines.html", "group__HAL__NAND__Aliased__Defines" ],
    [ "HAL NOR Aliased Defines maintained for legacy purpose", "group__HAL__NOR__Aliased__Defines.html", "group__HAL__NOR__Aliased__Defines" ],
    [ "HAL OPAMP Aliased Defines maintained for legacy purpose", "group__HAL__OPAMP__Aliased__Defines.html", "group__HAL__OPAMP__Aliased__Defines" ],
    [ "HAL I2S Aliased Defines maintained for legacy purpose", "group__HAL__I2S__Aliased__Defines.html", "group__HAL__I2S__Aliased__Defines" ],
    [ "HAL PCCARD Aliased Defines maintained for legacy purpose", "group__HAL__PCCARD__Aliased__Defines.html", "group__HAL__PCCARD__Aliased__Defines" ],
    [ "HAL RTC Aliased Defines maintained for legacy purpose", "group__HAL__RTC__Aliased__Defines.html", "group__HAL__RTC__Aliased__Defines" ],
    [ "HAL SMARTCARD Aliased Defines maintained for legacy purpose", "group__HAL__SMARTCARD__Aliased__Defines.html", "group__HAL__SMARTCARD__Aliased__Defines" ],
    [ "HAL SMBUS Aliased Defines maintained for legacy purpose", "group__HAL__SMBUS__Aliased__Defines.html", "group__HAL__SMBUS__Aliased__Defines" ],
    [ "HAL SPI Aliased Defines maintained for legacy purpose", "group__HAL__SPI__Aliased__Defines.html", "group__HAL__SPI__Aliased__Defines" ],
    [ "HAL TIM Aliased Defines maintained for legacy purpose", "group__HAL__TIM__Aliased__Defines.html", "group__HAL__TIM__Aliased__Defines" ],
    [ "HAL TSC Aliased Defines maintained for legacy purpose", "group__HAL__TSC__Aliased__Defines.html", "group__HAL__TSC__Aliased__Defines" ],
    [ "HAL UART Aliased Defines maintained for legacy purpose", "group__HAL__UART__Aliased__Defines.html", "group__HAL__UART__Aliased__Defines" ],
    [ "HAL USART Aliased Defines maintained for legacy purpose", "group__HAL__USART__Aliased__Defines.html", "group__HAL__USART__Aliased__Defines" ],
    [ "HAL WWDG Aliased Defines maintained for legacy purpose", "group__HAL__WWDG__Aliased__Defines.html", "group__HAL__WWDG__Aliased__Defines" ],
    [ "HAL CAN Aliased Defines maintained for legacy purpose", "group__HAL__CAN__Aliased__Defines.html", "group__HAL__CAN__Aliased__Defines" ],
    [ "HAL ETH Aliased Defines maintained for legacy purpose", "group__HAL__ETH__Aliased__Defines.html", "group__HAL__ETH__Aliased__Defines" ],
    [ "HAL DCMI Aliased Defines maintained for legacy purpose", "group__HAL__DCMI__Aliased__Defines.html", "group__HAL__DCMI__Aliased__Defines" ],
    [ "HAL PPP Aliased Defines maintained for legacy purpose", "group__HAL__PPP__Aliased__Defines.html", null ],
    [ "HAL CRYP Aliased Functions maintained for legacy purpose", "group__HAL__CRYP__Aliased__Functions.html", "group__HAL__CRYP__Aliased__Functions" ],
    [ "HAL DCACHE Aliased Functions maintained for legacy purpose", "group__HAL__DCACHE__Aliased__Functions.html", null ],
    [ "HASH API alias", "group__HASH__alias.html", "group__HASH__alias" ],
    [ "HAL HASH Aliased Functions maintained for legacy purpose", "group__HAL__HASH__Aliased__Functions.html", "group__HAL__HASH__Aliased__Functions" ],
    [ "HAL Generic Aliased Functions maintained for legacy purpose", "group__HAL__Aliased__Functions.html", "group__HAL__Aliased__Functions" ],
    [ "HAL FLASH Aliased Functions maintained for legacy purpose", "group__HAL__FLASH__Aliased__Functions.html", "group__HAL__FLASH__Aliased__Functions" ],
    [ "HAL I2C Aliased Functions maintained for legacy purpose", "group__HAL__I2C__Aliased__Functions.html", "group__HAL__I2C__Aliased__Functions" ],
    [ "HAL PWR Aliased maintained for legacy purpose", "group__HAL__PWR__Aliased.html", "group__HAL__PWR__Aliased" ],
    [ "HAL SMBUS Aliased Functions maintained for legacy purpose", "group__HAL__SMBUS__Aliased__Functions.html", "group__HAL__SMBUS__Aliased__Functions" ],
    [ "HAL SPI Aliased Functions maintained for legacy purpose", "group__HAL__SPI__Aliased__Functions.html", "group__HAL__SPI__Aliased__Functions" ],
    [ "HAL TIM Aliased Functions maintained for legacy purpose", "group__HAL__TIM__Aliased__Functions.html", "group__HAL__TIM__Aliased__Functions" ],
    [ "HAL UART Aliased Functions maintained for legacy purpose", "group__HAL__UART__Aliased__Functions.html", "group__HAL__UART__Aliased__Functions" ],
    [ "HAL LTDC Aliased Functions maintained for legacy purpose", "group__HAL__LTDC__Aliased__Functions.html", "group__HAL__LTDC__Aliased__Functions" ],
    [ "HAL PPP Aliased Functions maintained for legacy purpose", "group__HAL__PPP__Aliased__Functions.html", null ],
    [ "HAL CRYP Aliased Macros maintained for legacy purpose", "group__HAL__AES__Aliased__Macros.html", "group__HAL__AES__Aliased__Macros" ],
    [ "HAL Generic Aliased Macros maintained for legacy purpose", "group__HAL__Aliased__Macros.html", "group__HAL__Aliased__Macros" ],
    [ "HAL ADC Aliased Macros maintained for legacy purpose", "group__HAL__ADC__Aliased__Macros.html", "group__HAL__ADC__Aliased__Macros" ],
    [ "HAL DAC Aliased Macros maintained for legacy purpose", "group__HAL__DAC__Aliased__Macros.html", "group__HAL__DAC__Aliased__Macros" ],
    [ "HAL DBGMCU Aliased Macros maintained for legacy purpose", "group__HAL__DBGMCU__Aliased__Macros.html", "group__HAL__DBGMCU__Aliased__Macros" ],
    [ "HAL COMP Aliased Macros maintained for legacy purpose", "group__HAL__COMP__Aliased__Macros.html", "group__HAL__COMP__Aliased__Macros" ],
    [ "HAL FLASH Aliased Macros maintained for legacy purpose", "group__HAL__FLASH__Aliased__Macros.html", "group__HAL__FLASH__Aliased__Macros" ],
    [ "HAL I2C Aliased Macros maintained for legacy purpose", "group__HAL__I2C__Aliased__Macros.html", "group__HAL__I2C__Aliased__Macros" ],
    [ "HAL I2S Aliased Macros maintained for legacy purpose", "group__HAL__I2S__Aliased__Macros.html", "group__HAL__I2S__Aliased__Macros" ],
    [ "HAL IRDA Aliased Macros maintained for legacy purpose", "group__HAL__IRDA__Aliased__Macros.html", "group__HAL__IRDA__Aliased__Macros" ],
    [ "HAL IWDG Aliased Macros maintained for legacy purpose", "group__HAL__IWDG__Aliased__Macros.html", "group__HAL__IWDG__Aliased__Macros" ],
    [ "HAL LPTIM Aliased Macros maintained for legacy purpose", "group__HAL__LPTIM__Aliased__Macros.html", "group__HAL__LPTIM__Aliased__Macros" ],
    [ "HAL OPAMP Aliased Macros maintained for legacy purpose", "group__HAL__OPAMP__Aliased__Macros.html", "group__HAL__OPAMP__Aliased__Macros" ],
    [ "HAL PWR Aliased Macros maintained for legacy purpose", "group__HAL__PWR__Aliased__Macros.html", "group__HAL__PWR__Aliased__Macros" ],
    [ "HAL RCC Aliased maintained for legacy purpose", "group__HAL__RCC__Aliased.html", "group__HAL__RCC__Aliased" ],
    [ "HAL RNG Aliased Macros maintained for legacy purpose", "group__HAL__RNG__Aliased__Macros.html", "group__HAL__RNG__Aliased__Macros" ],
    [ "HAL RTC Aliased Macros maintained for legacy purpose", "group__HAL__RTC__Aliased__Macros.html", "group__HAL__RTC__Aliased__Macros" ],
    [ "HAL SD/MMC Aliased Macros maintained for legacy purpose", "group__HAL__SD__Aliased__Macros.html", "group__HAL__SD__Aliased__Macros" ],
    [ "HAL SMARTCARD Aliased Macros maintained for legacy purpose", "group__HAL__SMARTCARD__Aliased__Macros.html", "group__HAL__SMARTCARD__Aliased__Macros" ],
    [ "HAL SMBUS Aliased Macros maintained for legacy purpose", "group__HAL__SMBUS__Aliased__Macros.html", "group__HAL__SMBUS__Aliased__Macros" ],
    [ "HAL SPI Aliased Macros maintained for legacy purpose", "group__HAL__SPI__Aliased__Macros.html", "group__HAL__SPI__Aliased__Macros" ],
    [ "HAL UART Aliased Macros maintained for legacy purpose", "group__HAL__UART__Aliased__Macros.html", "group__HAL__UART__Aliased__Macros" ],
    [ "HAL USART Aliased Macros maintained for legacy purpose", "group__HAL__USART__Aliased__Macros.html", "group__HAL__USART__Aliased__Macros" ],
    [ "HAL USB Aliased Macros maintained for legacy purpose", "group__HAL__USB__Aliased__Macros.html", "group__HAL__USB__Aliased__Macros" ],
    [ "HAL TIM Aliased Macros maintained for legacy purpose", "group__HAL__TIM__Aliased__Macros.html", "group__HAL__TIM__Aliased__Macros" ],
    [ "HAL ETH Aliased Macros maintained for legacy purpose", "group__HAL__ETH__Aliased__Macros.html", "group__HAL__ETH__Aliased__Macros" ],
    [ "HAL LTDC Aliased Macros maintained for legacy purpose", "group__HAL__LTDC__Aliased__Macros.html", "group__HAL__LTDC__Aliased__Macros" ],
    [ "HAL SAI Aliased Macros maintained for legacy purpose", "group__HAL__SAI__Aliased__Macros.html", "group__HAL__SAI__Aliased__Macros" ],
    [ "HAL SPDIFRX Aliased Macros maintained for legacy purpose", "group__HAL__SPDIFRX__Aliased__Macros.html", null ],
    [ "HAL HRTIM Aliased Functions maintained for legacy purpose", "group__HAL__HRTIM__Aliased__Functions.html", null ],
    [ "HAL QSPI Aliased Macros maintained for legacy purpose", "group__HAL__QSPI__Aliased__Macros.html", null ],
    [ "HAL Generic Aliased Macros maintained for legacy purpose", "group__HAL__Generic__Aliased__Macros.html", null ],
    [ "HAL PPP Aliased Macros maintained for legacy purpose", "group__HAL__PPP__Aliased__Macros.html", null ],
    [ "FMC LL Private Functions", "group__FMC__LL__Private__Functions.html", "group__FMC__LL__Private__Functions" ],
    [ "Netconn API", "group__netconn.html", "group__netconn" ],
    [ "Interface Identification API", "group__if__api.html", null ],
    [ "NETDB API", "group__netdbapi.html", null ],
    [ "NETIF API", "group__netifapi.html", "group__netifapi" ],
    [ "MQTT client", "group__mqtt.html", "group__mqtt" ],
    [ "Application layered TCP Introduction", "group__altcp__api.html", "group__altcp__api" ],
    [ "DNS", "group__dns.html", null ],
    [ "IP", "group__ip.html", "group__ip" ],
    [ "IP address handling", "group__ipaddr.html", "group__ipaddr" ],
    [ "Memory pools", "group__mempool.html", "group__mempool" ],
    [ "Network interface (NETIF)", "group__netif.html", "group__netif" ],
    [ "Packet buffers (PBUF)", "group__pbuf.html", "group__pbuf" ],
    [ "RAW", "group__raw__raw.html", null ],
    [ "Porting (system abstraction layer)", "group__sys__layer.html", "group__sys__layer" ],
    [ "TCP", "group__tcp__raw.html", null ],
    [ "UDP", "group__udp__raw.html", null ],
    [ "Options", "group__httpd__opts.html", "group__httpd__opts" ],
    [ "Options", "group__mdns__opts.html", "group__mdns__opts" ],
    [ "Options", "group__netbiosns__opts.html", "group__netbiosns__opts" ],
    [ "Options", "group__smtp__opts.html", "group__smtp__opts" ],
    [ "Options", "group__snmp__opts.html", "group__snmp__opts" ],
    [ "Options", "group__sntp__opts.html", "group__sntp__opts" ],
    [ "Options", "group__tftp__opts.html", "group__tftp__opts" ],
    [ "Error codes", "group__infrastructure__errors.html", "group__infrastructure__errors" ],
    [ "Version", "group__lwip__version.html", "group__lwip__version" ],
    [ "Options (lwipopts.h)", "group__lwip__opts.html", "group__lwip__opts" ],
    [ "IANA assigned numbers", "group__iana.html", "group__iana" ],
    [ "IEEE assigned numbers", "group__ieee.html", "group__ieee" ],
    [ "IEEE 802.1D bridge", "group__bridgeif.html", "group__bridgeif" ],
    [ "Ethernet", "group__ethernet.html", null ],
    [ "6LoWPAN (RFC4944)", "group__sixlowpan.html", null ],
    [ "6LoWPAN over BLE (RFC7668)", "group__rfc7668if.html", null ],
    [ "PPP", "group__ppp.html", null ],
    [ "SLIP", "group__slipif.html", "group__slipif" ],
    [ "ZEP - ZigBee Encapsulation Protocol", "group__zepif.html", null ],
    [ "CMSIS", "group__CMSIS.html", "group__CMSIS" ],
    [ "STM32F7xx_HAL_Examples", "group__STM32F7xx__HAL__Examples.html", "group__STM32F7xx__HAL__Examples" ],
    [ "CMSIS_Device", "group__CMSIS__Device.html", "group__CMSIS__Device" ],
    [ "STM32F7xx_HAL_Driver", "group__STM32F7xx__HAL__Driver.html", "group__STM32F7xx__HAL__Driver" ],
    [ "STM32F7xx_LL_Driver", "group__STM32F7xx__LL__Driver.html", "group__STM32F7xx__LL__Driver" ]
];