Sensorclient: PDM2PCM/App/pdm2pcm.c File Reference
pdm2pcm.c File Reference
#include "pdm2pcm.h"
Functions
void MX_PDM2PCM_Init (void)
uint8_t MX_PDM2PCM_Process (uint16_t *PDMBuf, uint16_t *PCMBuf)
Variables
PDM_Filter_Handler_t PDM1_filter_handler
PDM_Filter_Config_t PDM1_filter_config
Function Documentation
MX_PDM2PCM_Init()
void MX_PDM2PCM_Init (void)
Definition at line 35 of file pdm2pcm.c.
References PDM_Filter_Handler_t::bit_order, PDM_Filter_Config_t::decimation_factor, PDM_Filter_Handler_t::endianness, PDM_Filter_Handler_t::high_pass_tap, PDM_Filter_Handler_t::in_ptr_channels, PDM_Filter_Config_t::mic_gain, PDM_Filter_Handler_t::out_ptr_channels, PDM_Filter_Config_t::output_samples_number, PDM1_filter_config, PDM1_filter_handler, PDM_FILTER_BIT_ORDER_LSB, PDM_FILTER_DEC_FACTOR_64, PDM_FILTER_ENDIANNESS_BE, PDM_Filter_Init(), and PDM_Filter_setConfig().
Referenced by main().
MX_PDM2PCM_Process()
uint8_t MX_PDM2PCM_Process (uint16_t * PDMBuf, uint16_t * PCMBuf)
Definition at line 62 of file pdm2pcm.c.
Variable Documentation
PDM1_filter_config
PDM_Filter_Config_t PDM1_filter_config
Definition at line 29 of file pdm2pcm.c.
Referenced by MX_PDM2PCM_Init().
PDM1_filter_handler
PDM_Filter_Handler_t PDM1_filter_handler
File Name : pdm2pcm.c Description : This file provides code for the configuration of the pdm2pcm instances.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition at line 28 of file pdm2pcm.c.
Referenced by MX_PDM2PCM_Init().