Sensorclient: Core/Inc/rtc.h File Reference
rtc.h File Reference
This file contains all the function prototypes for the rtc.c file.
#include "main.h"
Functions
void MX_RTC_Init (void)
Variables
RTC_HandleTypeDef hrtc
Detailed Description
This file contains all the function prototypes for the rtc.c file.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file rtc.h.
Function Documentation
MX_RTC_Init()
void MX_RTC_Init (void)
Initialize RTC Only
Initialize RTC and set the Time and Date
Enable the TimeStamp
Definition at line 30 of file rtc.c.
References RTC_InitTypeDef::AsynchPrediv, RTC_DateTypeDef::Date, RTC_TimeTypeDef::DayLightSaving, Error_Handler(), HAL_OK, HAL_RTC_Init(), HAL_RTC_SetDate(), HAL_RTC_SetTime(), HAL_RTCEx_SetTimeStamp(), RTC_InitTypeDef::HourFormat, RTC_TimeTypeDef::Hours, hrtc, RTC_HandleTypeDef::Init, RTC_HandleTypeDef::Instance, RTC_TimeTypeDef::Minutes, RTC_DateTypeDef::Month, RTC_InitTypeDef::OutPut, RTC_InitTypeDef::OutPutPolarity, RTC_InitTypeDef::OutPutType, RTC, RTC_DAYLIGHTSAVING_NONE, RTC_FORMAT_BCD, RTC_HOURFORMAT_24, RTC_MONTH_JANUARY, RTC_OUTPUT_DISABLE, RTC_OUTPUT_POLARITY_HIGH, RTC_OUTPUT_TYPE_OPENDRAIN, RTC_STOREOPERATION_RESET, RTC_TIMESTAMPEDGE_RISING, RTC_TIMESTAMPPIN_POS1, RTC_WEEKDAY_MONDAY, RTC_TimeTypeDef::Seconds, RTC_TimeTypeDef::StoreOperation, RTC_InitTypeDef::SynchPrediv, RTC_DateTypeDef::WeekDay, and RTC_DateTypeDef::Year.
Referenced by main().
Variable Documentation
hrtc
RTC_HandleTypeDef hrtc
Definition at line 27 of file rtc.c.
Referenced by MX_RTC_Init().