Sensorclient: Core/Inc/sai.h File Reference
sai.h File Reference
This file contains all the function prototypes for the sai.c file.
#include "main.h"
Functions
void MX_SAI1_Init (void)
Variables
SAI_HandleTypeDef hsai_BlockA1
Detailed Description
This file contains all the function prototypes for the sai.c file.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file sai.h.
Function Documentation
MX_SAI1_Init()
void MX_SAI1_Init (void)
Definition at line 31 of file sai.c.
References SAI_InitTypeDef::AudioFrequency, SAI_InitTypeDef::AudioMode, SAI_InitTypeDef::CompandingMode, Error_Handler(), SAI_InitTypeDef::FIFOThreshold, HAL_OK, HAL_SAI_InitProtocol(), hsai_BlockA1, __SAI_HandleTypeDef::Init, __SAI_HandleTypeDef::Instance, SAI_InitTypeDef::MonoStereoMode, SAI_InitTypeDef::NoDivider, SAI_InitTypeDef::OutputDrive, SAI1_Block_A, SAI_ASYNCHRONOUS, SAI_AUDIO_FREQUENCY_192K, SAI_FIFOTHRESHOLD_EMPTY, SAI_MASTERDIVIDER_ENABLE, SAI_MODEMASTER_RX, SAI_NOCOMPANDING, SAI_OUTPUTDRIVE_ENABLE, SAI_PCM_LONG, SAI_PROTOCOL_DATASIZE_32BIT, SAI_STEREOMODE, SAI_SYNCEXT_DISABLE, SAI_InitTypeDef::Synchro, and SAI_InitTypeDef::SynchroExt.
Referenced by main().
Variable Documentation
hsai_BlockA1
SAI_HandleTypeDef hsai_BlockA1
File Name : SAI.c Description : This file provides code for the configuration of the SAI instances.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition at line 28 of file sai.c.