Sensorclient: Core/Src/stm32f7xx_hal_timebase_tim.c File Reference
stm32f7xx_hal_timebase_tim.c File Reference
#include "stm32f7xx_hal.h"
#include "stm32f7xx_hal_tim.h"
Functions
HAL_StatusTypeDef HAL_InitTick (uint32_t TickPriority)
This function configures the TIM6 as a time base source. The time source is configured to have 1ms time base with a dedicated Tick interrupt priority.
void HAL_SuspendTick (void)
Suspend Tick increment.
void HAL_ResumeTick (void)
Resume Tick increment.
Variables
TIM_HandleTypeDef htim6
Function Documentation
HAL_InitTick()
__weak HAL_StatusTypeDef HAL_InitTick (uint32_t TickPriority)
This function configures the TIM6 as a time base source. The time source is configured to have 1ms time base with a dedicated Tick interrupt priority.
This function configures the source of the time base. The time source is configured to have 1ms time base with a dedicated Tick interrupt priority.
Note
This function is called automatically at the beginning of program after reset by HAL_Init() or at any time when clock is configured, by HAL_RCC_ClockConfig().
Parameters
TickPriority Tick interrupt priority.
Return values
HAL status
Note
This function is called automatically at the beginning of program after reset by HAL_Init() or at any time when clock is reconfigured by HAL_RCC_ClockConfig().
In the default implementation, SysTick timer is the source of time base. It is used to generate interrupts at regular time intervals. Care must be taken if HAL_Delay() is called from a peripheral ISR process, The SysTick interrupt must have higher priority (numerically lower) than the peripheral interrupt. Otherwise the caller ISR process will be blocked. The function is declared as __weak to be overwritten in case of other implementation in user file.
Parameters
TickPriority Tick interrupt priority.
Return values
HAL status
Definition at line 41 of file stm32f7xx_hal_timebase_tim.c.
References __HAL_RCC_TIM6_CLK_ENABLE, __NVIC_PRIO_BITS, RCC_ClkInitTypeDef::APB1CLKDivider, TIM_Base_InitTypeDef::AutoReloadPreload, TIM_Base_InitTypeDef::ClockDivision, TIM_Base_InitTypeDef::CounterMode, HAL_ERROR, HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), HAL_OK, HAL_RCC_GetClockConfig(), HAL_RCC_GetPCLK1Freq(), HAL_TIM_Base_Init(), HAL_TIM_Base_Start_IT(), htim6, TIM_HandleTypeDef::Init, TIM_HandleTypeDef::Instance, TIM_Base_InitTypeDef::Period, TIM_Base_InitTypeDef::Prescaler, RCC_HCLK_DIV1, TIM6, TIM6_DAC_IRQn, TIM_AUTORELOAD_PRELOAD_DISABLE, TIM_COUNTERMODE_UP, and uwTickPrio.
Referenced by HAL_Init(), and HAL_SetTickFreq().
HAL_ResumeTick()
__weak void HAL_ResumeTick (void)
Resume Tick increment.
Note
Enable the tick increment by Enabling TIM6 update interrupt.
Parameters
None
Return values
None
Note
In the default implementation , SysTick timer is the source of time base. It is used to generate interrupts at regular time intervals. Once HAL_ResumeTick() is called, the SysTick interrupt will be enabled and so Tick increment is resumed.
This function is declared as __weak to be overwritten in case of other implementations in user file.
Return values
None
Definition at line 131 of file stm32f7xx_hal_timebase_tim.c.
References __HAL_TIM_ENABLE_IT, htim6, and TIM_IT_UPDATE.
HAL_SuspendTick()
__weak void HAL_SuspendTick (void)
Suspend Tick increment.
Note
Disable the tick increment by disabling TIM6 update interrupt.
Parameters
None
Return values
None
Note
In the default implementation , SysTick timer is the source of time base. It is used to generate interrupts at regular time intervals. Once HAL_SuspendTick() is called, the SysTick interrupt will be disabled and so Tick increment is suspended.
This function is declared as __weak to be overwritten in case of other implementations in user file.
Return values
None
Definition at line 119 of file stm32f7xx_hal_timebase_tim.c.
References __HAL_TIM_DISABLE_IT, htim6, and TIM_IT_UPDATE.
Variable Documentation
htim6
TIM_HandleTypeDef htim6
Definition at line 28 of file stm32f7xx_hal_timebase_tim.c.
Referenced by HAL_InitTick(), HAL_ResumeTick(), HAL_SuspendTick(), and TIM6_DAC_IRQHandler().