Sensorclient: Core/Inc/usart.h File Reference
usart.h File Reference
This file contains all the function prototypes for the usart.c file.
#include "main.h"
Functions
void MX_USART1_UART_Init (void)
Variables
UART_HandleTypeDef huart1
Detailed Description
This file contains all the function prototypes for the usart.c file.
Attention
Copyright (c) 2022 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file usart.h.
Function Documentation
MX_USART1_UART_Init()
void MX_USART1_UART_Init (void)
Definition at line 31 of file usart.c.
References __UART_HandleTypeDef::AdvancedInit, UART_AdvFeatureInitTypeDef::AdvFeatureInit, UART_InitTypeDef::BaudRate, Error_Handler(), HAL_OK, HAL_UART_Init(), huart1, UART_InitTypeDef::HwFlowCtl, __UART_HandleTypeDef::Init, __UART_HandleTypeDef::Instance, UART_InitTypeDef::Mode, UART_InitTypeDef::OneBitSampling, UART_InitTypeDef::OverSampling, UART_InitTypeDef::Parity, UART_InitTypeDef::StopBits, UART_ADVFEATURE_NO_INIT, UART_HWCONTROL_NONE, UART_MODE_TX_RX, UART_ONE_BIT_SAMPLE_DISABLE, UART_OVERSAMPLING_16, UART_PARITY_NONE, UART_STOPBITS_1, UART_WORDLENGTH_8B, USART1, and UART_InitTypeDef::WordLength.
Referenced by main().
Variable Documentation
huart1
UART_HandleTypeDef huart1
Definition at line 27 of file usart.c.
Referenced by main(), and MX_USART1_UART_Init().