Sensorclient: Core/Inc/waverecorder.h File Reference
waverecorder.h File Reference
#include "main.h"
Macros
#define DEFAULT_TIME_REC 30 /* Recording time in second (default: 30s) */
#define REC_WAVE_NAME "Wave.wav"
#define REC_SAMPLE_LENGTH (DEFAULT_TIME_REC * DEFAULT_AUDIO_IN_FREQ * DEFAULT_AUDIO_IN_CHANNEL_NBR * 2)
Functions
AUDIO_ErrorTypeDef AUDIO_REC_Process (void)
Manages Audio process.
AUDIO_ErrorTypeDef AUDIO_REC_Start (void)
Starts Audio streaming.
AUDIO_ErrorTypeDef AUDIO_PLAYER_Init (void)
Macro Definition Documentation
DEFAULT_TIME_REC
#define DEFAULT_TIME_REC 30 /* Recording time in second (default: 30s) */
Definition at line 30 of file waverecorder.h.
REC_SAMPLE_LENGTH
#define REC_SAMPLE_LENGTH (DEFAULT_TIME_REC * DEFAULT_AUDIO_IN_FREQ * DEFAULT_AUDIO_IN_CHANNEL_NBR * 2)
Definition at line 34 of file waverecorder.h.
REC_WAVE_NAME
#define REC_WAVE_NAME "Wave.wav"
Definition at line 32 of file waverecorder.h.
Function Documentation
AUDIO_PLAYER_Init()
AUDIO_ErrorTypeDef AUDIO_PLAYER_Init (void)
AUDIO_REC_Process()
AUDIO_ErrorTypeDef AUDIO_REC_Process (void)
Manages Audio process.
Parameters
None
Return values
Audio error
Definition at line 162 of file waverecorder.c.
References BSP_AUDIO_IN_Pause(), BSP_AUDIO_IN_Resume(), BSP_AUDIO_IN_SetVolume(), BSP_AUDIO_IN_Stop(), BSP_LCD_ClearStringLine(), BSP_LCD_DisplayStringAt(), BSP_LCD_DisplayStringAtLine(), BSP_LCD_FillCircle(), BSP_LCD_FillRect(), BSP_LCD_SetFont(), BSP_LCD_SetTextColor(), BSP_TS_GetState(), BufferCtl, DEFAULT_AUDIO_IN_CHANNEL_NBR, DEFAULT_AUDIO_IN_FREQ, display_update, HAL_Delay(), LCD_COLOR_CYAN, LCD_COLOR_RED, LCD_COLOR_YELLOW, LEFT_MODE, pHeaderBuff, REC_SAMPLE_LENGTH, TOUCH_PAUSE_XMAX, TOUCH_PAUSE_XMIN, TOUCH_PAUSE_YMAX, TOUCH_PAUSE_YMIN, TOUCH_RECORD_XMAX, TOUCH_RECORD_XMIN, TOUCH_RECORD_YMAX, TOUCH_RECORD_YMIN, TOUCH_STOP_XMAX, TOUCH_STOP_XMIN, TOUCH_STOP_YMAX, TOUCH_STOP_YMIN, TOUCH_VOL_MINUS_XMAX, TOUCH_VOL_MINUS_XMIN, TOUCH_VOL_MINUS_YMAX, TOUCH_VOL_MINUS_YMIN, TOUCH_VOL_PLUS_XMAX, TOUCH_VOL_PLUS_XMIN, TOUCH_VOL_PLUS_YMAX, TOUCH_VOL_PLUS_YMIN, TS_StateTypeDef::touchDetected, TS_StateTypeDef::touchX, TS_StateTypeDef::touchY, TS_State, uwVolume, WaveFormat, WavFile, and WavProcess_HeaderUpdate().
AUDIO_REC_Start()
AUDIO_ErrorTypeDef AUDIO_REC_Start (void)
Starts Audio streaming.
Parameters
None
Return values
Audio error
Definition at line 96 of file waverecorder.c.
References AUDIO_REC_DisplayButtons(), BSP_AUDIO_IN_Init(), BSP_AUDIO_IN_Record(), BSP_LCD_ClearStringLine(), BSP_LCD_DisplayStringAt(), BSP_LCD_DisplayStringAtLine(), BSP_LCD_SetTextColor(), BufferCtl, DEFAULT_AUDIO_IN_BIT_RESOLUTION, DEFAULT_AUDIO_IN_CHANNEL_NBR, DEFAULT_AUDIO_IN_FREQ, LCD_COLOR_CYAN, LCD_COLOR_WHITE, LEFT_MODE, pHeaderBuff, REC_WAVE_NAME, uwVolume, WavFile, and WavProcess_EncInit().