Sensorclient: Core/Src/waverecorder.c File Reference
waverecorder.c File Reference
#include "waverecorder.h"
Macros
#define TOUCH_RECORD_XMIN 300
#define TOUCH_RECORD_XMAX 340
#define TOUCH_RECORD_YMIN 212
#define TOUCH_RECORD_YMAX 252
#define TOUCH_STOP_XMIN 205
#define TOUCH_STOP_XMAX 245
#define TOUCH_STOP_YMIN 212
#define TOUCH_STOP_YMAX 252
#define TOUCH_PAUSE_XMIN 125
#define TOUCH_PAUSE_XMAX 149
#define TOUCH_PAUSE_YMIN 212
#define TOUCH_PAUSE_YMAX 252
#define TOUCH_VOL_MINUS_XMIN 20
#define TOUCH_VOL_MINUS_XMAX 70
#define TOUCH_VOL_MINUS_YMIN 212
#define TOUCH_VOL_MINUS_YMAX 252
#define TOUCH_VOL_PLUS_XMIN 402
#define TOUCH_VOL_PLUS_XMAX 452
#define TOUCH_VOL_PLUS_YMIN 212
#define TOUCH_VOL_PLUS_YMAX 252
Functions
static uint32_t WavProcess_EncInit (uint32_t Freq, uint8_t *pHeader)
Encoder initialization.
static uint32_t WavProcess_HeaderInit (uint8_t *pHeader, WAVE_FormatTypeDef *pWaveFormatStruct)
Initialize the wave header file.
static uint32_t WavProcess_HeaderUpdate (uint8_t *pHeader, WAVE_FormatTypeDef *pWaveFormatStruct)
Initialize the wave header file.
static void AUDIO_REC_DisplayButtons (void)
Display interface touch screen buttons.
AUDIO_ErrorTypeDef AUDIO_REC_Start (void)
Starts Audio streaming.
AUDIO_ErrorTypeDef AUDIO_REC_Process (void)
Manages Audio process.
void BSP_AUDIO_IN_TransferComplete_CallBack (void)
Calculates the remaining file size and new position of the pointer.
void BSP_AUDIO_IN_HalfTransfer_CallBack (void)
Manages the DMA Half Transfer complete interrupt.
Variables
uint8_t pHeaderBuff [44]
static AUDIO_IN_BufferTypeDef BufferCtl
static __IO uint32_t uwVolume = 100
WAVE_FormatTypeDef WaveFormat
FIL WavFile
static uint32_t display_update = 1
Macro Definition Documentation
TOUCH_PAUSE_XMAX
#define TOUCH_PAUSE_XMAX 149
Definition at line 35 of file waverecorder.c.
TOUCH_PAUSE_XMIN
#define TOUCH_PAUSE_XMIN 125
Definition at line 34 of file waverecorder.c.
TOUCH_PAUSE_YMAX
#define TOUCH_PAUSE_YMAX 252
Definition at line 37 of file waverecorder.c.
TOUCH_PAUSE_YMIN
#define TOUCH_PAUSE_YMIN 212
Definition at line 36 of file waverecorder.c.
TOUCH_RECORD_XMAX
#define TOUCH_RECORD_XMAX 340
Definition at line 25 of file waverecorder.c.
TOUCH_RECORD_XMIN
#define TOUCH_RECORD_XMIN 300
Definition at line 24 of file waverecorder.c.
TOUCH_RECORD_YMAX
#define TOUCH_RECORD_YMAX 252
Definition at line 27 of file waverecorder.c.
TOUCH_RECORD_YMIN
#define TOUCH_RECORD_YMIN 212
Definition at line 26 of file waverecorder.c.
TOUCH_STOP_XMAX
#define TOUCH_STOP_XMAX 245
Definition at line 30 of file waverecorder.c.
TOUCH_STOP_XMIN
#define TOUCH_STOP_XMIN 205
Definition at line 29 of file waverecorder.c.
TOUCH_STOP_YMAX
#define TOUCH_STOP_YMAX 252
Definition at line 32 of file waverecorder.c.
TOUCH_STOP_YMIN
#define TOUCH_STOP_YMIN 212
Definition at line 31 of file waverecorder.c.
TOUCH_VOL_MINUS_XMAX
#define TOUCH_VOL_MINUS_XMAX 70
Definition at line 40 of file waverecorder.c.
TOUCH_VOL_MINUS_XMIN
#define TOUCH_VOL_MINUS_XMIN 20
Definition at line 39 of file waverecorder.c.
TOUCH_VOL_MINUS_YMAX
#define TOUCH_VOL_MINUS_YMAX 252
Definition at line 42 of file waverecorder.c.
TOUCH_VOL_MINUS_YMIN
#define TOUCH_VOL_MINUS_YMIN 212
Definition at line 41 of file waverecorder.c.
TOUCH_VOL_PLUS_XMAX
#define TOUCH_VOL_PLUS_XMAX 452
Definition at line 45 of file waverecorder.c.
TOUCH_VOL_PLUS_XMIN
#define TOUCH_VOL_PLUS_XMIN 402
Definition at line 44 of file waverecorder.c.
TOUCH_VOL_PLUS_YMAX
#define TOUCH_VOL_PLUS_YMAX 252
Definition at line 47 of file waverecorder.c.
TOUCH_VOL_PLUS_YMIN
#define TOUCH_VOL_PLUS_YMIN 212
Definition at line 46 of file waverecorder.c.
Function Documentation
AUDIO_REC_DisplayButtons()
static void AUDIO_REC_DisplayButtons (void) static
Display interface touch screen buttons.
Parameters
None
Return values
None
Definition at line 634 of file waverecorder.c.
Referenced by AUDIO_REC_Start().
AUDIO_REC_Process()
AUDIO_ErrorTypeDef AUDIO_REC_Process (void)
Manages Audio process.
Parameters
None
Return values
Audio error
Definition at line 162 of file waverecorder.c.
References BSP_AUDIO_IN_Pause(), BSP_AUDIO_IN_Resume(), BSP_AUDIO_IN_SetVolume(), BSP_AUDIO_IN_Stop(), BSP_LCD_ClearStringLine(), BSP_LCD_DisplayStringAt(), BSP_LCD_DisplayStringAtLine(), BSP_LCD_FillCircle(), BSP_LCD_FillRect(), BSP_LCD_SetFont(), BSP_LCD_SetTextColor(), BSP_TS_GetState(), BufferCtl, DEFAULT_AUDIO_IN_CHANNEL_NBR, DEFAULT_AUDIO_IN_FREQ, display_update, HAL_Delay(), LCD_COLOR_CYAN, LCD_COLOR_RED, LCD_COLOR_YELLOW, LEFT_MODE, pHeaderBuff, REC_SAMPLE_LENGTH, TOUCH_PAUSE_XMAX, TOUCH_PAUSE_XMIN, TOUCH_PAUSE_YMAX, TOUCH_PAUSE_YMIN, TOUCH_RECORD_XMAX, TOUCH_RECORD_XMIN, TOUCH_RECORD_YMAX, TOUCH_RECORD_YMIN, TOUCH_STOP_XMAX, TOUCH_STOP_XMIN, TOUCH_STOP_YMAX, TOUCH_STOP_YMIN, TOUCH_VOL_MINUS_XMAX, TOUCH_VOL_MINUS_XMIN, TOUCH_VOL_MINUS_YMAX, TOUCH_VOL_MINUS_YMIN, TOUCH_VOL_PLUS_XMAX, TOUCH_VOL_PLUS_XMIN, TOUCH_VOL_PLUS_YMAX, TOUCH_VOL_PLUS_YMIN, TS_StateTypeDef::touchDetected, TS_StateTypeDef::touchX, TS_StateTypeDef::touchY, TS_State, uwVolume, WaveFormat, WavFile, and WavProcess_HeaderUpdate().
AUDIO_REC_Start()
AUDIO_ErrorTypeDef AUDIO_REC_Start (void)
Starts Audio streaming.
Parameters
None
Return values
Audio error
Definition at line 96 of file waverecorder.c.
References AUDIO_REC_DisplayButtons(), BSP_AUDIO_IN_Init(), BSP_AUDIO_IN_Record(), BSP_LCD_ClearStringLine(), BSP_LCD_DisplayStringAt(), BSP_LCD_DisplayStringAtLine(), BSP_LCD_SetTextColor(), BufferCtl, DEFAULT_AUDIO_IN_BIT_RESOLUTION, DEFAULT_AUDIO_IN_CHANNEL_NBR, DEFAULT_AUDIO_IN_FREQ, LCD_COLOR_CYAN, LCD_COLOR_WHITE, LEFT_MODE, pHeaderBuff, REC_WAVE_NAME, uwVolume, WavFile, and WavProcess_EncInit().
WavProcess_EncInit()
static uint32_t WavProcess_EncInit (uint32_t Freq, uint8_t * pHeader) static
Encoder initialization.
Parameters
Freq Sampling frequency.
pHeader Pointer to the WAV file header to be written.
Return values
0 if success, !0 else.
Definition at line 494 of file waverecorder.c.
Referenced by AUDIO_REC_Start().
WavProcess_HeaderInit()
static uint32_t WavProcess_HeaderInit (uint8_t * pHeader, WAVE_FormatTypeDef * pWaveFormatStruct) static
Initialize the wave header file.
Parameters
pHeader Header Buffer to be filled
pWaveFormatStruct Pointer to the wave structure to be filled.
Return values
0 if passed, !0 if failed.
Definition at line 522 of file waverecorder.c.
WavProcess_HeaderUpdate()
static uint32_t WavProcess_HeaderUpdate (uint8_t * pHeader, WAVE_FormatTypeDef * pWaveFormatStruct) static
Initialize the wave header file.
Parameters
pHeader Header Buffer to be filled
pWaveFormatStruct Pointer to the wave structure to be filled.
Return values
0 if passed, !0 if failed.
Definition at line 607 of file waverecorder.c.
Referenced by AUDIO_REC_Process().
Variable Documentation
BufferCtl
AUDIO_IN_BufferTypeDef BufferCtl static
Definition at line 53 of file waverecorder.c.
Referenced by AUDIO_REC_Process(), AUDIO_REC_Start(), BSP_AUDIO_IN_HalfTransfer_CallBack(), and BSP_AUDIO_IN_TransferComplete_CallBack().
display_update
uint32_t display_update = 1 static
Definition at line 57 of file waverecorder.c.
Referenced by AUDIO_REC_Process().
pHeaderBuff
uint8_t pHeaderBuff[44]
Definition at line 49 of file waverecorder.c.
Referenced by AUDIO_REC_Process(), and AUDIO_REC_Start().
uwVolume
__IO uint32_t uwVolume = 100 static
Definition at line 54 of file waverecorder.c.
Referenced by AUDIO_REC_Process(), and AUDIO_REC_Start().
WaveFormat
WAVE_FormatTypeDef WaveFormat
Referenced by AUDIO_REC_Process().
WavFile
FIL WavFile
Referenced by AUDIO_REC_Process(), and AUDIO_REC_Start().